-- Scenarios of BACKEND_SPEC §6: generated by scripts/gen-rls-tests.mjs. Do not edit.
begin;
-- Helpers (created inside the test transaction, rolled back with it).
create extension if not exists pgtap with schema extensions;
create schema if not exists tests;

-- Runs p_sql as the user of p_claims; returns the affected row count, -1 when denied (42501),
-- -2 on another error. Everything it did is rolled back.
create or replace function tests.as_user(p_claims jsonb, p_sql text, out n integer, out err text)
  language plpgsql as $$
begin
  n := 0;
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute p_sql;
    get diagnostics n = row_count;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then n := -1; err := sqlerrm;
    when others then n := -2; err := sqlstate || ' ' || sqlerrm;
  end;
end $$;

-- Rows of a table the user sees.
create or replace function tests.count_as(p_claims jsonb, p_table text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute format('select count(*) from public.%I', p_table) into v;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then v := -1;
  end;
  return v;
end $$;

-- Rows of a table matching a predicate evaluated with the user's claims (as the owner, without RLS).
create or replace function tests.count_scope(p_claims jsonb, p_table text, p_pred text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select count(*) from public.%I where coalesce((%s), false)', p_table, p_pred) into v;
  perform set_config('request.jwt.claims', '', true);
  return v;
end $$;

-- One write attempt on an own (p_own) or foreign row of the predicate: 'ok' when the outcome is the
-- expected one (or there is no such row in the data), else what happened. An insert copies the row with a
-- new key (p_sets), or — when the key is the scope itself (p_sets = '') — deletes it first and inserts it
-- again. Everything is rolled back.
create or replace function tests.check(p_claims jsonb, p_op text, p_table text, p_key text, p_pred text, p_own boolean, p_expect boolean, p_sets text)
  returns text language plpgsql as $$
declare
  v_id text;
  r record;
  v_sql text;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select %I::text from public.%I where coalesce((%s), false) = %L order by _pos limit 1', p_key, p_table, p_pred, p_own) into v_id;
  perform set_config('request.jwt.claims', '', true);
  if v_id is null then
    return 'ok';
  end if;
  begin
    if p_op = 'insert' then
      v_sql := format('insert into public.%I select * from pg_temp.tests_src', p_table);
      execute format('create temp table tests_src as select * from public.%I where %I::text = %L', p_table, p_key, v_id);
      if p_sets = '' then
        execute format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
      else
        execute format('update pg_temp.tests_src set %s', p_sets);
      end if;
      execute 'grant select on pg_temp.tests_src to authenticated';
    elsif p_op = 'update' then
      v_sql := format('update public.%I set _updated_at = now() where %I::text = %L', p_table, p_key, v_id);
    else
      v_sql := format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
    end if;
    r := tests.as_user(p_claims, v_sql);
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
  end;
  if (p_expect and r.n = 1) or (not p_expect and r.n <= 0 and r.n <> -2) then
    return 'ok';
  end if;
  return format('%s %s row %s: %s rows (%s)', p_op, case when p_own then 'own' else 'foreign' end, v_id, r.n, coalesce(r.err, ''));
end $$;

select plan(33);

-- HR isolation between companies
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select 1 from public.insured where client_id <> ''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2''')).n, 0, 'hr: sees no insured of another company');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'update public.insured set position = position where id = ''ed2683ce-b9f5-4b6f-bfb4-df3fc0b9962b''')).n, 0, 'hr: cannot update an insured person of another company');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'insert into public.policy_changes (id, client_id, client_name, policy_id, policy_number, kind, full_name, position, relation, effective_date, premium_delta, status, requested_at, requested_by_name, requested_by_id) values (gen_random_uuid(), ''0682c280-96fa-4961-a98b-5a4e1f53e2e1'', ''X'', ''970595a0-4361-4472-b871-10bac8839841'', ''N'', ''add'', ''X'', ''X'', ''employee'', current_date, 0, ''pending'', now(), ''X'', ''024b89fe-e0d0-4550-b796-5353f86b3486'')')).n, -1, 'hr: cannot request a change for another company');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'insert into public.policy_changes (id, client_id, client_name, policy_id, policy_number, kind, full_name, position, relation, effective_date, premium_delta, status, requested_at, requested_by_name, requested_by_id) select gen_random_uuid(), client_id, ''X'', id, number, ''add'', ''X'', ''X'', ''employee'', current_date, 0, ''pending'', now(), ''X'', ''024b89fe-e0d0-4550-b796-5353f86b3486'' from public.policies limit 1')).n, 1, 'hr: requests a change for the own company');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select 1 from public.claims')).n, 0, 'hr: sees no claims (medical data)');

-- Clinic only through an open visit
select is((tests.as_user('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select 1 from public.insured where id = ''706db9ea-c8c5-46d8-84e3-eb0afe448de4''')).n, 0, 'clinic: a person without a visit is invisible');
insert into public.visits (id, clinic_id, insured_id, opened_by_id, method, opened_at, expires_at) values ('00000000-0000-4000-8000-000000001001', 'd0579ad3-d8ff-44f0-bd72-00a2011c1fc5', '706db9ea-c8c5-46d8-84e3-eb0afe448de4', 'd87d459d-1000-4b7d-b5fd-369cf3032aaf', 'policy', now(), now() + interval '1 hour');
select is((tests.as_user('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select 1 from public.insured where id = ''706db9ea-c8c5-46d8-84e3-eb0afe448de4''')).n, 1, 'clinic: an open visit gives access to the patient');
update public.visits set expires_at = now() - interval '1 minute' where id = '00000000-0000-4000-8000-000000001001';
select is((tests.as_user('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select 1 from public.insured where id = ''706db9ea-c8c5-46d8-84e3-eb0afe448de4''')).n, 0, 'clinic: access ends with the visit');
select is((tests.as_user('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select 1 from public.guarantees where clinic_id <> ''d0579ad3-d8ff-44f0-bd72-00a2011c1fc5''')).n, 0, 'clinic: no guarantee letters of other clinics');

-- Assistance company by the date of the event
insert into public.assignments (policy_id, assistance_id, "from", set_by_id, set_at) values ('7e2e38e1-9a33-49c5-b971-4baf8e291136', 'a121b4af-f33d-4698-aa49-81543ec9c8af', current_date - 10, 'dcd5cca6-2ed6-4901-b4de-1ad4b8a72e1f', now());
create temp table sc_claims as select * from public.claims where id = '44d2549c-dca7-40bf-86ac-66ba2e81a26a';
update sc_claims set id = '00000000-0000-4000-8000-000000001101', number = 'T-1', insured_id = '987935ee-ca40-423a-a5ff-efafef6023af', client_id = '5ebd5870-893c-4b58-8806-28d058120711', service_date = current_date - 20;
insert into public.claims select * from sc_claims;
update sc_claims set id = '00000000-0000-4000-8000-000000001102', number = 'T-2', service_date = current_date - 5;
insert into public.claims select * from sc_claims;
select is((tests.as_user('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select 1 from public.claims where id = ''00000000-0000-4000-8000-000000001101''')).n, 0, 'assistance: an event before the assignment is not its own');
select is((tests.as_user('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select 1 from public.claims where id = ''00000000-0000-4000-8000-000000001102''')).n, 1, 'assistance: an event within the assignment is its own');
select is((tests.as_user('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select 1 from public.insured where id = ''987935ee-ca40-423a-a5ff-efafef6023af''')).n, 1, 'assistance: persons of a policy assigned today');

-- Family: children always, adults only with consent
create temp table fam_claims as select * from public.claims where id = '44d2549c-dca7-40bf-86ac-66ba2e81a26a';
update fam_claims set id = '00000000-0000-4000-8000-000000001201', number = 'T-3', insured_id = '8143b00f-1e67-48cc-bf18-3329a8133bbe', client_id = '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2';
insert into public.claims select * from fam_claims;
update fam_claims set id = '00000000-0000-4000-8000-000000001202', number = 'T-4', insured_id = 'a5f54507-110d-4a86-9f75-e4790ed9c1a1', client_id = '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2';
insert into public.claims select * from fam_claims;
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select 1 from public.claims where id = ''00000000-0000-4000-8000-000000001201''')).n, 0, 'insured: an adult family member’s claim is hidden without consent');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select 1 from public.claims where id = ''00000000-0000-4000-8000-000000001202''')).n, 1, 'insured: a child’s claim is visible');
insert into public.family_consents (id, owner_id, viewer_id, granted_at) values ('00000000-0000-4000-8000-000000001203', '8143b00f-1e67-48cc-bf18-3329a8133bbe', '3bbd3ada-60b7-451a-9ad3-30daa667beb1', now());
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select 1 from public.claims where id = ''00000000-0000-4000-8000-000000001201''')).n, 1, 'insured: visible after the adult’s consent');
update public.family_consents set revoked_at = now() where id = '00000000-0000-4000-8000-000000001203';
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select 1 from public.claims where id = ''00000000-0000-4000-8000-000000001201''')).n, 0, 'insured: hidden again after the consent is revoked');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'insert into public.family_consents (id, owner_id, viewer_id, granted_at) values (gen_random_uuid(), ''8143b00f-1e67-48cc-bf18-3329a8133bbe'', ''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', now())')).n, -1, 'insured: cannot give a consent on behalf of a family member');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select 1 from public.insured where id <> all(app.my_family_ids())')).n, 0, 'insured: sees only the own family');

-- aal2 for MIG staff, clinics and assistance companies
select is(tests.count_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal1","app_metadata":{"role":"operator"}}'::jsonb, 'claims'), 0::bigint, 'operator without the second factor sees nothing');
select ok(tests.count_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'claims') > 0, 'operator with aal2 sees claims');
select is(tests.count_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal1","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'visits'), 0::bigint, 'clinic without the second factor sees nothing');
select is(tests.count_as('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal1","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'cases'), 0::bigint, 'assistance without the second factor sees nothing');
select ok(tests.count_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'insured') > 0, 'hr works with aal1');
select is(tests.count_as('{}'::jsonb, 'clinics'), 0::bigint, 'no claims: nothing');

-- Masking: ciphertexts of identity data only through app.reveal()
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select pinfl_enc from public.insured limit 1')).n, -1, 'operator cannot select the PINFL ciphertext');
select ok((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select pinfl_mask, phone_mask, birth_date_masked, email_masked from public.insured_masked limit 1')).n = 1, 'the masked view is readable');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select app.reveal(''insured'', ''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''pinfl'', ''Call of the insured person'')')).n, 1, 'operator reveals a PINFL with a reason');
select is((tests.as_user('{"sub":"dcd5cca6-2ed6-4901-b4de-1ad4b8a72e1f","role":"authenticated","aal":"aal2","app_metadata":{"role":"underwriter"}}'::jsonb, 'select app.reveal(''insured'', ''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''pinfl'', ''reason'')')).n, -2, 'underwriter (masked) cannot reveal');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select app.reveal(''insured'', ''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''pinfl'', '''')')).n, -2, 'reveal needs a reason');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.reveal(''insured'', ''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''phone'', ''me'')')).n, 1, 'the insured reveals the own phone');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.reveal(''insured'', ''ed2683ce-b9f5-4b6f-bfb4-df3fc0b9962b'', ''phone'', ''me'')')).n, -2, 'the insured cannot reveal another person');
select is((select count(*) from public.audit_log where action = 'reveal_pii' and target_id = '3bbd3ada-60b7-451a-9ad3-30daa667beb1' and actor_id = '54bc4a41-9856-4a1e-a53b-a0ee976f364e' and _created_at = now()), 0::bigint, 'reveal attempts were rolled back with the helper');

-- anon
select is(has_table_privilege('anon', 'public.clients', 'select'), false, 'anon cannot read public tables');
select * from finish();
rollback;
