-- Audit log (BACKEND_SPEC §9) and background jobs (§10): generated by scripts/gen-rls-tests.mjs. Do not edit.
begin;
-- Helpers (created inside the test transaction, rolled back with it).
create extension if not exists pgtap with schema extensions;
create schema if not exists tests;

-- Runs p_sql as the user of p_claims; returns the affected row count, -1 when denied (42501),
-- -2 on another error. Everything it did is rolled back.
create or replace function tests.as_user(p_claims jsonb, p_sql text, out n integer, out err text)
  language plpgsql as $$
begin
  n := 0;
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute p_sql;
    get diagnostics n = row_count;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then n := -1; err := sqlerrm;
    when others then n := -2; err := sqlstate || ' ' || sqlerrm;
  end;
end $$;

-- Rows of a table the user sees.
create or replace function tests.count_as(p_claims jsonb, p_table text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute format('select count(*) from public.%I', p_table) into v;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then v := -1;
  end;
  return v;
end $$;

-- Rows of a table matching a predicate evaluated with the user's claims (as the owner, without RLS).
create or replace function tests.count_scope(p_claims jsonb, p_table text, p_pred text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select count(*) from public.%I where coalesce((%s), false)', p_table, p_pred) into v;
  perform set_config('request.jwt.claims', '', true);
  return v;
end $$;

-- One write attempt on an own (p_own) or foreign row of the predicate: 'ok' when the outcome is the
-- expected one (or there is no such row in the data), else what happened. An insert copies the row with a
-- new key (p_sets), or — when the key is the scope itself (p_sets = '') — deletes it first and inserts it
-- again. Everything is rolled back.
create or replace function tests.check(p_claims jsonb, p_op text, p_table text, p_key text, p_pred text, p_own boolean, p_expect boolean, p_sets text)
  returns text language plpgsql as $$
declare
  v_id text;
  r record;
  v_sql text;
  v_cols text;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select %I::text from public.%I where coalesce((%s), false) = %L order by _pos limit 1', p_key, p_table, p_pred, p_own) into v_id;
  perform set_config('request.jwt.claims', '', true);
  if v_id is null then
    return 'ok';
  end if;
  begin
    if p_op = 'insert' then
      -- Generated columns (search keys of the lists) are computed by the table, never inserted.
      select string_agg(quote_ident(attname), ', ' order by attnum) into v_cols from pg_attribute
        where attrelid = format('public.%I', p_table)::regclass and attnum > 0 and not attisdropped and attgenerated = '';
      v_sql := format('insert into public.%I (%s) select %s from pg_temp.tests_src', p_table, v_cols, v_cols);
      execute format('create temp table tests_src as select * from public.%I where %I::text = %L', p_table, p_key, v_id);
      if p_sets = '' then
        execute format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
      else
        execute format('update pg_temp.tests_src set %s', p_sets);
      end if;
      execute 'grant select on pg_temp.tests_src to authenticated';
    elsif p_op = 'update' then
      v_sql := format('update public.%I set _updated_at = now() where %I::text = %L', p_table, p_key, v_id);
    else
      v_sql := format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
    end if;
    r := tests.as_user(p_claims, v_sql);
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
  end;
  if (p_expect and r.n = 1) or (not p_expect and r.n <= 0 and r.n <> -2) then
    return 'ok';
  end if;
  return format('%s %s row %s: %s rows (%s)', p_op, case when p_own then 'own' else 'foreign' end, v_id, r.n, coalesce(r.err, ''));
end $$;

select plan(19);
select ok((select ok from app.verify_audit_chain()), 'the seeded audit chain verifies');
select is((select checked from app.verify_audit_chain()), (select count(*) from public.audit_log), 'every entry is checked');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'insert into public.audit_log (id, "at", actor_id, actor_name, actor_role, action, target_type) values (gen_random_uuid(), now(), gen_random_uuid(), ''x'', ''admin'', ''login'', ''session'')')).n, -1, 'authenticated cannot insert into audit_log directly');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'update public.audit_log set reason = ''x''')).n, -1, 'authenticated cannot update audit_log');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'delete from public.audit_log')).n, -1, 'authenticated cannot delete from audit_log');
select is((tests.as_user('{"sub":"da7c7e13-c39a-4a58-9253-779029c7d238","role":"authenticated","aal":"aal2","app_metadata":{"role":"admin"}}'::jsonb, 'select app.audit(''export'', ''export'', null, null, ''test'', null, ''Admin'', gen_random_uuid(), ''operator'')')).n, 1, 'app.audit writes for a signed-in user');
select app.audit('export', 'export', null, 'test-entry', 'test', null, 'Admin', '00000000-0000-4000-8000-000000000001', 'operator');
select is((select count(*) from public.audit_log where target_label = 'test-entry'), 1::bigint, 'the system writes through app.audit');
select ok((select ok from app.verify_audit_chain()), 'the chain still verifies after new entries');
select throws_ok($$ update public.audit_log set reason = 'x' where id = 'd291562d-530d-4e29-b71f-91e26ad78dac' $$, '42501', 'audit_log is append-only', 'even the owner cannot update an entry');
select throws_ok($$ delete from public.audit_log where id = 'd291562d-530d-4e29-b71f-91e26ad78dac' $$, '42501', 'audit_log is append-only', 'even the owner cannot delete an entry');
select throws_ok($$ truncate public.audit_log $$, '42501', 'audit_log is append-only', 'even the owner cannot truncate');
select is((tests.as_user('{"sub":"da7c7e13-c39a-4a58-9253-779029c7d238","role":"authenticated","aal":"aal2","app_metadata":{"role":"admin"}}'::jsonb, 'select app.verify_audit_chain()')).n, -1, 'users cannot call the verification directly');
alter table public.audit_log disable trigger audit_log_no_update;
update public.audit_log set reason = 'tampered' where id = 'd291562d-530d-4e29-b71f-91e26ad78dac';
alter table public.audit_log enable trigger audit_log_no_update;
select is((select ok from app.verify_audit_chain()), false, 'a changed entry breaks the chain');
select is((select first_broken from app.verify_audit_chain()), 'd291562d-530d-4e29-b71f-91e26ad78dac'::uuid, 'the first broken entry is reported');
select is(app.job_verify_audit_chain(), false, 'the daily job detects the break');
select ok((select count(*) from public.notifications n join public.staff s on s.id = n.user_id where n.text = 'srv.auditChainBroken' and s.role = 'admin') > 0, 'every admin is notified');
select ok(app.job_cleanup_expired() ? 'sessions', 'the cleanup job runs');
select ok(not exists (select 1 from app.job_catalog where runner = 'db' and name not in (select replace(jobname, 'mig:', '') from cron.job)), 'db jobs are scheduled in pg_cron');
select is((select count(*) from cron.job where jobname like 'mig:%'), (select count(*) from app.job_catalog), 'every job of jobs.ts is scheduled');
select * from finish();
rollback;
