-- Sessions, sign-in, identity sync, the token hook, cleanup and files (BACKEND_SPEC §7, §8, §10): generated by scripts/gen-rls-tests.mjs. Do not edit.
begin;
-- Helpers (created inside the test transaction, rolled back with it).
create extension if not exists pgtap with schema extensions;
create schema if not exists tests;

-- Runs p_sql as the user of p_claims; returns the affected row count, -1 when denied (42501),
-- -2 on another error. Everything it did is rolled back.
create or replace function tests.as_user(p_claims jsonb, p_sql text, out n integer, out err text)
  language plpgsql as $$
begin
  n := 0;
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute p_sql;
    get diagnostics n = row_count;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then n := -1; err := sqlerrm;
    when others then n := -2; err := sqlstate || ' ' || sqlerrm;
  end;
end $$;

-- Rows of a table the user sees.
create or replace function tests.count_as(p_claims jsonb, p_table text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute format('select count(*) from public.%I', p_table) into v;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then v := -1;
  end;
  return v;
end $$;

-- Rows of a table matching a predicate evaluated with the user's claims (as the owner, without RLS).
create or replace function tests.count_scope(p_claims jsonb, p_table text, p_pred text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select count(*) from public.%I where coalesce((%s), false)', p_table, p_pred) into v;
  perform set_config('request.jwt.claims', '', true);
  return v;
end $$;

-- One write attempt on an own (p_own) or foreign row of the predicate: 'ok' when the outcome is the
-- expected one (or there is no such row in the data), else what happened. An insert copies the row with a
-- new key (p_sets), or — when the key is the scope itself (p_sets = '') — deletes it first and inserts it
-- again. Everything is rolled back.
create or replace function tests.check(p_claims jsonb, p_op text, p_table text, p_key text, p_pred text, p_own boolean, p_expect boolean, p_sets text)
  returns text language plpgsql as $$
declare
  v_id text;
  r record;
  v_sql text;
  v_cols text;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select %I::text from public.%I where coalesce((%s), false) = %L order by _pos limit 1', p_key, p_table, p_pred, p_own) into v_id;
  perform set_config('request.jwt.claims', '', true);
  if v_id is null then
    return 'ok';
  end if;
  begin
    if p_op = 'insert' then
      -- Generated columns (search keys of the lists) are computed by the table, never inserted.
      select string_agg(quote_ident(attname), ', ' order by attnum) into v_cols from pg_attribute
        where attrelid = format('public.%I', p_table)::regclass and attnum > 0 and not attisdropped and attgenerated = '';
      v_sql := format('insert into public.%I (%s) select %s from pg_temp.tests_src', p_table, v_cols, v_cols);
      execute format('create temp table tests_src as select * from public.%I where %I::text = %L', p_table, p_key, v_id);
      if p_sets = '' then
        execute format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
      else
        execute format('update pg_temp.tests_src set %s', p_sets);
      end if;
      execute 'grant select on pg_temp.tests_src to authenticated';
    elsif p_op = 'update' then
      v_sql := format('update public.%I set _updated_at = now() where %I::text = %L', p_table, p_key, v_id);
    else
      v_sql := format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
    end if;
    r := tests.as_user(p_claims, v_sql);
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
  end;
  if (p_expect and r.n = 1) or (not p_expect and r.n <= 0 and r.n <> -2) then
    return 'ok';
  end if;
  return format('%s %s row %s: %s rows (%s)', p_op, case when p_own then 'own' else 'foreign' end, v_id, r.n, coalesce(r.err, ''));
end $$;

create or replace function tests.private_buckets() returns boolean
  language plpgsql as $$
begin
  if to_regclass('storage.buckets') is null then
    return true;
  end if;
  return (select count(*) from storage.buckets where id = any(array['receipts', 'contract-scans', 'guarantee-attachments', 'documents', 'help-assets']) and not public) = 5;
end $$;
select plan(27);
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select 1 from public.app_sessions')).n, -1, 'authenticated cannot read app_sessions');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'delete from public.app_sessions')).n, -1, 'authenticated cannot delete from app_sessions');
select ok(not has_table_privilege('anon', 'public.app_sessions', 'select'), 'anon cannot read app_sessions');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select 1 from public.app_auth_challenges')).n, -1, 'authenticated cannot read app_auth_challenges');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'delete from public.app_auth_challenges')).n, -1, 'authenticated cannot delete from app_auth_challenges');
select ok(not has_table_privilege('anon', 'public.app_auth_challenges', 'select'), 'anon cannot read app_auth_challenges');
select is((public.custom_access_token_hook('{"user_id":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","authentication_method":"password","claims":{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","aud":"authenticated","role":"authenticated","aal":"aal1","app_metadata":{"provider":"email","providers":["email"],"role":"hr","company_id":"00000000-0000-4000-8000-000000000009","is_admin":true},"user_metadata":{"role":"admin"}}}'::jsonb) -> 'claims' -> 'app_metadata'), '{"provider": "email", "providers": ["email"], "role": "hr", "company_id": "00000000-0000-4000-8000-000000000009"}'::jsonb, 'the access token hook keeps only the role and bindings of app_metadata');
select is((public.custom_access_token_hook('{"user_id":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","authentication_method":"password","claims":{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","aud":"authenticated","role":"authenticated","aal":"aal1","app_metadata":{"provider":"email","providers":["email"],"role":"hr","company_id":"00000000-0000-4000-8000-000000000009","is_admin":true},"user_metadata":{"role":"admin"}}}'::jsonb) -> 'claims' -> 'user_metadata'), '{}'::jsonb, 'user_metadata never reaches the token');
select is((public.custom_access_token_hook('{"user_id":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","authentication_method":"password","claims":{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","aud":"authenticated","role":"authenticated","aal":"aal1","app_metadata":{"provider":"email","providers":["email"],"role":"hr","company_id":"00000000-0000-4000-8000-000000000009","is_admin":true},"user_metadata":{"role":"admin"}}}'::jsonb) -> 'claims' ->> 'sub'), '54bc4a41-9856-4a1e-a53b-a0ee976f364e', 'the required claims stay');
select ok(not has_function_privilege('authenticated', 'public.custom_access_token_hook(jsonb)', 'execute'), 'users cannot call the access token hook');
select ok(not has_function_privilege('anon', 'public.custom_access_token_hook(jsonb)', 'execute'), 'anon cannot call the access token hook');
select ok(not exists (select 1 from pg_roles where rolname = 'supabase_auth_admin') or has_function_privilege('supabase_auth_admin', 'public.custom_access_token_hook(jsonb)', 'execute'), 'Supabase Auth may call the hook');
select is((select count(*) from app.identity_sync), 0::bigint, 'the seed queues no identity sync');
update public.staff set role = 'legal' where id = '54bc4a41-9856-4a1e-a53b-a0ee976f364e';
select is((select count(*) from app.identity_sync where user_id = '54bc4a41-9856-4a1e-a53b-a0ee976f364e'), 1::bigint, 'a role change queues the identity sync');
insert into public.hr_users (id, email, full_name, company_id) values ('00000000-0000-4000-8000-000000000031', 'new-hr@test.uz', 'Test', '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2');
select is((select count(*) from app.identity_sync where user_id = '00000000-0000-4000-8000-000000000031'), 1::bigint, 'a new account queues the identity sync');
select is((tests.as_user('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select 1 from app.identity_sync')).n, -1, 'users cannot read the identity queue');
insert into public.sessions (id, user_id, role, created_at, last_activity) values ('t-fresh', '54bc4a41-9856-4a1e-a53b-a0ee976f364e', 'operator', (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint);
insert into public.app_sessions (id_hash, session_id, user_id, role, aal, refresh_enc, refresh_key_ver, access_enc, access_key_ver, access_expires_at, created_at, last_activity) values (convert_to('t-fresh', 'UTF8'), 't-fresh', '54bc4a41-9856-4a1e-a53b-a0ee976f364e', 'operator', 'aal2', '\x00', 1, '\x00', 1, now(), now(), now() - interval '1 minute');
insert into public.sessions (id, user_id, role, created_at, last_activity) values ('t-idle', '54bc4a41-9856-4a1e-a53b-a0ee976f364e', 'operator', (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint);
insert into public.app_sessions (id_hash, session_id, user_id, role, aal, refresh_enc, refresh_key_ver, access_enc, access_key_ver, access_expires_at, created_at, last_activity) values (convert_to('t-idle', 'UTF8'), 't-idle', '54bc4a41-9856-4a1e-a53b-a0ee976f364e', 'operator', 'aal2', '\x00', 1, '\x00', 1, now(), now(), now() - interval '40 minutes');
delete from public.sessions where id = 't-fresh';
select is((select count(*) from public.app_sessions where session_id = 't-fresh'), 0::bigint, 'ending a session ends its BFF row');
insert into public.app_auth_challenges (id_hash, kind, lock_key, expires_at) values ('\x01', 'password', 'k', now() - interval '1 minute'), ('\x02', 'phone', 'k', now() + interval '5 minutes');
select ok((app.job_cleanup_expired() ->> 'app_sessions')::int >= 1, 'the cleanup job ends idle BFF sessions');
select is((select count(*) from public.app_sessions where session_id = 't-idle'), 0::bigint, 'the idle session is gone');
select is((select count(*) from public.app_auth_challenges), 1::bigint, 'expired sign-in challenges are gone, live ones stay');
select has_column('public', 'files', 'bucket', 'files.bucket');
select has_column('public', 'files', 'object_name', 'files.object_name');
select has_column('public', 'files', 'sha256', 'files.sha256');
select throws_ok($$ insert into public.files (id, mime, bucket) values ('00000000-0000-4000-8000-000000000041', 'image/png', 'receipts') $$, '23514', null, 'a bucket needs an object name');
select throws_ok($$ insert into public.files (id, mime, bucket, object_name, sha256) values ('00000000-0000-4000-8000-000000000042', 'image/png', 'public', '00000000-0000-4000-8000-000000000042', '0000000000000000000000000000000000000000000000000000000000000000') $$, '23514', null, 'only the private buckets');
select ok(tests.private_buckets(), 'the buckets of Storage are private (where Storage is installed)');
select ok(has_table_privilege('service_role', 'app.job_queue', 'update'), 'the API worker takes queued jobs');
select * from finish();
rollback;
