-- Narrow facts and the policies that replaced privileged reads (docs/PRIVILEGED_AUDIT.md): generated by scripts/gen-rls-tests.mjs. Do not edit.
begin;
-- Helpers (created inside the test transaction, rolled back with it).
create extension if not exists pgtap with schema extensions;
create schema if not exists tests;

-- Runs p_sql as the user of p_claims; returns the affected row count, -1 when denied (42501),
-- -2 on another error. Everything it did is rolled back.
create or replace function tests.as_user(p_claims jsonb, p_sql text, out n integer, out err text)
  language plpgsql as $$
begin
  n := 0;
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute p_sql;
    get diagnostics n = row_count;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then n := -1; err := sqlerrm;
    when others then n := -2; err := sqlstate || ' ' || sqlerrm;
  end;
end $$;

-- Rows of a table the user sees.
create or replace function tests.count_as(p_claims jsonb, p_table text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute format('select count(*) from public.%I', p_table) into v;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then v := -1;
  end;
  return v;
end $$;

-- Rows of a table matching a predicate evaluated with the user's claims (as the owner, without RLS).
create or replace function tests.count_scope(p_claims jsonb, p_table text, p_pred text) returns bigint
  language plpgsql as $$
declare
  v bigint;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select count(*) from public.%I where coalesce((%s), false)', p_table, p_pred) into v;
  perform set_config('request.jwt.claims', '', true);
  return v;
end $$;

-- One write attempt on an own (p_own) or foreign row of the predicate: 'ok' when the outcome is the
-- expected one (or there is no such row in the data), else what happened. An insert copies the row with a
-- new key (p_sets), or — when the key is the scope itself (p_sets = '') — deletes it first and inserts it
-- again. Everything is rolled back.
create or replace function tests.check(p_claims jsonb, p_op text, p_table text, p_key text, p_pred text, p_own boolean, p_expect boolean, p_sets text)
  returns text language plpgsql as $$
declare
  v_id text;
  r record;
  v_sql text;
begin
  perform set_config('request.jwt.claims', p_claims::text, true);
  execute format('select %I::text from public.%I where coalesce((%s), false) = %L order by _pos limit 1', p_key, p_table, p_pred, p_own) into v_id;
  perform set_config('request.jwt.claims', '', true);
  if v_id is null then
    return 'ok';
  end if;
  begin
    if p_op = 'insert' then
      v_sql := format('insert into public.%I select * from pg_temp.tests_src', p_table);
      execute format('create temp table tests_src as select * from public.%I where %I::text = %L', p_table, p_key, v_id);
      if p_sets = '' then
        execute format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
      else
        execute format('update pg_temp.tests_src set %s', p_sets);
      end if;
      execute 'grant select on pg_temp.tests_src to authenticated';
    elsif p_op = 'update' then
      v_sql := format('update public.%I set _updated_at = now() where %I::text = %L', p_table, p_key, v_id);
    else
      v_sql := format('delete from public.%I where %I::text = %L', p_table, p_key, v_id);
    end if;
    r := tests.as_user(p_claims, v_sql);
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
  end;
  if (p_expect and r.n = 1) or (not p_expect and r.n <= 0 and r.n <> -2) then
    return 'ok';
  end if;
  return format('%s %s row %s: %s rows (%s)', p_op, case when p_own then 'own' else 'foreign' end, v_id, r.n, coalesce(r.err, ''));
end $$;

-- The value of one statement run as the user ('denied' on 42501, 'error: <state>' on another error); rolled back.
create or replace function tests.value_as(p_claims jsonb, p_sql text) returns text
  language plpgsql as $$
declare
  v text;
begin
  begin
    perform set_config('request.jwt.claims', p_claims::text, true);
    execute 'set local role authenticated';
    execute p_sql into v;
    raise exception using errcode = 'TSTRB';
  exception
    when sqlstate 'TSTRB' then null;
    when insufficient_privilege then v := 'denied';
    when others then v := 'error: ' || sqlstate;
  end;
  return v;
end $$;

select plan(113);

-- app.fact_client_insured_count: whoever sees the client
select is(tests.value_as('{"sub":"dcd5cca6-2ed6-4901-b4de-1ad4b8a72e1f","role":"authenticated","aal":"aal2","app_metadata":{"role":"underwriter"}}'::jsonb, 'select app.fact_client_insured_count(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), (select count(*)::text from public.insured where client_id = '0682c280-96fa-4961-a98b-5a4e1f53e2e1' and status = 'active'), 'insured count: the underwriter of any client');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_client_insured_count(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'')'), (select count(*)::text from public.insured where client_id = '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2' and status = 'active'), 'insured count: HR of the own company');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_client_insured_count(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), 'denied', 'insured count: HR of another company is refused');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_client_insured_count(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'')'), 'denied', 'insured count: the insured person is refused');
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_client_insured_count(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), 'denied', 'insured count: a role without the client is refused');

-- app.fact_client_legal_form: MIG staff, HR of the own company
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_client_legal_form(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), 'private_enterprise', 'legal form: any MIG employee');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_client_legal_form(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'')'), (select legal_form from public.clients where id = '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'), 'legal form: HR of the own company');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_client_legal_form(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), 'denied', 'legal form: HR of another company is refused');
select is(tests.value_as('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_client_legal_form(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), 'denied', 'legal form: a clinic is refused');

-- app.fact_client_claim_figures / invoice figures / policy brief / history: clients.read only, anonymous
select is(tests.value_as('{"sub":"dcd5cca6-2ed6-4901-b4de-1ad4b8a72e1f","role":"authenticated","aal":"aal2","app_metadata":{"role":"underwriter"}}'::jsonb, 'select jsonb_array_length(app.fact_client_claim_figures(''0682c280-96fa-4961-a98b-5a4e1f53e2e1''))'), (select count(*)::text from public.claims where client_id = '0682c280-96fa-4961-a98b-5a4e1f53e2e1'), 'claim figures: every claim of the client for clients.read');
select is(tests.value_as('{"sub":"dcd5cca6-2ed6-4901-b4de-1ad4b8a72e1f","role":"authenticated","aal":"aal2","app_metadata":{"role":"underwriter"}}'::jsonb, 'select bool_and(not (x ? ''number'') and not (x ? ''insuredId'') and not (x ? ''insuredName'') and not (x ? ''providerName''))::text from jsonb_array_elements(app.fact_client_claim_figures(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')) x'), 'true', 'claim figures: no number, person or provider');
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_client_claim_figures(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')::text'), 'denied', 'claim figures: a role without clients.read is refused');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_client_claim_figures(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'')::text'), 'denied', 'claim figures: HR (no clients.read) is refused for the own company too');
select is(tests.value_as('{"sub":"da7c7e13-c39a-4a58-9253-779029c7d238","role":"authenticated","aal":"aal2","app_metadata":{"role":"admin"}}'::jsonb, 'select jsonb_array_length(app.fact_client_invoice_figures(''0682c280-96fa-4961-a98b-5a4e1f53e2e1''))'), (select count(*)::text from public.invoices where client_id = '0682c280-96fa-4961-a98b-5a4e1f53e2e1'), 'invoice figures: the admin (no invoice access) gets the numbers of the client card');
select is(tests.value_as('{"sub":"7506834c-5d16-478c-9783-971a89d1ceb2","role":"authenticated","aal":"aal2","app_metadata":{"role":"claims_officer"}}'::jsonb, 'select app.fact_client_invoice_figures(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')::text'), 'denied', 'invoice figures: a role without clients.read is refused');
select is(tests.value_as('{"sub":"da7c7e13-c39a-4a58-9253-779029c7d238","role":"authenticated","aal":"aal2","app_metadata":{"role":"admin"}}'::jsonb, 'select app.fact_policy_brief(''970595a0-4361-4472-b871-10bac8839841'') ->> ''number'''), (select number from public.policies where id = '970595a0-4361-4472-b871-10bac8839841'), 'policy brief: the admin (no policy access) gets the number');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_policy_brief(''970595a0-4361-4472-b871-10bac8839841'')::text'), 'denied', 'policy brief: HR is refused');
select is(tests.value_as('{"sub":"b6a714d4-267a-49cc-b7a6-fb3972b746f1","role":"authenticated","aal":"aal2","app_metadata":{"role":"sales_manager"}}'::jsonb, 'select count(*)::text from jsonb_array_elements(app.fact_client_history(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'', 50)) x where x ->> ''action'' in (''reveal_pii'', ''open_medical'') or x ? ''reason'''), '0', 'client history: no openings of personal or medical data, no reasons');
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_client_history(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'', 50)::text'), 'denied', 'client history: a role without clients.read is refused');

-- app.fact_company_claim_count: HR of the own company only
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_company_claim_count(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'', 0)'), (select count(*)::text from public.claims c join public.insured i on i.id = c.insured_id where i.client_id = '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2' and i.status = 'active'), 'company claim count: HR of the own company');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_company_claim_count(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'', 0)'), 'denied', 'company claim count: HR of another company is refused');
select is(tests.value_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select app.fact_company_claim_count(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'', 0)'), 'denied', 'company claim count: MIG staff use their own access');

-- app.fact_person_access_log: MIG card readers, persons they read
select is(tests.value_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select jsonb_array_length(app.fact_person_access_log(''3bbd3ada-60b7-451a-9ad3-30daa667beb1''))'), (select count(*)::text from public.audit_log where target_id = '3bbd3ada-60b7-451a-9ad3-30daa667beb1' and action in ('reveal_pii', 'open_medical')), 'access log: the operator reads the openings of a person');
select is(tests.value_as('{"sub":"88ccd81f-fa26-4562-ac7f-a68930c62d15","role":"authenticated","aal":"aal2","app_metadata":{"role":"accountant"}}'::jsonb, 'select app.fact_person_access_log(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'')::text'), 'denied', 'access log: the accountant (names only) is refused');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_person_access_log(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'')::text'), 'denied', 'access log: HR is refused');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_person_access_log(''706db9ea-c8c5-46d8-84e3-eb0afe448de4'')::text'), 'denied', 'access log: a clinic is refused');

-- app.fact_own_audit_entries: own openings only
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select jsonb_array_length(app.fact_own_audit_entries(''89366724-81b8-405d-bf79-63e84207f156'', array[''reveal_pii'', ''open_medical''], null))'), (select count(*)::text from public.audit_log where actor_id = '89366724-81b8-405d-bf79-63e84207f156' and action in ('reveal_pii', 'open_medical')), 'own entries: the doctor reads the own openings');
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_own_audit_entries(''54bc4a41-9856-4a1e-a53b-a0ee976f364e'', array[''open_medical''], null)::text'), 'denied', 'own entries: another employee’s entries are refused');
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_own_audit_entries(''89366724-81b8-405d-bf79-63e84207f156'', array[''login''], null)::text'), 'denied', 'own entries: only openings of data');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_own_audit_entries(''59f577ba-4115-4ea2-ba60-f2454cb8ffc1'', array[''open_medical''], null)::text'), 'denied', 'own entries: not for the insured person');

-- card_tokens: the insured person issues tokens of self and the active family under them, nobody else
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'insert into public.card_tokens (token, short_code, insured_id, expires_at) values (''t-child'', ''CCCC3333'', ''8143b00f-1e67-48cc-bf18-3329a8133bbe'', 1)')).n, 1, 'card token: of a child of the family');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'insert into public.card_tokens (token, short_code, insured_id, expires_at) values (''t-stranger'', ''DDDD4444'', ''24c28bf6-00a2-4562-a372-c88cbe2da8e2'', 1)')).n, -1, 'card token: not of a person of another family');

-- deal_events: HR writes events of the own company’s deal only
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'insert into public.deal_events (id, deal_id, "at", actor_name, text) values (gen_random_uuid(), ''75014162-224a-4052-a6fa-fcdf96ffa1ca'', now(), ''HR'', ''x'')')).n, 1, 'deal events: HR of the own company’s deal');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'insert into public.deal_events (id, deal_id, "at", actor_name, text) values (gen_random_uuid(), ''248399a4-7e67-4fed-ab20-bda6f9ec46d7'', now(), ''HR'', ''x'')')).n, -1, 'deal events: not into another company’s deal');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select 1 from public.deal_events')).n, 0, 'deal events: HR still reads nothing');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'insert into public.deal_events (id, deal_id, "at", actor_name, text) values (gen_random_uuid(), ''248399a4-7e67-4fed-ab20-bda6f9ec46d7'', now(), ''X'', ''x'')')).n, -1, 'deal events: the insured person writes nothing');

-- webhook_deliveries: the partner’s integration admin records a retry of its own deliveries
insert into public.webhook_deliveries (id, endpoint_id, clinic_id, event, status, attempts, last_attempt_at, object_id, body, signature) select '00000000-0000-4000-8000-000000002001', w.id, w.clinic_id, 'guarantee.decided', 'failed', 1, now(), gen_random_uuid(), '{}', '' from public.webhooks w where w.clinic_id = 'd0579ad3-d8ff-44f0-bd72-00a2011c1fc5' limit 1;
insert into public.webhook_deliveries (id, endpoint_id, clinic_id, event, status, attempts, last_attempt_at, object_id, body, signature) select '00000000-0000-4000-8000-000000002002', w.id, w.clinic_id, 'guarantee.decided', 'failed', 1, now(), gen_random_uuid(), '{}', '' from public.webhooks w where w.clinic_id <> 'd0579ad3-d8ff-44f0-bd72-00a2011c1fc5' limit 1;
select ok((tests.as_user('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'update public.webhook_deliveries set attempts = 2 where id = ''00000000-0000-4000-8000-000000002001''')).n = (select count(*)::int from public.webhook_deliveries where id = '00000000-0000-4000-8000-000000002001'), 'webhook deliveries: the clinic admin updates an own delivery');
select is((tests.as_user('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'update public.webhook_deliveries set attempts = 2 where id = ''00000000-0000-4000-8000-000000002002''')).n, 0, 'webhook deliveries: not another partner’s delivery');
select is((tests.as_user('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'update public.webhook_deliveries set attempts = 2')).n, 0, 'webhook deliveries: the registrar updates nothing');
select is((tests.as_user('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'insert into public.webhook_deliveries (id, endpoint_id, clinic_id, event, status, attempts, last_attempt_at, object_id, body, signature) select gen_random_uuid(), endpoint_id, clinic_id, event, status, attempts, last_attempt_at, object_id, body, signature from public.webhook_deliveries limit 1')).n, -1, 'webhook deliveries: the outbox itself stays the system’s');

-- price_lists / clinic_contracts: every user of an assistance company, own contracts only
select ok(tests.count_as('{"sub":"ec08bc53-418b-47d6-a5e5-c8d56196f5f1","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_admin","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'price_lists') = (select count(*) from public.price_lists), 'price lists: the assistance admin reads the network list');
select is(tests.count_as('{"sub":"ec08bc53-418b-47d6-a5e5-c8d56196f5f1","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_admin","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'clinic_contracts'), (select count(*) from public.clinic_contracts where payer = 'a121b4af-f33d-4698-aa49-81543ec9c8af'), 'clinic contracts: the assistance admin reads only its own contracts');
select is(tests.count_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'price_lists'), 0::bigint, 'price lists: the insured person reads none');

-- app.fact_advance_deal: forward only, HR of the own company
select is(tests.value_as('{"sub":"e6a763ef-810d-4380-9d2d-fea2aff9b2fb","role":"authenticated","aal":"aal2","app_metadata":{"role":"legal"}}'::jsonb, 'select app.fact_advance_deal(''248399a4-7e67-4fed-ab20-bda6f9ec46d7'', ''lead'', array[''lead'', ''census'', ''quote'', ''kp_sent'', ''kp_accepted'', ''contract_draft'', ''contract_review'', ''contract_sent'', ''signing'', ''awaiting_payment'', ''active''], now())::text'), (select (stage = 'lead')::text from public.deals where id = '248399a4-7e67-4fed-ab20-bda6f9ec46d7'), 'advance deal: never backwards');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_advance_deal(''248399a4-7e67-4fed-ab20-bda6f9ec46d7'', ''active'', array[''lead'', ''census'', ''quote'', ''kp_sent'', ''kp_accepted'', ''contract_draft'', ''contract_review'', ''contract_sent'', ''signing'', ''awaiting_payment'', ''active''], now())::text'), 'denied', 'advance deal: HR of another company is refused');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_advance_deal(''248399a4-7e67-4fed-ab20-bda6f9ec46d7'', ''active'', array[''lead'', ''census'', ''quote'', ''kp_sent'', ''kp_accepted'', ''contract_draft'', ''contract_review'', ''contract_sent'', ''signing'', ''awaiting_payment'', ''active''], now())::text'), 'denied', 'advance deal: the insured person is refused');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_advance_deal(''75014162-224a-4052-a6fa-fcdf96ffa1ca'', ''active'', array[''lead'', ''census'', ''quote'', ''kp_sent'', ''kp_accepted'', ''contract_draft'', ''contract_review'', ''contract_sent'', ''signing'', ''awaiting_payment'', ''active''], now())::text'), (select (stage <> 'lost')::text from public.deals where id = '75014162-224a-4052-a6fa-fcdf96ffa1ca'), 'advance deal: HR of the own company');

-- app.fact_push_clinic_event: anyone signed in, a clinic only into its own feed
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_push_clinic_event(gen_random_uuid(), ''e7c2d8f6-5340-4e44-bd98-8adeacea2251'', now(), ''x'')::text'), '', 'clinic event: written for a booking of the insured person');
select is(tests.value_as('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_push_clinic_event(gen_random_uuid(), ''e7c2d8f6-5340-4e44-bd98-8adeacea2251'', now(), ''x'')::text'), 'denied', 'clinic event: a clinic cannot write into another clinic’s feed');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_push_clinic_event(gen_random_uuid(), gen_random_uuid(), now(), ''x'')::text'), 'denied', 'clinic event: only of an existing clinic');
select is((tests.as_user('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'insert into public.clinic_events (id, clinic_id, "at", text) values (gen_random_uuid(), ''e7c2d8f6-5340-4e44-bd98-8adeacea2251'', now(), ''x'')')).n, -1, 'clinic event: no direct insert');

-- app.fact_append_client_log: MIG staff, HR of the own company
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_append_client_log(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'', ''{"at": "2026-01-01T00:00:00+05:00", "text": "x"}'')::text'), '', 'client log: HR of the own company');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_append_client_log(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'', ''{"at": "2026-01-01T00:00:00+05:00", "text": "x"}'')::text'), 'denied', 'client log: HR of another company is refused');
select is(tests.value_as('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_append_client_log(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'', ''{"at": "2026-01-01T00:00:00+05:00", "text": "x"}'')::text'), 'denied', 'client log: a clinic is refused');

-- app.fact_redeem_card_token / app.fact_match_policy_pinfl: a clinic checking a patient, nobody else
insert into public.card_tokens (token, short_code, insured_id, expires_at) values ('t-redeem', 'EEEE5555', '3bbd3ada-60b7-451a-9ad3-30daa667beb1', (extract(epoch from now()) * 1000)::bigint + 600000);
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_redeem_card_token(''EEEE5555'', null, (extract(epoch from now()) * 1000)::bigint) ->> ''insuredId'''), '3bbd3ada-60b7-451a-9ad3-30daa667beb1', 'card code: the clinic gets only the person id');
update public.card_tokens set used_at = 1 where token = 't-redeem';
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_redeem_card_token(''EEEE5555'', null, (extract(epoch from now()) * 1000)::bigint) ->> ''status'''), 'used', 'card code: a second use is refused');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_redeem_card_token(null, ''no-such-token-0000'', (extract(epoch from now()) * 1000)::bigint) ->> ''status'''), 'stale', 'card code: an unknown code is stale');
select is(tests.value_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select app.fact_redeem_card_token(''EEEE5555'', null, 0)::text'), 'denied', 'card code: MIG staff do not redeem codes');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_redeem_card_token(''EEEE5555'', null, 0)::text'), 'denied', 'card code: the insured person does not redeem codes');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_match_policy_pinfl(''dms-2026-000101'', ''\x8ee61637cd291efd59b3ef776a94a4b504c487d65b5573e7cbbaa41b6f8773b7'')::text'), '3bbd3ada-60b7-451a-9ad3-30daa667beb1', 'policy and PINFL: the clinic gets the person id (any case of the number)');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_match_policy_pinfl(''DMS-2026-000101'', ''\x00'')::text'), null, 'policy and PINFL: a wrong PINFL matches nobody');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_match_policy_pinfl(''DMS-2026-000101'', ''\x00'')::text'), 'denied', 'policy and PINFL: HR is refused');

-- app.fact_visit_patient / app.fact_visit_policy_period: visits the caller sees
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_visit_patient(''8d7907fa-9d87-462c-9054-1e4333dd8978'') ->> ''id'''), '49889f6d-0de4-43ee-ac91-22aaad48b839', 'visit patient: the clinic of the visit, also after it closed');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select (app.fact_visit_patient(''8d7907fa-9d87-462c-9054-1e4333dd8978'') ? ''pinfl'')::text'), 'false', 'visit patient: only the name and the policy');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_visit_patient(''fdf7ee2d-2fed-4163-bb2d-f4779a5607d8'')::text'), 'denied', 'visit patient: not a visit of another clinic');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_visit_policy_period(''8d7907fa-9d87-462c-9054-1e4333dd8978'') ->> ''endDate'''), (select p.end_date::text from public.insured i join public.policies p on p.id = i.policy_id where i.id = '49889f6d-0de4-43ee-ac91-22aaad48b839'), 'visit policy period: the term of the patient’s policy');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_visit_policy_period(''fdf7ee2d-2fed-4163-bb2d-f4779a5607d8'')::text'), 'denied', 'visit policy period: not of another clinic’s visit');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_visit_patient(''8d7907fa-9d87-462c-9054-1e4333dd8978'')::text'), 'denied', 'visit patient: the insured person is refused');

-- app.fact_policy_routing: whoever deals with the policy
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select jsonb_array_length(app.fact_policy_routing(''37c1a764-fb1e-49c1-bccc-71f79d27235f''))'), (select count(*)::text from public.assignments where policy_id = '37c1a764-fb1e-49c1-bccc-71f79d27235f'), 'routing: the insured person of the own policy');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_policy_routing(''7e2e38e1-9a33-49c5-b971-4baf8e291136'')::text'), 'denied', 'routing: not another policy of the insured person');
select is(tests.value_as('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select jsonb_array_length(app.fact_policy_routing(''37c1a764-fb1e-49c1-bccc-71f79d27235f''))'), (select count(*)::text from public.assignments where policy_id = '37c1a764-fb1e-49c1-bccc-71f79d27235f'), 'routing: an assistance company of a policy it served (all companies of it)');
select is(tests.value_as('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select app.fact_policy_routing(''7e2e38e1-9a33-49c5-b971-4baf8e291136'')::text'), 'denied', 'routing: not of a policy the company never served');
select is(tests.value_as('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select bool_and(not (x ? ''setById'') and not (x ? ''setAt''))::text from jsonb_array_elements(app.fact_policy_routing(''37c1a764-fb1e-49c1-bccc-71f79d27235f'')) x'), 'true', 'routing: no author of the assignment');

-- app.fact_file_kind: whether a file exists, never the file
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_file_kind(''43327781-72fd-4acd-b36f-8d53aaf53a6b'')'), 'other', 'file kind: a hidden file answers only its kind');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_file_kind(gen_random_uuid())'), null, 'file kind: a missing file');

-- app.fact_limit_sums / app.fact_coverage_brief: whoever may check the person, sums only
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select (app.fact_limit_sums(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''individual'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'') ? ''used'')::text'), 'true', 'limit sums: the insured person of self');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select (select string_agg(k, '','' order by k) from jsonb_object_keys(app.fact_limit_sums(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''family_shared'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'')) k)'), 'program,reserved,used', 'limit sums: only the program and the sums');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_limit_sums(''24c28bf6-00a2-4562-a372-c88cbe2da8e2'', ''individual'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'')::text'), 'denied', 'limit sums: not of a person of another family');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select (app.fact_limit_sums(''49889f6d-0de4-43ee-ac91-22aaad48b839'', ''individual'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'') ? ''used'')::text'), 'true', 'limit sums: a clinic that had a visit of the person');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_limit_sums(''987935ee-ca40-423a-a5ff-efafef6023af'', ''individual'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'')::text'), 'denied', 'limit sums: a clinic without a visit of the person is refused');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_limit_sums(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''individual'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'')::text'), 'denied', 'limit sums: HR never (no medical data), also of the own company');
select is(tests.value_as('{"sub":"b6a714d4-267a-49cc-b7a6-fb3972b746f1","role":"authenticated","aal":"aal2","app_metadata":{"role":"sales_manager"}}'::jsonb, 'select app.fact_limit_sums(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'', ''individual'', current_date, ''{"medicines":"medicines","doctor_visit":"outpatient","diagnostics":"outpatient","dental":"dental","inpatient":"inpatient"}'', ''{"outpatient":"outpatient","diagnostics_advanced":"outpatient","dental":"dental","medicines":"medicines","inpatient":"inpatient"}'')::text'), 'denied', 'limit sums: a MIG role without cards, claims or coverage is refused');
select is(tests.value_as('{"sub":"63e6a77c-6970-4fc6-8839-87e3f7ed5d36","role":"authenticated","aal":"aal2","app_metadata":{"role":"asst_operator","assistance_id":"a121b4af-f33d-4698-aa49-81543ec9c8af"}}'::jsonb, 'select app.fact_coverage_brief(''987935ee-ca40-423a-a5ff-efafef6023af'')::text'), 'denied', 'coverage brief: an assistance company that never served the policy is refused');
select is(tests.value_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select app.fact_coverage_brief(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'') -> ''policy'' ->> ''number'''), 'DMS-2026-000101', 'coverage brief: the policy of the person');
select is(tests.value_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select (app.fact_coverage_brief(''3bbd3ada-60b7-451a-9ad3-30daa667beb1'') -> ''person'' ? ''fullName'')::text'), 'false', 'coverage brief: no name or identity data');

-- app.fact_taken_slots: times of live appointments, no person
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select jsonb_array_length(app.fact_taken_slots(''d0579ad3-d8ff-44f0-bd72-00a2011c1fc5''))'), (select count(*)::text from public.appointments where clinic_id = 'd0579ad3-d8ff-44f0-bd72-00a2011c1fc5' and status not in ('cancelled', 'declined')), 'taken slots: the insured person sees every taken time of a clinic');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select coalesce(bool_and(jsonb_typeof(x) = ''string''), true)::text from jsonb_array_elements(app.fact_taken_slots(''d0579ad3-d8ff-44f0-bd72-00a2011c1fc5'')) x'), 'true', 'taken slots: only the times');
select is(tests.value_as('{"sub":"d87d459d-1000-4b7d-b5fd-369cf3032aaf","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_registrar","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_taken_slots(''e7c2d8f6-5340-4e44-bd98-8adeacea2251'')::text'), 'denied', 'taken slots: a clinic only of its own');

-- app.fact_client_pipeline: clients.read
select is(tests.value_as('{"sub":"b6a714d4-267a-49cc-b7a6-fb3972b746f1","role":"authenticated","aal":"aal2","app_metadata":{"role":"sales_manager"}}'::jsonb, 'select (app.fact_client_pipeline(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'') ? ''hasHr'')::text'), 'true', 'pipeline: the sales manager of any client');
select is(tests.value_as('{"sub":"da7c7e13-c39a-4a58-9253-779029c7d238","role":"authenticated","aal":"aal2","app_metadata":{"role":"admin"}}'::jsonb, 'select (app.fact_client_pipeline(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'') ->> ''hasPolicy'')'), 'true', 'pipeline: the admin (no deals or contracts) gets the stage');
select is(tests.value_as('{"sub":"89366724-81b8-405d-bf79-63e84207f156","role":"authenticated","aal":"aal2","app_metadata":{"role":"doctor_expert"}}'::jsonb, 'select app.fact_client_pipeline(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')::text'), 'denied', 'pipeline: a role without clients.read is refused');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_client_pipeline(''20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2'')::text'), 'denied', 'pipeline: HR is refused');

-- app.fact_certificate_data: contract readers, HR of the own company, the insured person for the own card
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select jsonb_array_length(app.fact_certificate_data(''37c1a764-fb1e-49c1-bccc-71f79d27235f'', ''3bbd3ada-60b7-451a-9ad3-30daa667beb1'') -> ''rows'')'), (select count(*)::text from public.insured where id = '3bbd3ada-60b7-451a-9ad3-30daa667beb1' and status = 'active' and coalesce(certificate_number, '') <> ''), 'certificates: the insured person of the own card');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_certificate_data(''37c1a764-fb1e-49c1-bccc-71f79d27235f'', null)::text'), 'denied', 'certificates: the insured person not of the whole policy');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_certificate_data(''37c1a764-fb1e-49c1-bccc-71f79d27235f'', ''24c28bf6-00a2-4562-a372-c88cbe2da8e2'')::text'), 'denied', 'certificates: not of a person of another family');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_certificate_data(''970595a0-4361-4472-b871-10bac8839841'', null)::text'), 'denied', 'certificates: HR of another company is refused');
select is(tests.value_as('{"sub":"e6a763ef-810d-4380-9d2d-fea2aff9b2fb","role":"authenticated","aal":"aal2","app_metadata":{"role":"legal"}}'::jsonb, 'select (app.fact_certificate_data(''970595a0-4361-4472-b871-10bac8839841'', null) ? ''rows'')::text'), 'true', 'certificates: a contract reader of MIG');

-- app.fact_mig_signatory / app.fact_deal_number
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select coalesce(app.fact_mig_signatory(''52fe1304-558d-45b3-9a0b-5c670bbfb7ec'') ->> ''fullName'', '''')'), (select coalesce(case when (signatory ->> 'canSign')::boolean then full_name end, '') from public.staff where id = '52fe1304-558d-45b3-9a0b-5c670bbfb7ec'), 'signatory: HR sees the MIG signatory of its contract');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select (app.fact_mig_signatory(''52fe1304-558d-45b3-9a0b-5c670bbfb7ec'') ? ''email'')::text'), 'false', 'signatory: no e-mail or authority');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_mig_signatory(''52fe1304-558d-45b3-9a0b-5c670bbfb7ec'')::text'), 'denied', 'signatory: the insured person is refused');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_deal_number(''75014162-224a-4052-a6fa-fcdf96ffa1ca'')'), 'SD-2026-000047', 'deal number: HR of the own company’s deal');
select is(tests.value_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select app.fact_deal_number(''248399a4-7e67-4fed-ab20-bda6f9ec46d7'')'), 'denied', 'deal number: not of another company’s deal');

-- app.fact_contract_quote: whoever reads the contract
select is(tests.value_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'select (app.fact_contract_quote(''f4b56b88-8faa-412a-9de5-f00b308a95be'', ''643f5139-49cc-432a-a445-824dcd815d1f'') ? ''quote'')::text'), 'true', 'contract quote: the operator (no quotes) reads the summary of a contract');
select is(tests.value_as('{"sub":"59f577ba-4115-4ea2-ba60-f2454cb8ffc1","role":"authenticated","aal":"aal1","app_metadata":{"role":"insured","insured_id":"3bbd3ada-60b7-451a-9ad3-30daa667beb1"}}'::jsonb, 'select app.fact_contract_quote(''f4b56b88-8faa-412a-9de5-f00b308a95be'', null)::text'), 'denied', 'contract quote: the insured person is refused');
select is(tests.value_as('{"sub":"15cb7ec0-e7cd-4367-aad5-e46790f5d3e0","role":"authenticated","aal":"aal2","app_metadata":{"role":"clinic_admin","clinic_id":"d0579ad3-d8ff-44f0-bd72-00a2011c1fc5"}}'::jsonb, 'select app.fact_contract_quote(''f4b56b88-8faa-412a-9de5-f00b308a95be'', null)::text'), 'denied', 'contract quote: a clinic is refused');

-- contracts: HR reads and fills a draft of the own company only while MIG asks for its appendix 2
create temp table sc_contract as select * from public.contracts where id = 'cad0f774-f0ae-4fdc-9555-c4d9ca917a17';
update sc_contract set id = '00000000-0000-4000-8000-000000002101', number = number || '#t', client_id = '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2', status = 'draft';
insert into public.contracts select * from sc_contract;
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select 1 from public.contracts where id = ''00000000-0000-4000-8000-000000002101''')).n, 0, 'contracts: a draft is hidden from HR');
insert into public.tasks (id, action, to_role, subject_type, subject_id, client_id, client_name, title, comment, link, created_by_name, created_at, due_at, due_date, status, subject_label, subject_link, history, created_by_id, contract_id) values ('00000000-0000-4000-8000-000000002102', 'insured_list', 'hr', 'contract', '00000000-0000-4000-8000-000000002101', '20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2', 'C', 'srv.test', '', '/hr', 'T', now(), now() + interval '1 day', current_date + 1, 'open', 'C', '/hr', '[]'::jsonb, 'b6a714d4-267a-49cc-b7a6-fb3972b746f1', '00000000-0000-4000-8000-000000002101');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select 1 from public.contracts where id = ''00000000-0000-4000-8000-000000002101''')).n, 1, 'contracts: HR reads the draft while the request is open');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'update public.contracts set insured_count = 1 where id = ''00000000-0000-4000-8000-000000002101''')).n, 1, 'contracts: HR fills the asked draft');
update public.tasks set status = 'done' where id = '00000000-0000-4000-8000-000000002102';
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'select 1 from public.contracts where id = ''00000000-0000-4000-8000-000000002101''')).n, 0, 'contracts: hidden again once the request is done');
select is((tests.as_user('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'update public.contracts set insured_count = 1 where id = ''00000000-0000-4000-8000-000000002101''')).n, 0, 'contracts: and no longer writable');
select is(tests.count_as('{"sub":"54bc4a41-9856-4a1e-a53b-a0ee976f364e","role":"authenticated","aal":"aal2","app_metadata":{"role":"operator"}}'::jsonb, 'payments'), (select count(*) from public.payments), 'payments: the operator reads the payments of the contract card');
select is(tests.count_as('{"sub":"024b89fe-e0d0-4550-b796-5353f86b3486","role":"authenticated","aal":"aal1","app_metadata":{"role":"hr","company_id":"20c1d1ef-6ac4-48b2-87ea-7e9728d9d5f2"}}'::jsonb, 'payments'), 0::bigint, 'payments: HR reads none');
select is(tests.value_as('{}'::jsonb, 'select app.fact_client_legal_form(''0682c280-96fa-4961-a98b-5a4e1f53e2e1'')'), 'denied', 'no claims: every fact is refused');
select * from finish();
rollback;
