/*
 * The narrow facts of store/facts.ts as SQL functions of schema `app` (docs/PRIVILEGED_AUDIT.md). Every function:
 * - is SECURITY DEFINER with `search_path = ''` (it reads rows the caller's RLS hides);
 * - checks `app.active()` and the permission or the scope itself, and raises 42501 otherwise;
 * - returns only the value the service needs (a count, a code, anonymous figures in storage order);
 * - may be executed by `authenticated` (the API's system repositories compute the same in TypeScript).
 * Its twin in TypeScript (`genericFacts`) must return exactly the same: the conformance test compares them.
 */
import { lit } from './physical';
import { grantExpression } from './rls';
import { TABLES } from '../schema';
import { CLINIC_EVENTS_KEPT } from '../facts';

const HEADER = `-- Narrow facts (docs/PRIVILEGED_AUDIT.md): counts, codes and anonymous figures of rows the caller's RLS hides; side effects in another party's feed.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/facts.ts. Do not edit by hand:
-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.
`;

/** `YYYY-MM-DDTHH:mm:ss+05:00`, as the repositories read a `ts` column. */
export const tsText = (col: string) => `to_char(${col} at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"')`;

/** The row `key = value` of a table is visible to the caller by the table's SELECT policy (evaluated by the definer). */
export function visible(collection: string, keyColumn: string, value: string): string {
  const t = TABLES.find((x) => x.collection === collection);
  if (!t) throw new Error(`No table ${collection}`);
  const e = grantExpression(t.access.select);
  if (!e) return 'false';
  return `exists (select 1 from public.${t.table} v where v.${keyColumn} = ${value} and (${e.replace(/\n\s*/g, ' ')}))`;
}

/** The SELECT policy of a table as a condition on the row alias `a` (evaluated by the definer). */
export function visibleExpr(collection: string, a: string): string {
  const t = TABLES.find((x) => x.collection === collection);
  if (!t) throw new Error(`No table ${collection}`);
  const e = grantExpression(t.access.select);
  if (!e) return 'false';
  return `exists (select 1 from public.${t.table} v where v.${t.key === null ? '_id' : snakeKey(t.key)} = ${a}.${t.key === null ? '_id' : snakeKey(t.key)} and (${e.replace(/\n\s*/g, ' ')}))`;
}
const snakeKey = (k: string) => k.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`);

interface FactFn {
  /** Signature inside schema `app`, e.g. `fact_client_insured_count(p_client uuid)`. */
  sig: string;
  returns: string;
  /** PL/pgSQL condition the caller must meet (besides app.active()). */
  gate: string;
  /** The body after the gate: `return …;` statements. */
  body: string;
  comment: string;
  volatility?: 'stable' | 'volatile';
}

/** An audit entry as the repositories read it (`reason` only when `withReason`). */
const auditJson = (a: string, withReason = true) =>
  `jsonb_strip_nulls(jsonb_build_object('id', ${a}.id, 'at', ${tsText(`${a}."at"`)}, 'actorId', ${a}.actor_id, 'actorName', ${a}.actor_name, 'actorRole', ${a}.actor_role, 'action', ${a}.action, 'targetType', ${a}.target_type, 'targetId', ${a}.target_id, 'targetLabel', ${a}.target_label,${withReason ? ` 'reason', ${a}.reason,` : ''} 'assistanceId', ${a}.assistance_id))`;

/**
 * Who may check a person's coverage and limits: MIG staff who read cards, claims or coverage; the insured person for
 * the persons whose medical data they see (self, children, adults who consented); a clinic that had a visit of the
 * person; an assistance company that served the person's policy. Never HR (it sees no medical data).
 */
const COVERAGE_CHECKER = (p: string) => `(app.is_staff() and (select app.can_any(array['insured.read', 'claims.read', 'ai.coverage.mig']::text[])))
      or (app.role() = 'insured' and ${p} = any(app.my_person_ids()))
      or (app.is_clinic() and exists (select 1 from public.visits v where v.insured_id = ${p} and v.clinic_id = app.clinic_id()))
      or (app.is_assist() and exists (select 1 from public.insured i join public.assignments a on a.policy_id = i.policy_id where i.id = ${p} and a.assistance_id = app.assistance_id()))`;

const CLIENT_READER = (p: string) => `(select app.can('clients.read')) and ${visible('clients', 'id', p)}`;

export const FACT_FUNCTIONS: readonly FactFn[] = [
  {
    sig: 'fact_client_insured_count(p_client uuid)',
    returns: 'integer',
    gate: visible('clients', 'id', 'p_client'),
    body: `return (select count(*)::int from public.insured i where i.client_id = p_client and i.status = 'active');`,
    comment: 'Active insured persons of a client the caller sees (the client card counter).',
  },
  {
    sig: 'fact_client_legal_form(p_client uuid)',
    returns: 'text',
    gate: `app.is_staff() or p_client = app.company_id()`,
    body: `return (select c.legal_form from public.clients c where c.id = p_client);`,
    comment: 'Legal form shown next to a client name (MIG staff; HR — the own company).',
  },
  {
    sig: 'fact_client_claim_figures(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
      'category', c.category, 'serviceDate', c.service_date::text, 'createdAt', ${tsText('c.created_at')},
      'status', c.status, 'amountClaimed', c.amount_claimed, 'amountApproved', c.amount_approved)) order by c._pos), '[]'::jsonb)
    from public.claims c where c.client_id = p_client);`,
    comment: 'Anonymous figures (category, dates, status, amounts) of the claims of a client, for clients.read: loss statistics.',
  },
  {
    sig: 'fact_client_invoice_figures(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(jsonb_build_object('number', i.number, 'amount', i.amount, 'issuedAt', i.issued_at::text) order by i._pos), '[]'::jsonb)
    from public.invoices i where i.client_id = p_client);`,
    comment: 'Number, amount and date of the invoices of a client, for clients.read (the last invoice of the client card).',
  },
  {
    sig: 'fact_policy_brief(p_policy uuid)',
    returns: 'jsonb',
    gate: `(select app.can('clients.read')) and exists (select 1 from public.policies p where p.id = p_policy and ${visible('clients', 'id', 'p.client_id')})`,
    body: `return (select jsonb_build_object('number', p.number, 'startDate', p.start_date::text) from public.policies p where p.id = p_policy);`,
    comment: 'Number and start date of a policy of a client the caller reads (the client card).',
  },
  {
    sig: 'fact_client_history(p_client uuid, p_limit integer)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, ${auditJson('a', false)} as j
      from public.audit_log a
      where a.action <> all(array['reveal_pii', 'open_medical']) and a.target_id = any(
        array[p_client::text]
        || array(select p.id::text from public.policies p where p.client_id = p_client)
        || array(select c.id::text from public.claims c where c.client_id = p_client)
        || array(select k.id::text from public.kp k where k.client_id = p_client))
      order by a._pos limit greatest(p_limit, 0)) e);`,
    comment: 'Audit entries about a client, its policies, claims and offers (no openings of personal or medical data, no reasons), for clients.read.',
  },
  {
    sig: 'fact_company_claim_count(p_client uuid, p_since_ms bigint)',
    returns: 'integer',
    gate: `app.role() = 'hr' and p_client = app.company_id()`,
    body: `return (select count(*)::int from public.claims c join public.insured i on i.id = c.insured_id
      where i.client_id = p_client and i.status = 'active' and c.created_at >= to_timestamp(p_since_ms / 1000.0));`,
    comment: 'Number of claims of the active persons of the own company since a moment (HR statistics, shown k-anonymous): HR never reads claims.',
  },
  {
    sig: 'fact_person_access_log(p_insured uuid)',
    returns: 'jsonb',
    gate: `app.is_staff() and app.role() <> 'accountant' and (select app.can('insured.read')) and ${visible('insured', 'id', 'p_insured')}`,
    body: `return (select coalesce(jsonb_agg(${auditJson('a')} order by a._pos), '[]'::jsonb) from public.audit_log a
      where a.target_id = p_insured::text and a.action in ('reveal_pii', 'open_medical'));`,
    comment: 'Openings of personal and medical data of a person the caller reads (the access log of the card): MIG card readers.',
  },
  {
    sig: 'fact_own_audit_entries(p_actor uuid, p_actions text[], p_limit integer)',
    returns: 'jsonb',
    gate: `app.is_staff() and p_actor = app.uid() and p_actions <@ array['reveal_pii', 'open_medical']`,
    body: `return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, ${auditJson('a')} as j from public.audit_log a
      where a.actor_id = p_actor and a.action = any(p_actions) order by a._pos limit p_limit) e);`,
    comment: 'The caller’s own openings of personal and medical data (the doctor’s desktop): a MIG employee, own entries only.',
  },
  {
    sig: 'fact_advance_deal(p_deal uuid, p_stage text, p_order text[], p_at timestamptz)',
    returns: 'boolean',
    gate: `app.is_staff() or (app.role() = 'hr' and app.client_of_deal(p_deal) = app.company_id())`,
    volatility: 'volatile',
    body: `declare
    v text;
  begin
    select d.stage into v from public.deals d where d.id = p_deal for update;
    if v is null or v = 'lost' then
      return false;
    end if;
    if coalesce(array_position(p_order, p_stage), 0) <= coalesce(array_position(p_order, v), 0) and p_stage <> v then
      return false;
    end if;
    if p_stage <> v then
      update public.deals set stage = p_stage, updated_at = p_at where id = p_deal;
    end if;
    return true;
  end;`,
    comment: 'Moves a deal forward along the pipeline order (never back, never out of lost) after an event of any party: MIG staff, HR of the own company.',
  },
  {
    sig: 'fact_push_clinic_event(p_id uuid, p_clinic uuid, p_at timestamptz, p_text text)',
    returns: 'void',
    gate: `exists (select 1 from public.clinics c where c.id = p_clinic) and (not app.is_clinic() or p_clinic = app.clinic_id()) and length(p_text) <= 2000`,
    volatility: 'volatile',
    body: `insert into public.clinic_events (id, clinic_id, "at", "text", _pos) values (p_id, p_clinic, p_at, p_text, -nextval('app.pos_seq'));
  delete from public.clinic_events where id in (select e.id from public.clinic_events e order by e._pos offset ${CLINIC_EVENTS_KEPT});`,
    comment: 'An event in the feed of a clinic cabinet caused by any party (a booking, a referral, a decision); the newest ${CLINIC_EVENTS_KEPT} are kept. A clinic writes only into its own feed.',
  },
  {
    sig: 'fact_append_client_log(p_client uuid, p_entry jsonb)',
    returns: 'void',
    gate: `(app.is_staff() or (app.role() = 'hr' and p_client = app.company_id())) and jsonb_typeof(p_entry) = 'object' and length(p_entry::text) <= 4000`,
    volatility: 'volatile',
    body: `update public.clients set log = jsonb_build_array(jsonb_build_object('at', p_entry ->> 'at', 'text', p_entry ->> 'text')) || coalesce(log, '[]'::jsonb) where id = p_client;`,
    comment: 'A line at the top of the activity log of a client after an action on a request: MIG staff, HR of the own company (who may not update the client).',
  },  {
    sig: 'fact_redeem_card_token(p_short_code text, p_token text, p_now bigint)',
    returns: 'jsonb',
    gate: `app.is_clinic() and (select app.can('clinic.check_patient'))`,
    volatility: 'volatile',
    body: `declare
    r public.card_tokens;
  begin
    if p_short_code is not null then
      select * into r from public.card_tokens t where t.short_code = p_short_code order by t._pos limit 1 for update;
    else
      select * into r from public.card_tokens t where t.token = p_token order by t._pos limit 1 for update;
    end if;
    if r.token is not null and r.used_at is not null then
      return jsonb_build_object('status', 'used');
    end if;
    if r.token is null or r.expires_at < p_now then
      return jsonb_build_object('status', 'stale');
    end if;
    update public.card_tokens set used_at = p_now where token = r.token;
    return jsonb_build_object('status', 'ok', 'insuredId', r.insured_id);
  end;`,
    comment: 'Redeems a card code shown at the desk once (a clinic checking a patient): only the person id, or used/stale. The clinic never reads card tokens.',
  },
  {
    sig: 'fact_match_policy_pinfl(p_number text, p_pinfl_hmac bytea)',
    returns: 'uuid',
    gate: `app.is_clinic() and (select app.can('clinic.check_patient'))`,
    body: `return (select i.id from public.insured i
      where i.policy_id = (select p.id from public.policies p where upper(p.number) = upper(p_number) order by p._pos limit 1)
        and i.pinfl_hmac = p_pinfl_hmac and i.status = 'active' order by i._pos limit 1);`,
    comment: 'The active person of a policy number and a PINFL (search HMAC) before a visit exists: a clinic checking a patient gets only the id (rate-limited and audited by the API).',
  },
  {
    sig: 'fact_visit_patient(p_visit uuid)',
    returns: 'jsonb',
    gate: visible('visits', 'id', 'p_visit'),
    body: `return (select jsonb_build_object('id', i.id, 'fullName', i.full_name, 'policyId', i.policy_id)
      from public.visits v join public.insured i on i.id = v.insured_id where v.id = p_visit);`,
    comment: 'Name and policy of the patient of a visit the caller sees, also after the visit closed (registry lines, payer routing).',
  },
  {
    sig: 'fact_visit_policy_period(p_visit uuid)',
    returns: 'jsonb',
    gate: visible('visits', 'id', 'p_visit'),
    body: `return (select jsonb_build_object('startDate', p.start_date::text, 'endDate', p.end_date::text)
      from public.visits v join public.insured i on i.id = v.insured_id join public.policies p on p.id = i.policy_id where v.id = p_visit);`,
    comment: 'Term of the policy of the patient of a visit the caller sees (registry line checks of the clinic).',
  },
  {
    sig: 'fact_policy_routing(p_policy uuid)',
    returns: 'jsonb',
    gate: `app.is_staff()
      or (app.role() = 'insured' and p_policy = app.my_policy_id())
      or (app.role() = 'hr' and exists (select 1 from public.policies p where p.id = p_policy and p.client_id = app.company_id()))
      or (app.is_clinic() and exists (select 1 from public.visits v join public.insured i on i.id = v.insured_id where v.clinic_id = app.clinic_id() and i.policy_id = p_policy))
      or (app.is_assist() and exists (select 1 from public.assignments a where a.policy_id = p_policy and a.assistance_id = app.assistance_id()))`,
    body: `return (select coalesce(jsonb_agg(jsonb_build_object('policyId', a.policy_id, 'assistanceId', a.assistance_id, 'from', a."from"::text)
        || case when a."to" is null then '{}'::jsonb else jsonb_build_object('to', a."to"::text) end order by a._pos), '[]'::jsonb)
      from public.assignments a where a.policy_id = p_policy);`,
    comment: 'Which assistance company serves a policy from which date (no author): MIG staff; the insured person and HR of the policy; a clinic that had a patient of it; an assistance company that served it.',
  },
  {
    sig: 'fact_file_kind(p_file uuid)',
    returns: 'text',
    gate: 'true',
    body: `return (select case when f.guarantee_id is not null then 'guarantee' else 'other' end from public.files f where f.id = p_file);`,
    comment: 'Whether a file exists and is a guarantee-letter attachment: the download answers 403 or 404 for a file hidden by RLS exactly as the mock (never the file).',
  },  {
    sig: 'fact_limit_sums(p_insured uuid, p_mode text, p_today date, p_claim_to_limit jsonb, p_limit_of_service jsonb)',
    returns: 'jsonb',
    gate: COVERAGE_CHECKER('p_insured'),
    volatility: 'volatile',
    body: `declare
    i public.insured;
    v_from date;
    v_program text;
    v_pool uuid[];
    v_used jsonb;
    v_reserved jsonb;
  begin
    select * into i from public.insured x where x.id = p_insured;
    if i.id is null then
      return null;
    end if;
    select p.start_date, p.program into v_from, v_program from public.policies p where p.id = i.policy_id;
    if p_mode = 'individual' then
      v_pool := array[i.id];
    else
      select coalesce(array_agg(x.id), '{}') into v_pool from public.insured x
        where x.policy_id = i.policy_id and coalesce(x.principal_id, x.id) = coalesce(i.principal_id, i.id);
    end if;
    -- The lazy clock: an approved letter of the pool past its validity expires.
    update public.guarantees g set status = 'expired'
      where g.insured_id = any(v_pool) and g.status = 'approved' and g.valid_until is not null and g.valid_until < p_today;
    with used as (
      select p_claim_to_limit ->> c.category as cat, coalesce(c.amount_approved, c.amount_claimed)::numeric as amount
        from public.claims c
        where c.insured_id = any(v_pool) and c.status in ('approved', 'to_pay', 'paid') and (v_from is null or c.service_date >= v_from - 7)
      union all
      select m.key, m.value::numeric from public.insured x cross join lateral jsonb_each_text(coalesce(x.migrated_used, '{}'::jsonb)) as m(key, value)
        where x.id = any(v_pool)
      union all
      select p_limit_of_service ->> coalesce(pi.category, 'outpatient'), (l.e ->> 'amount')::numeric
        from public.registries reg
        cross join lateral jsonb_array_elements(coalesce(reg.lines, '[]'::jsonb)) as l(e)
        join public.visits v on v.id::text = l.e ->> 'visitId' and v.insured_id = any(v_pool)
        left join lateral (select it.e ->> 'category' as category from public.price_lists pl cross join lateral jsonb_array_elements(coalesce(pl.items, '[]'::jsonb)) with ordinality as it(e, n)
          where pl.clinic_id = reg.clinic_id and it.e ->> 'code' = l.e ->> 'serviceCode' order by it.n limit 1) pi on true
        where l.e ->> 'status' = 'accepted' and coalesce(l.e ->> 'payer', 'mig') <> 'mig'
          and (v_from is null or (l.e ->> 'serviceDate')::date >= v_from - 7)
          and not exists (select 1 from public.claims c2 where c2.insured_id = v.insured_id and c2.registry_line_id::text = l.e ->> 'id'
            and c2.status in ('approved', 'to_pay', 'paid'))
    )
    select coalesce(jsonb_object_agg(u.cat, u.total), '{}'::jsonb) into v_used from (select cat, sum(amount) as total from used group by cat) u;
    select coalesce(jsonb_object_agg(r.cat, r.total), '{}'::jsonb) into v_reserved from (
      select p_limit_of_service ->> coalesce(pi.category, 'outpatient') as cat, sum(coalesce(g.approved_amount, g.estimated_cost)) as total
        from public.guarantees g
        left join lateral (select it.e ->> 'category' as category from public.price_lists pl cross join lateral jsonb_array_elements(coalesce(pl.items, '[]'::jsonb)) with ordinality as it(e, n)
          where pl.clinic_id = g.clinic_id and it.e ->> 'code' = g.service_code order by it.n limit 1) pi on true
        where g.insured_id = any(v_pool) and g.status = 'approved'
        group by 1) r;
    return jsonb_build_object('program', v_program, 'used', v_used, 'reserved', v_reserved);
  end;`,
    comment: 'Used and reserved sums of the limits of a person by category, and the program (no claims, letters or lines): whoever may check the person. An approved letter of the pool past its validity expires (lazy clock).',
  },
  {
    sig: 'fact_coverage_brief(p_insured uuid)',
    returns: 'jsonb',
    gate: COVERAGE_CHECKER('p_insured'),
    body: `return (select jsonb_build_object(
        'person', jsonb_strip_nulls(jsonb_build_object('id', i.id, 'status', i.status, 'insuredFrom', i.insured_from::text, 'excludedFrom', i.excluded_from::text)),
        'policy', (select jsonb_build_object('id', p.id, 'number', p.number, 'program', p.program, 'startDate', p.start_date::text, 'endDate', p.end_date::text, 'status', p.status)
          from public.policies p where p.id = i.policy_id))
      from public.insured i where i.id = p_insured);`,
    comment: 'Term, program and status of the policy and the person’s own dates (the coverage answer): whoever may check the person.',
  },
  {
    sig: 'fact_taken_slots(p_clinic uuid)',
    returns: 'jsonb',
    gate: `not app.is_clinic() or p_clinic = app.clinic_id()`,
    body: `return (select coalesce(jsonb_agg(${tsText('a.starts_at')} order by a._pos), '[]'::jsonb)
      from public.appointments a where a.clinic_id = p_clinic and a.status not in ('cancelled', 'declined'));`,
    comment: 'Start times of the live appointments of a clinic, whoever booked them (no person): free slots for every signed-in role; a clinic only its own.',
  },  {
    sig: 'fact_client_pipeline(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `declare
    v_deal public.deals;
    v_contract public.contracts;
    v_invoice public.invoices;
    v_out jsonb;
  begin
    v_out := jsonb_build_object(
      'hasPolicy', exists (select 1 from public.clients c where c.id = p_client and c.active_policy_id is not null) or exists (select 1 from public.insured i where i.client_id = p_client),
      'hasHr', exists (select 1 from public.hr_users h where h.company_id = p_client));
    select * into v_deal from public.deals d where d.client_id = p_client and d.stage not in ('lost', 'active') order by d.updated_at desc nulls last, d._pos limit 1;
    if v_deal.id is null then
      select * into v_deal from public.deals d where d.client_id = p_client order by d.updated_at desc nulls last, d._pos limit 1;
    end if;
    if v_deal.id is null then
      return v_out;
    end if;
    v_out := v_out || jsonb_build_object('dealId', v_deal.id, 'dealNumber', v_deal.number, 'stage', v_deal.stage);
    select * into v_contract from public.contracts c where c.deal_id = v_deal.id order by c.version desc, c._pos desc limit 1;
    if v_contract.id is not null then
      v_out := v_out || jsonb_build_object('contractId', v_contract.id, 'contractNumber', v_contract.number, 'contractStatus', v_contract.status);
      select * into v_invoice from public.invoices i where i.contract_id = v_contract.id and i.status is distinct from 'paid' order by i.due_date asc nulls last, i._pos limit 1;
      if v_invoice.id is not null then
        v_out := v_out || jsonb_build_object('invoiceId', v_invoice.id, 'invoiceNumber', v_invoice.number);
      end if;
    end if;
    return v_out;
  end;`,
    comment: 'Where a client is in the sales pipeline (deal number and stage, contract number and status, the first unpaid invoice): clients.read.',
  },
  {
    sig: 'fact_certificate_data(p_policy uuid, p_insured uuid)',
    returns: 'jsonb',
    gate: `(app.is_staff() and (select app.can('contracts.read')))
      or (app.role() = 'hr' and exists (select 1 from public.policies p where p.id = p_policy and p.client_id = app.company_id()))
      or (app.role() = 'insured' and p_policy = app.my_policy_id() and p_insured = any(app.my_card_ids()))`,
    body: `return (select jsonb_build_object(
        'contractNumber', (select c.number from public.contracts c where c.id = p.contract_id),
        'clientName', cl.name,
        'rows', (select coalesce(jsonb_agg(jsonb_build_object('insuredId', i.id, 'fullName', i.full_name, 'certificateNumber', i.certificate_number, 'insuredFrom', i.insured_from::text) order by i._pos), '[]'::jsonb)
          from public.insured i where i.policy_id = p.id and i.status = 'active' and coalesce(i.certificate_number, '') <> '' and (p_insured is null or i.id = p_insured)))
        || case when cl.legal_form is null then '{}'::jsonb else jsonb_build_object('clientLegalForm', cl.legal_form) end
      from public.policies p left join public.clients cl on cl.id = p.client_id where p.id = p_policy);`,
    comment: 'Document data of the certificates of a policy (contract number, client, active persons with a number): MIG contract readers, HR of the own company, the insured person for a card of the own family.',
  },
  {
    sig: 'fact_mig_signatory(p_staff uuid)',
    returns: 'jsonb',
    gate: `app.is_staff() or app.role() = 'hr'`,
    body: `return (select case when coalesce((s.signatory ->> 'canSign')::boolean, false)
        then jsonb_build_object('id', s.id, 'fullName', s.full_name, 'role', s.role, 'basis', s.signatory ->> 'basis') end
      from public.staff s where s.id = p_staff);`,
    comment: 'A MIG signatory as a contract shows it (name, role, basis): MIG staff and HR (the other party of the contract).',
  },
  {
    sig: 'fact_deal_number(p_deal uuid)',
    returns: 'text',
    gate: `app.is_staff() or (app.role() = 'hr' and app.client_of_deal(p_deal) = app.company_id())`,
    body: `return (select d.number from public.deals d where d.id = p_deal);`,
    comment: 'The number of a deal shown on its contract: MIG staff, HR of the own company.',
  },
  {
    sig: 'fact_contract_quote(p_deal uuid, p_quote uuid)',
    returns: 'jsonb',
    gate: `exists (select 1 from public.contracts c where c.deal_id = p_deal and (p_quote is null or c.quote_id = p_quote) and ${visibleExpr('contracts', 'c')})`,
    body: `declare
    q public.quotes;
    v_below boolean := false;
  begin
    if p_quote is not null then
      select * into q from public.quotes x where x.id = p_quote;
      v_below := q.id is not null and q.below_min_exception is not null and q.below_min_exception <> 'null'::jsonb;
    else
      select * into q from public.quotes x where x.deal_id = p_deal order by x._pos desc limit 1;
    end if;
    return jsonb_build_object('quote', case when q.id is null then null else jsonb_build_object('id', q.id, 'premiumEmployee', q.premium_employee,
      'premiumFamily', q.premium_family, 'total', q.total, 'program', q.program) end, 'belowMinException', v_below);
  end;`,
    comment: 'The quote summary (premiums, total, program) of a contract the caller reads — its own quote or the deal’s latest — and whether its own quote allows a group below the minimum.',
  },
];

function factSql(f: FactFn): string {
  const name = f.sig.replace(/\(.*\)/, '');
  const types = f.sig
    .replace(/^.*\(|\)$/g, '')
    .split(',')
    .map((x) => x.trim().split(/\s+/).slice(1).join(' '))
    .filter(Boolean)
    .join(', ');
  return `create or replace function app.${f.sig} returns ${f.returns}
  language plpgsql ${f.volatility ?? 'stable'} security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((${f.gate}), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  ${f.body}
end $$;
comment on function app.${name}(${types}) is ${lit(f.comment)};
revoke execute on function app.${name}(${types}) from public;
grant execute on function app.${name}(${types}) to authenticated, service_role;
`;
}

/** The migration with every fact function. */
export function factsMigration(): string {
  return `${HEADER}
${FACT_FUNCTIONS.map(factSql).join('\n')}`;
}
