/*
 * The narrow facts of store/facts.ts as SQL functions of schema `app` (docs/PRIVILEGED_AUDIT.md). Every function:
 * - is SECURITY DEFINER with `search_path = ''` (it reads rows the caller's RLS hides);
 * - checks `app.active()` and the permission or the scope itself, and raises 42501 otherwise;
 * - returns only the value the service needs (a count, a code, anonymous figures in storage order);
 * - may be executed by `authenticated` (the API's system repositories compute the same in TypeScript).
 * Its twin in TypeScript (`genericFacts`) must return exactly the same: the conformance test compares them.
 */
import { lit } from './physical';
import { grantExpression } from './rls';
import { TABLES } from '../schema';

const HEADER = `-- Narrow facts (docs/PRIVILEGED_AUDIT.md): counts, codes and anonymous figures of rows the caller's RLS hides; side effects in another party's feed.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/facts.ts. Do not edit by hand:
-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.
`;

/** `YYYY-MM-DDTHH:mm:ss+05:00`, as the repositories read a `ts` column. */
export const tsText = (col: string) => `to_char(${col} at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"')`;

/** The row `key = value` of a table is visible to the caller by the table's SELECT policy (evaluated by the definer). */
export function visible(collection: string, keyColumn: string, value: string): string {
  const t = TABLES.find((x) => x.collection === collection);
  if (!t) throw new Error(`No table ${collection}`);
  const e = grantExpression(t.access.select);
  if (!e) return 'false';
  return `exists (select 1 from public.${t.table} v where v.${keyColumn} = ${value} and (${e.replace(/\n\s*/g, ' ')}))`;
}

interface FactFn {
  /** Signature inside schema `app`, e.g. `fact_client_insured_count(p_client uuid)`. */
  sig: string;
  returns: string;
  /** PL/pgSQL condition the caller must meet (besides app.active()). */
  gate: string;
  /** The body after the gate: `return …;` statements. */
  body: string;
  comment: string;
  volatility?: 'stable' | 'volatile';
}

const CLIENT_READER = (p: string) => `(select app.can('clients.read')) and ${visible('clients', 'id', p)}`;

export const FACT_FUNCTIONS: readonly FactFn[] = [
  {
    sig: 'fact_client_insured_count(p_client uuid)',
    returns: 'integer',
    gate: visible('clients', 'id', 'p_client'),
    body: `return (select count(*)::int from public.insured i where i.client_id = p_client and i.status = 'active');`,
    comment: 'Active insured persons of a client the caller sees (the client card counter).',
  },
  {
    sig: 'fact_client_legal_form(p_client uuid)',
    returns: 'text',
    gate: `app.is_staff() or p_client = app.company_id()`,
    body: `return (select c.legal_form from public.clients c where c.id = p_client);`,
    comment: 'Legal form shown next to a client name (MIG staff; HR — the own company).',
  },
  {
    sig: 'fact_client_claim_figures(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
      'category', c.category, 'serviceDate', c.service_date::text, 'createdAt', ${tsText('c.created_at')},
      'status', c.status, 'amountClaimed', c.amount_claimed, 'amountApproved', c.amount_approved)) order by c._pos), '[]'::jsonb)
    from public.claims c where c.client_id = p_client);`,
    comment: 'Anonymous figures (category, dates, status, amounts) of the claims of a client, for clients.read: loss statistics.',
  },
  {
    sig: 'fact_client_invoice_figures(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(jsonb_build_object('number', i.number, 'amount', i.amount, 'issuedAt', i.issued_at::text) order by i._pos), '[]'::jsonb)
    from public.invoices i where i.client_id = p_client);`,
    comment: 'Number, amount and date of the invoices of a client, for clients.read (the last invoice of the client card).',
  },
  {
    sig: 'fact_policy_brief(p_policy uuid)',
    returns: 'jsonb',
    gate: `(select app.can('clients.read')) and exists (select 1 from public.policies p where p.id = p_policy and ${visible('clients', 'id', 'p.client_id')})`,
    body: `return (select jsonb_build_object('number', p.number, 'startDate', p.start_date::text) from public.policies p where p.id = p_policy);`,
    comment: 'Number and start date of a policy of a client the caller reads (the client card).',
  },
  {
    sig: 'fact_client_history(p_client uuid, p_limit integer)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', ${tsText('a."at"')}, 'actorId', a.actor_id, 'actorName', a.actor_name,
        'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label,
        'assistanceId', a.assistance_id)) as j
      from public.audit_log a
      where a.action <> all(array['reveal_pii', 'open_medical']) and a.target_id = any(
        array[p_client::text]
        || array(select p.id::text from public.policies p where p.client_id = p_client)
        || array(select c.id::text from public.claims c where c.client_id = p_client)
        || array(select k.id::text from public.kp k where k.client_id = p_client))
      order by a._pos limit greatest(p_limit, 0)) e);`,
    comment: 'Audit entries about a client, its policies, claims and offers (no openings of personal or medical data, no reasons), for clients.read.',
  },
  {
    sig: 'fact_company_claim_count(p_client uuid, p_since_ms bigint)',
    returns: 'integer',
    gate: `app.role() = 'hr' and p_client = app.company_id()`,
    body: `return (select count(*)::int from public.claims c join public.insured i on i.id = c.insured_id
      where i.client_id = p_client and i.status = 'active' and c.created_at >= to_timestamp(p_since_ms / 1000.0));`,
    comment: 'Number of claims of the active persons of the own company since a moment (HR statistics, shown k-anonymous): HR never reads claims.',
  },
];

function factSql(f: FactFn): string {
  const name = f.sig.replace(/\(.*\)/, '');
  const types = f.sig
    .replace(/^.*\(|\)$/g, '')
    .split(',')
    .map((x) => x.trim().split(/\s+/).slice(1).join(' '))
    .filter(Boolean)
    .join(', ');
  return `create or replace function app.${f.sig} returns ${f.returns}
  language plpgsql ${f.volatility ?? 'stable'} security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((${f.gate}), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  ${f.body}
end $$;
comment on function app.${name}(${types}) is ${lit(f.comment)};
revoke execute on function app.${name}(${types}) from public;
grant execute on function app.${name}(${types}) to authenticated, service_role;
`;
}

/** The migration with every fact function. */
export function factsMigration(): string {
  return `${HEADER}
${FACT_FUNCTIONS.map(factSql).join('\n')}`;
}
