/*
 * The narrow facts of store/facts.ts as SQL functions of schema `app` (docs/PRIVILEGED_AUDIT.md). Every function:
 * - is SECURITY DEFINER with `search_path = ''` (it reads rows the caller's RLS hides);
 * - checks `app.active()` and the permission or the scope itself, and raises 42501 otherwise;
 * - returns only the value the service needs (a count, a code, anonymous figures in storage order);
 * - may be executed by `authenticated` (the API's system repositories compute the same in TypeScript).
 * Its twin in TypeScript (`genericFacts`) must return exactly the same: the conformance test compares them.
 */
import { lit } from './physical';
import { grantExpression } from './rls';
import { TABLES } from '../schema';
import { CLINIC_EVENTS_KEPT } from '../facts';

const HEADER = `-- Narrow facts (docs/PRIVILEGED_AUDIT.md): counts, codes and anonymous figures of rows the caller's RLS hides; side effects in another party's feed.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/facts.ts. Do not edit by hand:
-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.
`;

/** `YYYY-MM-DDTHH:mm:ss+05:00`, as the repositories read a `ts` column. */
export const tsText = (col: string) => `to_char(${col} at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"')`;

/** The row `key = value` of a table is visible to the caller by the table's SELECT policy (evaluated by the definer). */
export function visible(collection: string, keyColumn: string, value: string): string {
  const t = TABLES.find((x) => x.collection === collection);
  if (!t) throw new Error(`No table ${collection}`);
  const e = grantExpression(t.access.select);
  if (!e) return 'false';
  return `exists (select 1 from public.${t.table} v where v.${keyColumn} = ${value} and (${e.replace(/\n\s*/g, ' ')}))`;
}

interface FactFn {
  /** Signature inside schema `app`, e.g. `fact_client_insured_count(p_client uuid)`. */
  sig: string;
  returns: string;
  /** PL/pgSQL condition the caller must meet (besides app.active()). */
  gate: string;
  /** The body after the gate: `return …;` statements. */
  body: string;
  comment: string;
  volatility?: 'stable' | 'volatile';
}

/** An audit entry as the repositories read it (`reason` only when `withReason`). */
const auditJson = (a: string, withReason = true) =>
  `jsonb_strip_nulls(jsonb_build_object('id', ${a}.id, 'at', ${tsText(`${a}."at"`)}, 'actorId', ${a}.actor_id, 'actorName', ${a}.actor_name, 'actorRole', ${a}.actor_role, 'action', ${a}.action, 'targetType', ${a}.target_type, 'targetId', ${a}.target_id, 'targetLabel', ${a}.target_label,${withReason ? ` 'reason', ${a}.reason,` : ''} 'assistanceId', ${a}.assistance_id))`;

const CLIENT_READER = (p: string) => `(select app.can('clients.read')) and ${visible('clients', 'id', p)}`;

export const FACT_FUNCTIONS: readonly FactFn[] = [
  {
    sig: 'fact_client_insured_count(p_client uuid)',
    returns: 'integer',
    gate: visible('clients', 'id', 'p_client'),
    body: `return (select count(*)::int from public.insured i where i.client_id = p_client and i.status = 'active');`,
    comment: 'Active insured persons of a client the caller sees (the client card counter).',
  },
  {
    sig: 'fact_client_legal_form(p_client uuid)',
    returns: 'text',
    gate: `app.is_staff() or p_client = app.company_id()`,
    body: `return (select c.legal_form from public.clients c where c.id = p_client);`,
    comment: 'Legal form shown next to a client name (MIG staff; HR — the own company).',
  },
  {
    sig: 'fact_client_claim_figures(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
      'category', c.category, 'serviceDate', c.service_date::text, 'createdAt', ${tsText('c.created_at')},
      'status', c.status, 'amountClaimed', c.amount_claimed, 'amountApproved', c.amount_approved)) order by c._pos), '[]'::jsonb)
    from public.claims c where c.client_id = p_client);`,
    comment: 'Anonymous figures (category, dates, status, amounts) of the claims of a client, for clients.read: loss statistics.',
  },
  {
    sig: 'fact_client_invoice_figures(p_client uuid)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(jsonb_build_object('number', i.number, 'amount', i.amount, 'issuedAt', i.issued_at::text) order by i._pos), '[]'::jsonb)
    from public.invoices i where i.client_id = p_client);`,
    comment: 'Number, amount and date of the invoices of a client, for clients.read (the last invoice of the client card).',
  },
  {
    sig: 'fact_policy_brief(p_policy uuid)',
    returns: 'jsonb',
    gate: `(select app.can('clients.read')) and exists (select 1 from public.policies p where p.id = p_policy and ${visible('clients', 'id', 'p.client_id')})`,
    body: `return (select jsonb_build_object('number', p.number, 'startDate', p.start_date::text) from public.policies p where p.id = p_policy);`,
    comment: 'Number and start date of a policy of a client the caller reads (the client card).',
  },
  {
    sig: 'fact_client_history(p_client uuid, p_limit integer)',
    returns: 'jsonb',
    gate: CLIENT_READER('p_client'),
    body: `return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, ${auditJson('a', false)} as j
      from public.audit_log a
      where a.action <> all(array['reveal_pii', 'open_medical']) and a.target_id = any(
        array[p_client::text]
        || array(select p.id::text from public.policies p where p.client_id = p_client)
        || array(select c.id::text from public.claims c where c.client_id = p_client)
        || array(select k.id::text from public.kp k where k.client_id = p_client))
      order by a._pos limit greatest(p_limit, 0)) e);`,
    comment: 'Audit entries about a client, its policies, claims and offers (no openings of personal or medical data, no reasons), for clients.read.',
  },
  {
    sig: 'fact_company_claim_count(p_client uuid, p_since_ms bigint)',
    returns: 'integer',
    gate: `app.role() = 'hr' and p_client = app.company_id()`,
    body: `return (select count(*)::int from public.claims c join public.insured i on i.id = c.insured_id
      where i.client_id = p_client and i.status = 'active' and c.created_at >= to_timestamp(p_since_ms / 1000.0));`,
    comment: 'Number of claims of the active persons of the own company since a moment (HR statistics, shown k-anonymous): HR never reads claims.',
  },
  {
    sig: 'fact_person_access_log(p_insured uuid)',
    returns: 'jsonb',
    gate: `app.is_staff() and app.role() <> 'accountant' and (select app.can('insured.read')) and ${visible('insured', 'id', 'p_insured')}`,
    body: `return (select coalesce(jsonb_agg(${auditJson('a')} order by a._pos), '[]'::jsonb) from public.audit_log a
      where a.target_id = p_insured::text and a.action in ('reveal_pii', 'open_medical'));`,
    comment: 'Openings of personal and medical data of a person the caller reads (the access log of the card): MIG card readers.',
  },
  {
    sig: 'fact_own_audit_entries(p_actor uuid, p_actions text[], p_limit integer)',
    returns: 'jsonb',
    gate: `app.is_staff() and p_actor = app.uid() and p_actions <@ array['reveal_pii', 'open_medical']`,
    body: `return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, ${auditJson('a')} as j from public.audit_log a
      where a.actor_id = p_actor and a.action = any(p_actions) order by a._pos limit p_limit) e);`,
    comment: 'The caller’s own openings of personal and medical data (the doctor’s desktop): a MIG employee, own entries only.',
  },
  {
    sig: 'fact_advance_deal(p_deal uuid, p_stage text, p_order text[], p_at timestamptz)',
    returns: 'boolean',
    gate: `app.is_staff() or (app.role() = 'hr' and app.client_of_deal(p_deal) = app.company_id())`,
    volatility: 'volatile',
    body: `declare
    v text;
  begin
    select d.stage into v from public.deals d where d.id = p_deal for update;
    if v is null or v = 'lost' then
      return false;
    end if;
    if coalesce(array_position(p_order, p_stage), 0) <= coalesce(array_position(p_order, v), 0) and p_stage <> v then
      return false;
    end if;
    if p_stage <> v then
      update public.deals set stage = p_stage, updated_at = p_at where id = p_deal;
    end if;
    return true;
  end;`,
    comment: 'Moves a deal forward along the pipeline order (never back, never out of lost) after an event of any party: MIG staff, HR of the own company.',
  },
  {
    sig: 'fact_push_clinic_event(p_id uuid, p_clinic uuid, p_at timestamptz, p_text text)',
    returns: 'void',
    gate: `exists (select 1 from public.clinics c where c.id = p_clinic) and (not app.is_clinic() or p_clinic = app.clinic_id()) and length(p_text) <= 2000`,
    volatility: 'volatile',
    body: `insert into public.clinic_events (id, clinic_id, "at", "text", _pos) values (p_id, p_clinic, p_at, p_text, -nextval('app.pos_seq'));
  delete from public.clinic_events where id in (select e.id from public.clinic_events e order by e._pos offset ${CLINIC_EVENTS_KEPT});`,
    comment: 'An event in the feed of a clinic cabinet caused by any party (a booking, a referral, a decision); the newest ${CLINIC_EVENTS_KEPT} are kept. A clinic writes only into its own feed.',
  },
  {
    sig: 'fact_append_client_log(p_client uuid, p_entry jsonb)',
    returns: 'void',
    gate: `(app.is_staff() or (app.role() = 'hr' and p_client = app.company_id())) and jsonb_typeof(p_entry) = 'object' and length(p_entry::text) <= 4000`,
    volatility: 'volatile',
    body: `update public.clients set log = jsonb_build_array(jsonb_build_object('at', p_entry ->> 'at', 'text', p_entry ->> 'text')) || coalesce(log, '[]'::jsonb) where id = p_client;`,
    comment: 'A line at the top of the activity log of a client after an action on a request: MIG staff, HR of the own company (who may not update the client).',
  },
];

function factSql(f: FactFn): string {
  const name = f.sig.replace(/\(.*\)/, '');
  const types = f.sig
    .replace(/^.*\(|\)$/g, '')
    .split(',')
    .map((x) => x.trim().split(/\s+/).slice(1).join(' '))
    .filter(Boolean)
    .join(', ');
  return `create or replace function app.${f.sig} returns ${f.returns}
  language plpgsql ${f.volatility ?? 'stable'} security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((${f.gate}), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  ${f.body}
end $$;
comment on function app.${name}(${types}) is ${lit(f.comment)};
revoke execute on function app.${name}(${types}) from public;
grant execute on function app.${name}(${types}) to authenticated, service_role;
`;
}

/** The migration with every fact function. */
export function factsMigration(): string {
  return `${HEADER}
${FACT_FUNCTIONS.map(factSql).join('\n')}`;
}
