/*
 * The migration of the list queries (store/query.ts, store/computed.ts, schema.ts LIST_QUERIES): the collations the
 * lists sort text by, the search key and the claim reserve as SQL functions (twins of lib/searchNormalize.ts
 * `searchKey` and services/reserve.ts `currentReserve`: apps/api/src/listQueries.test.ts compares them), generated search-key
 * columns with trigram indexes, and the composite list indexes.
 */
import { qi } from '../columns';
import { LIST_QUERIES, tableOf, type ListIndexKey } from '../schema';
import { fieldMapping, hasSecrets, indexColumn, lit } from './physical';
import { APOSTROPHE_CHARS, CYR } from '../../lib/searchNormalize';

export const LIST_QUERIES_MIGRATION = '20261012000100_list_queries.sql';

const HEADER = `-- List queries (docs/backend/DATABASE.md, section "List queries"): collations, the search key, the claim reserve, generated
-- search-key columns and list indexes.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/listQueries.ts and schema.ts LIST_QUERIES. Do not
-- edit by hand: change the TypeScript source and run \`node scripts/gen-schema.mjs\`.
`;

/** Collations of store/query.ts (`Collation`) in SQL. */
export const COLLATION_SQL = { ru: 'app.ru', legal: 'app.legal_name' } as const;

/** The generated search-key column of a text field. */
export function searchColumn(field: string, column: string): string {
  void field;
  return `${column}_sk`;
}

// lib/searchNormalize.ts CYR: the letters that become several Latin letters, the one-to-one ones, the dropped signs.
const MULTI = Object.entries(CYR).filter(([, to]) => to.length > 1);
const SINGLE = Object.entries(CYR).filter(([, to]) => to.length === 1);
const DROPPED = Object.entries(CYR)
  .filter(([, to]) => to === '')
  .map(([from]) => from)
  .join('');
// JavaScript `\s`.
const WHITESPACE = '[\\t\\n\\v\\f\\r \\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]+';

function searchKeyFunction(): string {
  const multi = MULTI.map(([from, to]) => `  s := replace(s, ${lit(from)}, ${lit(to)});`).join('\n');
  return `create or replace function app.search_key(p_text text) returns text
  language plpgsql immutable strict parallel safe set search_path = ''
as $$
declare
  s text;
begin
  -- normalizeSearch(): lower case (full Unicode mapping, as JavaScript toLowerCase), NFC, Cyrillic into Uzbek Latin,
  -- apostrophes dropped, whitespace runs collapsed, trimmed.
  s := normalize(lower(p_text collate pg_catalog."und-x-icu"), nfc);
${multi}
  s := translate(s, ${lit(SINGLE.map(([from]) => from).join('') + DROPPED)}, ${lit(SINGLE.map(([, to]) => to).join(''))});
  s := translate(s, ${lit(APOSTROPHE_CHARS)}, '');
  s := btrim(regexp_replace(s, ${lit(WHITESPACE)}, ' ', 'g'), ' ');
  -- searchKey(): the loose phonetic folding.
  s := replace(s, 'q', 'k');
  s := replace(s, 'x', 'h');
  s := replace(s, 'kh', 'h');
  s := translate(s, 'oe', 'aa');
  s := replace(s, 'yu', 'u');
  -- Runs of one character become one (JavaScript /(.)\\1+/ over UTF-16 units: characters outside the BMP never repeat).
  return regexp_replace(s, '([^\\U00010000-\\U0010FFFF])\\1+', '\\1', 'g');
end
$$;
comment on function app.search_key(text) is 'lib/searchNormalize.ts searchKey(): the key the list search compares (generated *_sk columns).';`;
}

function claimReserveFunction(): string {
  return `create or replace function app.claim_reserve(p_history jsonb, p_changes jsonb, p_claimed bigint, p_approved bigint) returns numeric
  language plpgsql immutable parallel safe set search_path = ''
as $$
declare
  v numeric := 0;
  nxt numeric;
  h jsonb;
  best_at text;
  best_to numeric := 0;
begin
  -- Events derived from the status history (registration, decision, refusal or payment) …
  for h in select value from jsonb_array_elements(case when jsonb_typeof(p_history) = 'array' then p_history else '[]'::jsonb end) loop
    nxt := null;
    if h ->> 'to' = 'new' and coalesce(h ->> 'from', '') = '' then nxt := p_claimed;
    elsif h ->> 'to' = 'approved' then nxt := coalesce(p_approved, p_claimed);
    elsif h ->> 'to' in ('rejected', 'paid') then nxt := 0;
    end if;
    if nxt is null or nxt = v then continue; end if;
    if best_at is null or (h ->> 'at') collate "C" >= best_at collate "C" then best_at := h ->> 'at'; best_to := nxt; end if;
    v := nxt;
  end loop;
  -- … then the explicit changes; the value is the one of the latest event (the last one of equal times).
  for h in select value from jsonb_array_elements(case when jsonb_typeof(p_changes) = 'array' then p_changes else '[]'::jsonb end) loop
    if best_at is null or (h ->> 'at') collate "C" >= best_at collate "C" then best_at := h ->> 'at'; best_to := (h ->> 'to')::numeric; end if;
  end loop;
  return best_to;
end
$$;
comment on function app.claim_reserve(jsonb, jsonb, bigint, bigint) is 'services/reserve.ts currentReserve(): the current reserve of a claim (the claims list sorts by it).';`;
}

/** SQL of one list index key. */
function indexKey(collection: string, key: ListIndexKey): string {
  const [name = '', collate] = key.split('@');
  const col = qi(indexColumn(tableOf(collection), name));
  if (!collate) return col;
  const c = COLLATION_SQL[collate as keyof typeof COLLATION_SQL];
  if (!c) throw new Error(`Unknown collation ${collate} in a list index of ${collection}`);
  return `${col} collate ${c}`;
}

function indexName(table: string, keys: readonly ListIndexKey[], collection: string): string {
  const parts = keys.map((k) => {
    const [name = '', collate] = k.split('@');
    return indexColumn(tableOf(collection), name) + (collate ? `_${collate}` : '');
  });
  const name = `${table}_${parts.join('_')}_list_idx`;
  if (name.length > 63) throw new Error(`Index name too long: ${name}`);
  return name;
}

export function listQueriesMigration(): string {
  const out = [HEADER];
  out.push(`-- Text order of the lists (store/query.ts Collation): ICU, non-deterministic (strings ICU calls equal are a tie, broken by _pos).
create collation if not exists app.ru (provider = icu, locale = 'ru', deterministic = false);
comment on collation app.ru is 'localeCompare(…, ''ru''): text sort keys of the lists.';
create collation if not exists app.legal_name (provider = icu, locale = 'en-u-ks-level1-ka-shifted', deterministic = false);
comment on collation app.legal_name is 'config/legalForms.ts legalNameCollator: names of legal entities (case, quotes, punctuation ignored).';
`);
  out.push(searchKeyFunction());
  out.push(claimReserveFunction());
  out.push('grant execute on function app.search_key(text), app.claim_reserve(jsonb, jsonb, bigint, bigint) to authenticated, service_role;\n');
  for (const [collection, spec] of Object.entries(LIST_QUERIES)) {
    const t = tableOf(collection);
    const lines: string[] = [`-- ${collection}`];
    for (const field of spec.search ?? []) {
      const c = t.columns[field];
      if (!c || (c.kind !== 'text' && c.kind !== 'enum') || c.pii || c.card) throw new Error(`Search key on a field that is not plain text: ${collection}.${field}`);
      const col = fieldMapping(field, c).column!;
      const sk = searchColumn(field, col);
      lines.push(`alter table public.${t.table} add column ${qi(sk)} text generated always as (app.search_key(${qi(col)})) stored;`);
      lines.push(`create index ${t.table}_${sk}_trgm_idx on public.${t.table} using gin (${qi(sk)} extensions.gin_trgm_ops);`);
      if (hasSecrets(t)) lines.push(`grant select (${qi(sk)}) on public.${t.table} to authenticated;`);
    }
    for (const keys of spec.indexes ?? []) {
      lines.push(`create index ${indexName(t.table, keys, collection)} on public.${t.table} (${[...keys.map((k) => indexKey(collection, k)), '_pos'].join(', ')});`);
    }
    out.push(`${lines.join('\n')}\n`);
  }
  return out.join('\n');
}
