/*
 * Migration of stage 1.5 (background jobs do their actions): the marks that make every job action happen once
 * (`app.job_marks`, repo `jobMarks`), the cleanup extended to the test SMS codes and old marks, and the job catalog
 * brought up to services/jobs.ts. Generated like the others (scripts/gen-schema.mjs).
 */
import { JOBS } from '../../services/jobs';
import { cleanupFunction } from './cleanup';
import { JOBS_STEP3 } from './jobsStep3';
import { AUTH_CLEANUP_STATEMENTS } from './migrationsAuth';
import { lit } from './physical';
import { LATER_ENUM_VALUES, tableOf } from '../schema';
import { snake } from '../columns';

export const JOB_ACTIONS_MIGRATION = '20261013000100_job_actions.sql';

const HEADER = (what: string) =>
  `-- ${what}\n-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/migrationsJobs.ts. Do not edit by hand:\n-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.\n`;

/** How long a job mark is kept: longer than any period a job looks back on (a policy year and a margin). */
export const JOB_MARK_KEEP_DAYS = 400;

/** The cleanup of this migration: the list of part 2 plus the test SMS codes (five minutes) and old job marks. */
export const JOBS_CLEANUP_STATEMENTS: readonly string[] = [
  ...AUTH_CLEANUP_STATEMENTS,
  `delete from app.test_phone_codes where "at" < now() - interval '5 minutes'; get diagnostics n = row_count; v := v || jsonb_build_object('test_phone_codes', n);`,
  `delete from app.job_marks where "at" < now() - interval '${JOB_MARK_KEEP_DAYS} days'; get diagnostics n = row_count; v := v || jsonb_build_object('job_marks', n);`,
];

const command = (j: (typeof JOBS)[number]) => (j.runner === 'db' ? j.sql! : j.service!);

/** `update` statements bringing `app.job_catalog` (registered by step 3) to the current job list. */
function catalogUpdates(): string[] {
  const out: string[] = [];
  for (const j of JOBS) {
    const was = JOBS_STEP3.find((x) => x.name === j.name);
    // A new job or a new schedule needs its own pg_cron registration: not part of this migration.
    if (!was || was.cron !== j.cron || was.runner !== j.runner)
      throw new Error(`Job ${j.name}: a new job or schedule needs a new migration`);
    if (command(was) === command(j) && was.description === j.description) continue;
    out.push(
      `update app.job_catalog set command = ${lit(command(j))}, description = ${lit(j.description)} where name = ${lit(j.name)};`,
    );
  }
  return out;
}

/** The CHECK of an enum column widened to the values of LATER_ENUM_VALUES added by `migration`. */
export function enumWidening(migration: string): string[] {
  return LATER_ENUM_VALUES.filter((x) => x.migration === migration).map((x) => {
    const t = tableOf(x.collection);
    const col = t.columns[x.field];
    if (!col || col.kind !== 'enum' || !col.values)
      throw new Error(`${x.collection}.${x.field} is not an enum`);
    const c = snake(x.field);
    const name = `${t.table}_${c}_check`;
    return `alter table public.${t.table} drop constraint ${name};\nalter table public.${t.table} add constraint ${name} check (${c} in (${col.values.map(lit).join(', ')}));`;
  });
}

export function jobActionsMigration(): string {
  return `${HEADER('Background jobs do their actions once (BACKEND_SPEC §10): marks of what a job did per subject and occurrence, the cleanup of test SMS codes and old marks, the job catalog of services/jobs.ts.')}
-- What a job already did: one row per (job, subject, occurrence) — a reminder of one SLA breach, the renewal deal of
-- one policy, the request about one child's age limit. The insert commits with the action (one transaction of the
-- worker): a run that fails leaves no mark, a second run finds the mark and does nothing.
create table app.job_marks (
  job text not null check (length(job) between 1 and 64),
  subject text not null check (length(subject) between 1 and 200),
  occurrence text not null check (length(occurrence) between 1 and 200),
  "at" timestamptz not null default now(),
  primary key (job, subject, occurrence)
);
create index job_marks_at_idx on app.job_marks ("at");
comment on table app.job_marks is 'Actions of background jobs done once per subject and occurrence (repo jobMarks). System only: the worker.';
alter table app.job_marks enable row level security;
revoke all on app.job_marks from public, anon, authenticated;
grant select, insert, delete on app.job_marks to service_role;

${cleanupFunction(JOBS_CLEANUP_STATEMENTS)}
revoke execute on function app.job_cleanup_expired() from public, authenticated;

-- Audit entries of the job's lifecycle transitions (and of the same transitions on read).
${enumWidening(JOB_ACTIONS_MIGRATION).join('\n')}

-- The catalog follows services/jobs.ts (the schedules are unchanged).
${catalogUpdates().join('\n')}
`;
}
