/*
 * SQL migrations generated from the declarative schema (schema.ts), the permissions matrix and the job
 * list. `scripts/gen-schema.mjs` writes them to `supabase/migrations/`; the committed files are the
 * source of truth for the database and a test fails when they differ from this output.
 */
import { PERMISSIONS } from '../../auth/permissions';
import { JOBS } from '../../services/jobs';
import { qi, snake } from '../columns';
import { REVEAL, SEQUENCES, TABLES, sequenceName, type TableSpec } from '../schema';
import { META_COLUMNS, LOG_ID, hasSecrets, indexColumn, keyColumn, lit, physicalColumns, readableColumns } from './physical';
import { ALL_ROLES, ASSIST_ROLES, CLINIC_ROLES, OPS, STAFF_ROLES, cached, grantExpression } from './rls';

export interface SqlFile {
  name: string;
  sql: string;
}

const HEADER = (what: string) =>
  `-- ${what}\n-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/schema.ts and friends. Do not edit by hand:\n-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.\n`;

const roleList = (roles: readonly string[]) => `array[${roles.map(lit).join(', ')}]`;

// ------------------------------------------------------------------------------------------------
// 1. app core: claims of the request, permissions matrix, storage order
// ------------------------------------------------------------------------------------------------
function appCore(): string {
  const fn = (name: string, returns: string, body: string, comment: string) =>
    `create or replace function app.${name} returns ${returns}\n  language sql stable security definer set search_path = ''\nas $$ ${body} $$;\ncomment on function app.${name} is ${lit(comment)};\n`;
  const meta = (key: string) => `select nullif(app.claims() -> 'app_metadata' ->> '${key}', '')`;
  const perms: string[] = [];
  for (const [action, row] of Object.entries(PERMISSIONS)) {
    for (const role of ALL_ROLES) perms.push(`  (${lit(action)}, ${lit(role)}, ${lit(JSON.stringify((row as Record<string, unknown>)[role]))}::jsonb)`);
  }
  return `${HEADER('Schema `app`: request claims, the permissions matrix, storage order (BACKEND_SPEC §6).')}
create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create schema if not exists app;
revoke all on schema app from public;
grant usage on schema app to authenticated, service_role;
alter default privileges in schema app revoke execute on functions from public;

-- Claims of the current request: the API sets them per transaction with
--   set local role authenticated; select set_config('request.jwt.claims', '<json>', true);
-- Roles and bindings come only from app_metadata (set by the API with the service role).
${fn('claims()', 'jsonb', "select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb)", 'Claims of the current request (request.jwt.claims).')}
${fn('uid()', 'uuid', "select nullif(app.claims() ->> 'sub', '')::uuid", 'Id of the signed-in user (JWT sub).')}
${fn('role()', 'text', meta('role'), 'Role of the user (app_metadata.role).')}
${fn('company_id()', 'uuid', `${meta('company_id')}::uuid`, 'Client company of an HR user.')}
${fn('clinic_id()', 'uuid', `${meta('clinic_id')}::uuid`, 'Clinic of a clinic user.')}
${fn('assistance_id()', 'uuid', `${meta('assistance_id')}::uuid`, 'Assistance company of its user.')}
${fn('insured_id()', 'uuid', `${meta('insured_id')}::uuid`, 'Insured person of the app user.')}
${fn('aal()', 'text', "select coalesce(nullif(app.claims() ->> 'aal', ''), 'aal1')", 'Authenticator assurance level of the session (aal2 after TOTP).')}
${fn('is_staff()', 'boolean', `select coalesce(app.role() = any(${roleList(STAFF_ROLES)}), false)`, 'The user is a MIG employee.')}
${fn('is_clinic()', 'boolean', `select coalesce(app.role() = any(${roleList(CLINIC_ROLES)}), false)`, 'The user works for a clinic.')}
${fn('is_assist()', 'boolean', `select coalesce(app.role() = any(${roleList(ASSIST_ROLES)}), false)`, 'The user works for an assistance company.')}
${fn('needs_aal2()', 'boolean', 'select app.is_staff() or app.is_clinic() or app.is_assist()', 'MIG staff, clinics and assistance companies see data only after the second factor.')}
${fn('active()', 'boolean', "select app.uid() is not null and app.role() is not null and (not app.needs_aal2() or app.aal() = 'aal2')", 'A signed-in user with a role (and aal2 where required): every policy starts with it.')}
create or replace function app.tz() returns text language sql immutable set search_path = '' as $$ select 'Asia/Tashkent'::text $$;
comment on function app.tz() is 'Time zone of business dates.';

-- The permissions matrix (packages/domain/src/auth/permissions.ts): one row per action and role.
create table app.permissions (
  action text not null,
  role text not null,
  rule jsonb not null,
  primary key (action, role)
);
comment on table app.permissions is 'Generated from PERMISSIONS: rule is true/false or a scoped rule (own, masked, via_visit, …).';
insert into app.permissions (action, role, rule) values
${perms.join(',\n')};
revoke all on app.permissions from public;
grant select on app.permissions to authenticated, service_role;

${fn('rule(action text)', 'jsonb', 'select p.rule from app.permissions p where p.action = $1 and p.role = app.role()', 'Rule of the matrix for the current role.')}
${fn('can(action text)', 'boolean', "select coalesce((select p.rule <> 'false'::jsonb from app.permissions p where p.action = $1 and p.role = app.role()), false)", 'The current role may do the action at all (its rule is not false); scopes are row predicates of the policies.')}
${fn('can_any(actions text[])', 'boolean', "select exists (select 1 from app.permissions p where p.action = any($1) and p.role = app.role() and p.rule <> 'false'::jsonb)", 'app.can() of any of the actions.')}

-- Storage order of every table: appended rows get increasing positions, rows inserted «at start»
-- (newest-first lists) get -nextval(), i.e. decreasing negative positions. Lists order by _pos.
create sequence app.pos_seq;
grant usage on sequence app.pos_seq to authenticated, service_role;

-- Service columns: _created_at/_updated_at are kept by the database, _created_by is the signed-in user.
create or replace function app.stamp() returns trigger
  language plpgsql security definer set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new._created_at := now();
    new._updated_at := now();
    if app.uid() is not null then
      new._created_by := app.uid();
    end if;
  else
    new._created_at := old._created_at;
    new._created_by := old._created_by;
    new._updated_at := now();
  end if;
  return new;
end $$;

revoke execute on all functions in schema app from public;
grant execute on all functions in schema app to authenticated, service_role;
`;
}

// ------------------------------------------------------------------------------------------------
// 2. tables
// ------------------------------------------------------------------------------------------------
function tableDdl(t: TableSpec): string {
  const cols = physicalColumns(t);
  const lines: string[] = [];
  if (t.key === null) lines.push(`${LOG_ID} uuid primary key default gen_random_uuid()`);
  const key = t.key === null ? null : snake(t.key);
  for (const c of cols) {
    let l = `${qi(c.name)} ${c.sqlType}`;
    if (c.name === key) l += ' primary key';
    else if (c.notNull) l += ' not null';
    if (c.unique) l += ' unique';
    if (c.check) l += ` check (${c.check})`;
    lines.push(l);
  }
  lines.push(`_pos bigint not null default nextval('app.pos_seq')`);
  lines.push(`_created_at timestamptz not null default now()`);
  lines.push(`_updated_at timestamptz not null default now()`);
  lines.push(`_created_by uuid default app.uid()`);
  const out = [`create table public.${t.table} (\n  ${lines.join(',\n  ')}\n);`];
  out.push(`comment on table public.${t.table} is ${lit(`Collection ${t.collection} (${t.kind}).`)};`);
  out.push(`create trigger ${t.table}_stamp before insert or update on public.${t.table} for each row execute function app.stamp();`);
  out.push(`create index ${t.table}__pos_idx on public.${t.table} (_pos);`);
  const seen = new Set<string>();
  for (const ix of t.indexes) {
    if (typeof ix === 'object' && 'trgm' in ix) {
      const c = indexColumn(t, ix.trgm);
      out.push(`create index ${t.table}_${c}_trgm_idx on public.${t.table} using gin (${qi(c)} extensions.gin_trgm_ops);`);
      continue;
    }
    const fields = typeof ix === 'string' ? [ix] : 'unique' in ix ? ix.unique : (ix as readonly string[]);
    const cs = fields.map((f) => indexColumn(t, f));
    const name = `${t.table}_${cs.join('_')}_idx`;
    if (seen.has(name)) throw new Error(`Duplicate index ${name}`);
    seen.add(name);
    const unique = typeof ix === 'object' && 'unique' in ix ? 'unique ' : '';
    out.push(`create ${unique}index ${name} on public.${t.table} (${cs.map(qi).join(', ')});`);
  }
  return out.join('\n');
}

function foreignKeys(t: TableSpec): string[] {
  return physicalColumns(t)
    .filter((c) => c.references)
    .map((c) => `alter table public.${t.table} add constraint ${t.table}_${c.name}_fkey foreign key (${qi(c.name)}) references ${c.references} deferrable initially deferred;`);
}

function schema(): string {
  const parts = [HEADER('Tables of every collection (BACKEND_SPEC §5): keys, NOT NULL, CHECK for enums, deferrable foreign keys, indexes.')];
  for (const t of TABLES) parts.push(tableDdl(t));
  parts.push(`-- Foreign keys (deferrable: rows of one change may arrive in any order within a transaction).\n${TABLES.flatMap(foreignKeys).join('\n')}`);
  parts.push('-- Document number sequences (repo `seq`): next() = nextval().');
  for (const [name, coll] of Object.entries(SEQUENCES)) parts.push(`create sequence public.${sequenceName(name as keyof typeof SEQUENCES)}; -- ${coll}`);
  parts.push(`-- Singletons hold one row.\nalter table public.ai_settings add constraint ai_settings_one_row check (id = 1);\nalter table public.integrations_seed add constraint integrations_seed_one_row check (id = 1);`);
  return parts.join('\n\n') + '\n';
}

function insuredView(): string {
  const ins = TABLES.find((t) => t.collection === 'insured')!;
  const listed = readableColumns(ins).filter((c) => !['birth_date', 'email'].includes(c));
  return `-- Lists of insured persons: no ciphertexts, the birth date and email masked (security_invoker: RLS of the caller applies).
create view public.insured_masked with (security_invoker = true) as
  select ${listed.map(qi).join(', ')},
    '••.••.' || to_char(birth_date, 'YYYY') as birth_date_masked,
    app.mask_email(email) as email_masked
  from public.insured;
comment on view public.insured_masked is 'Masked list view of insured persons (BACKEND_SPEC §6): the API uses it for lists.';`;
}

// ------------------------------------------------------------------------------------------------
// 3. scope helpers (they read tables: SECURITY DEFINER, no RLS recursion) and reveal
// ------------------------------------------------------------------------------------------------
function scopes(): string {
  const def = (sig: string, returns: string, body: string, comment: string, volatility = 'stable') =>
    `create or replace function app.${sig} returns ${returns}\n  language sql ${volatility} security definer set search_path = ''\nas $$\n  ${body}\n$$;\ncomment on function app.${sig.replace(/\(.*\)/, '')} is ${lit(comment)};\n`;
  const reveal: string[] = [];
  for (const t of TABLES) {
    const r = REVEAL[t.collection];
    const fields = Object.entries(t.columns).filter(([, c]) => c.pii === 'encrypt+hmac');
    if (!fields.length) continue;
    if (!r) throw new Error(`No REVEAL rule for ${t.collection}`);
    const visible = grantExpression(t.access.select) ?? 'false';
    const allowed = `(${cached(r.self)}) or ((select app.can_any(array[${r.actions.map(lit).join(', ')}]::text[])) and ${visible})`;
    for (const [f] of fields) {
      const col = snake(f);
      reveal.push(`  if p_table = ${lit(t.table)} and p_field = ${lit(col)} then
    select r.${col}_enc, r.${col}_key_ver into v_enc, v_ver from public.${t.table} r
      where r.${keyColumn(t)}::text = p_id and (${allowed.replace(/\n\s*/g, ' ')});
  end if;`);
    }
  }
  return `${HEADER('Scope helpers of the RLS policies (BACKEND_SPEC §6): «own» rows of HR, the insured, clinics and assistance companies.')}
${def('my_policy_id()', 'uuid', 'select i.policy_id from public.insured i where i.id = app.insured_id()', 'Policy of the signed-in insured person.')}
${def('my_client_id()', 'uuid', 'select i.client_id from public.insured i where i.id = app.insured_id()', 'Client company of the signed-in insured person.')}
${def(
  'my_family_ids()',
  'uuid[]',
  `select coalesce(array_agg(distinct x), '{}') from (
    select app.insured_id() as x
    union all select i.id from public.insured i where i.principal_id = app.insured_id()
    union all select i.principal_id from public.insured i where i.id = app.insured_id() and i.principal_id is not null
  ) s where x is not null`,
  'The insured person, the family under them and their employee: names of the family screen.',
)}
${def(
  'my_person_ids()',
  'uuid[]',
  `select coalesce(array_agg(distinct x), '{}') from (
    select app.insured_id() as x
    union all select i.id from public.insured i where i.principal_id = app.insured_id() and i.relation = 'child'
    union all select c.owner_id from public.family_consents c
      join public.insured o on o.id = c.owner_id
      where c.viewer_id = app.insured_id() and c.revoked_at is null and o.principal_id = app.insured_id()
  ) s where x is not null`,
  'Persons whose claims and appointments the insured person sees: self, children, adults of the family with consent (FAMILY_SPEC).',
)}
${def(
  'clinic_patient_ids()',
  'uuid[]',
  "select coalesce(array_agg(distinct v.insured_id), '{}') from public.visits v where v.clinic_id = app.clinic_id() and v.expires_at > now()",
  'Patients of the clinic with an open visit (CLINIC_SPEC: access only through a visit).',
)}
${def(
  'assist_covers(p_policy uuid, p_day date)',
  'boolean',
  `select exists (select 1 from public.assignments a
    where a.policy_id = p_policy and a.assistance_id = app.assistance_id()
      and a."from" <= p_day and (a."to" is null or p_day <= a."to"))`,
  'The policy is assigned to the user’s assistance company on the date (ASSISTANCE_SPEC §3).',
)}
${def(
  'assist_covers_insured(p_insured uuid, p_day date)',
  'boolean',
  'select app.assist_covers((select i.policy_id from public.insured i where i.id = p_insured), p_day)',
  'The person’s policy is assigned to the user’s assistance company on the date.',
)}
${def('client_of_contract(p_contract uuid)', 'uuid', 'select c.client_id from public.contracts c where c.id = p_contract', 'Client of a contract (HR scope of appendices, change requests, endorsements).')}
${def(
  'registry_has_payer(p_lines jsonb, p_payer uuid)',
  'boolean',
  "select p_payer is not null and exists (select 1 from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb)) l where l ->> 'payer' = p_payer::text)",
  'A registry has lines paid by the assistance company.',
  'immutable',
)}
${def(
  'mask_email(p_email text)',
  'text',
  "select case when p_email is null or p_email = '' then p_email else left(split_part(p_email, '@', 1), 1) || '•••@' || split_part(p_email, '@', 2) end",
  'a•••@company.uz (the same mask as packages/domain/src/lib/mask.ts).',
  'immutable',
)}
-- The full value of PINFL or phone (ciphertext and key version; the API decrypts) for a role allowed to see
-- it, written to the audit log. The only way for \`authenticated\` to read *_enc of identity data.
create or replace function app.reveal(p_table text, p_id text, p_field text, p_reason text, p_actor_name text default null)
  returns table (enc bytea, key_ver smallint)
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_enc bytea;
  v_ver smallint;
begin
  if not app.active() then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  if coalesce(btrim(p_reason), '') = '' then
    raise exception 'a reason is required' using errcode = '22023';
  end if;
${reveal.join('\n')}
  if v_enc is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;
  perform app.audit('reveal_pii', 'insured', p_id, null, p_field || ': ' || p_reason, app.assistance_id(), p_actor_name);
  return query select v_enc, v_ver;
end $$;
comment on function app.reveal(text, text, text, text, text) is 'Ciphertext of an identity field for an allowed role, audited (BACKEND_SPEC §5).';

${insuredView()}

revoke execute on all functions in schema app from public;
grant execute on all functions in schema app to authenticated, service_role;
`;
}

// ------------------------------------------------------------------------------------------------
// 4. RLS and privileges
// ------------------------------------------------------------------------------------------------
const PRIV: Record<(typeof OPS)[number], string> = { select: 'select', insert: 'insert', update: 'update', delete: 'delete' };

function rls(): string {
  const parts = [
    HEADER('Row level security on every table of `public` (BACKEND_SPEC §6), generated from the access rules of schema.ts and the permissions matrix.'),
    `-- Nobody but the API reaches the database; the anon role gets nothing.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;`,
  ];
  for (const t of TABLES) {
    const out = [`-- ${t.table}: ${t.access.note}`, `alter table public.${t.table} enable row level security;`];
    const privs: string[] = [];
    for (const op of OPS) {
      const e = grantExpression(t.access[op]);
      if (e === null) continue;
      privs.push(PRIV[op]);
      const name = `${t.table}_${op}`;
      if (op === 'select' || op === 'delete') out.push(`create policy ${name} on public.${t.table} for ${op} to authenticated\n  using (${e});`);
      else if (op === 'insert') out.push(`create policy ${name} on public.${t.table} for insert to authenticated\n  with check (${e});`);
      else out.push(`create policy ${name} on public.${t.table} for update to authenticated\n  using (${e})\n  with check (${e});`);
    }
    if (privs.length) {
      const nonSelect = privs.filter((p) => p !== 'select');
      if (privs.includes('select')) {
        if (hasSecrets(t)) out.push(`grant select (${readableColumns(t).map(qi).join(', ')}) on public.${t.table} to authenticated;`);
        else nonSelect.unshift('select');
      }
      if (nonSelect.length) out.push(`grant ${nonSelect.join(', ')} on public.${t.table} to authenticated;`);
    }
    parts.push(out.join('\n'));
  }
  parts.push(`grant select on public.insured_masked to authenticated;
grant usage on all sequences in schema public to authenticated;`);
  return parts.join('\n\n') + '\n';
}

// ------------------------------------------------------------------------------------------------
// 5. audit log: append-only with a hash chain (BACKEND_SPEC §9)
// ------------------------------------------------------------------------------------------------
function audit(): string {
  return `${HEADER('Audit log: append-only, written only through app.audit(), hash chain and its verification (BACKEND_SPEC §9).')}
alter table public.audit_log
  add column chain_seq bigint,
  add column prev_hash bytea,
  add column hash bytea;
create unique index audit_log_chain_seq_idx on public.audit_log (chain_seq);
comment on column public.audit_log.hash is 'sha256(hex(prev_hash) | canonical entry): the chain of app.verify_audit_chain().';

-- Canonical text of an entry (the hashed fields; NULL is an empty string).
create or replace function app.audit_canonical(e public.audit_log) returns text
  language sql immutable set search_path = ''
as $$
  select concat_ws('|', e.id::text, to_char(e."at" at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'), e.actor_id::text,
    e.actor_name, e.actor_role, e.action, e.target_type, coalesce(e.target_id, ''), coalesce(e.target_label, ''),
    coalesce(e.reason, ''), coalesce(e.assistance_id::text, ''))
$$;

-- Links every new entry to the previous one. Entries are serialized by an advisory lock; the API works in
-- READ COMMITTED, so the statement after the lock sees the last committed entry.
create or replace function app.audit_chain() returns trigger
  language plpgsql security definer set search_path = ''
as $$
declare
  v_prev public.audit_log;
begin
  perform pg_advisory_xact_lock(hashtext('app.audit_chain'));
  select * into v_prev from public.audit_log order by chain_seq desc limit 1;
  new.chain_seq := coalesce(v_prev.chain_seq, 0) + 1;
  new.prev_hash := v_prev.hash;
  new.hash := extensions.digest(coalesce(encode(v_prev.hash, 'hex'), '') || '|' || app.audit_canonical(new), 'sha256');
  return new;
end $$;
create trigger audit_log_chain before insert on public.audit_log for each row execute function app.audit_chain();

-- Append-only, also for the table owner and the service role: no UPDATE, DELETE or TRUNCATE.
create or replace function app.audit_immutable() returns trigger
  language plpgsql set search_path = ''
as $$
begin
  raise exception 'audit_log is append-only' using errcode = '42501';
end $$;
create trigger audit_log_no_update before update or delete on public.audit_log for each row execute function app.audit_immutable();
create trigger audit_log_no_truncate before truncate on public.audit_log for each statement execute function app.audit_immutable();
revoke insert, update, delete, truncate on public.audit_log from authenticated, anon, service_role;

-- The only way to write an entry. For a signed-in user the actor is taken from the claims (cannot be forged);
-- the service role (system jobs, sign-in events) passes the actor explicitly.
create or replace function app.audit(
  p_action text,
  p_target_type text,
  p_target_id text default null,
  p_target_label text default null,
  p_reason text default null,
  p_assistance_id uuid default null,
  p_actor_name text default null,
  p_actor_id uuid default null,
  p_actor_role text default null,
  p_at timestamptz default now(),
  p_id uuid default gen_random_uuid()
) returns uuid
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_actor uuid := p_actor_id;
  v_role text := p_actor_role;
begin
  if app.uid() is not null then
    if not app.active() then
      raise exception 'not signed in' using errcode = '42501';
    end if;
    v_actor := app.uid();
    v_role := app.role();
  elsif coalesce(current_setting('role', true), 'none') in ('authenticated', 'anon') then
    raise exception 'audit entries are written by a signed-in user or the system' using errcode = '42501';
  end if;
  if v_actor is null or v_role is null then
    raise exception 'audit actor is required' using errcode = '22023';
  end if;
  insert into public.audit_log (id, "at", actor_id, actor_name, actor_role, action, target_type, target_id, target_label, reason, assistance_id)
  values (p_id, p_at, v_actor, coalesce(p_actor_name, ''), v_role, p_action, p_target_type, p_target_id, p_target_label, p_reason, p_assistance_id);
  return p_id;
end $$;
comment on function app.audit is 'Writes an audit entry (BACKEND_SPEC §9): the only INSERT path for authenticated.';

-- Recomputes the chain in order; ok = false with the first broken entry.
create or replace function app.verify_audit_chain() returns table (ok boolean, checked bigint, first_broken uuid)
  language plpgsql stable security definer set search_path = ''
as $$
declare
  r public.audit_log;
  v_prev bytea := null;
  v_n bigint := 0;
begin
  for r in select * from public.audit_log order by chain_seq loop
    v_n := v_n + 1;
    if r.prev_hash is distinct from v_prev
      or r.hash is distinct from extensions.digest(coalesce(encode(v_prev, 'hex'), '') || '|' || app.audit_canonical(r), 'sha256') then
      return query select false, v_n, r.id;
      return;
    end if;
    v_prev := r.hash;
  end loop;
  return query select true, v_n, null::uuid;
end $$;
comment on function app.verify_audit_chain is 'Verifies the audit hash chain (daily by pg_cron).';

revoke execute on all functions in schema app from public;
grant execute on all functions in schema app to authenticated, service_role;
revoke execute on function app.verify_audit_chain() from authenticated;
revoke execute on function app.audit_chain() from authenticated;
revoke execute on function app.audit_immutable() from authenticated;
`;
}

// ------------------------------------------------------------------------------------------------
// 6. background jobs (BACKEND_SPEC §10)
// ------------------------------------------------------------------------------------------------
function jobs(): string {
  const schedule = JOBS.map((j) => {
    const cmd = j.runner === 'db' ? j.sql! : `select app.enqueue_job(${lit(j.name)})`;
    return `    perform cron.schedule(${lit(`mig:${j.name}`)}, ${lit(j.cron)}, ${lit(cmd)});`;
  });
  const now = `(extract(epoch from now()) * 1000)::bigint`;
  return `${HEADER('Background jobs (BACKEND_SPEC §10): schedules from packages/domain/src/services/jobs.ts.')}
-- Jobs that need the domain services are queued for the API (step 4 runs them with the system context).
create table app.job_queue (
  id bigint generated always as identity primary key,
  name text not null,
  requested_at timestamptz not null default now(),
  taken_at timestamptz,
  done_at timestamptz,
  error text
);
create index job_queue_pending_idx on app.job_queue (name) where taken_at is null;
comment on table app.job_queue is 'Runs of API jobs requested by pg_cron; the API takes pending rows.';
revoke all on app.job_queue from public, authenticated;

create table app.job_catalog (
  name text primary key,
  cron text not null,
  runner text not null check (runner in ('db', 'api')),
  command text not null,
  description text not null
);
comment on table app.job_catalog is 'The schedules of jobs.ts (also registered in pg_cron when it is available).';
insert into app.job_catalog (name, cron, runner, command, description) values
${JOBS.map((j) => `  (${lit(j.name)}, ${lit(j.cron)}, ${lit(j.runner)}, ${lit(j.runner === 'db' ? j.sql! : j.service!)}, ${lit(j.description)})`).join(',\n')};
revoke all on app.job_catalog from public, authenticated;

create or replace function app.enqueue_job(p_name text) returns void
  language sql volatile security definer set search_path = ''
as $$ insert into app.job_queue (name) values (p_name) $$;

-- Expired sessions, challenges, attempt counters and tokens (epoch columns are milliseconds).
create or replace function app.job_cleanup_expired() returns jsonb
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_now bigint := ${now};
  v_day bigint := 24 * 3600 * 1000;
  v jsonb := '{}'::jsonb;
  n bigint;
begin
  delete from public.sessions where last_activity < v_now - 12 * 3600 * 1000; get diagnostics n = row_count; v := v || jsonb_build_object('sessions', n);
  delete from public.challenges where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('challenges', n);
  delete from public.grants where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('grants', n);
  delete from public.lockouts where until < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('lockouts', n);
  delete from public.login_failures where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('login_failures', n);
  delete from public.check_attempts where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('check_attempts', n);
  delete from public.check_locks where until < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('check_locks', n);
  delete from public.card_tokens where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('card_tokens', n);
  delete from public.access_tokens where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('access_tokens', n);
  delete from public.idempotency where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('idempotency', n);
  delete from public.api_calls where "at" < v_now - 3600 * 1000; get diagnostics n = row_count; v := v || jsonb_build_object('api_calls', n);
  return v;
end $$;

-- Daily check of the audit chain: on a break every active MIG admin gets a notification.
create or replace function app.job_verify_audit_chain() returns boolean
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v record;
begin
  select * into v from app.verify_audit_chain();
  if not v.ok then
    insert into public.notifications (id, text, detail, link, created_at, read, user_id)
    select gen_random_uuid(), 'srv.auditChainBroken', v.first_broken::text, '/staff/admin/audit', now(), false, s.id
      from public.staff s where s.role = 'admin' and s.active;
  end if;
  return v.ok;
end $$;

revoke execute on all functions in schema app from public;
grant execute on all functions in schema app to authenticated, service_role;
revoke execute on function app.verify_audit_chain() from authenticated;
revoke execute on function app.audit_chain() from authenticated;
revoke execute on function app.audit_immutable() from authenticated;
revoke execute on function app.enqueue_job(text) from authenticated;
revoke execute on function app.job_cleanup_expired() from authenticated;
revoke execute on function app.job_verify_audit_chain() from authenticated;

-- pg_cron is optional: where it is missing the migration still applies and the jobs stay unscheduled.
do $do$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
${schedule.join('\n')}
  else
    raise notice 'pg_cron is not available: background jobs are not scheduled';
  end if;
end
$do$;
`;
}

export const MIGRATIONS_DIR = 'supabase/migrations';

/** The migrations, in order. File names are fixed: a new logical change gets a new file. */
export function buildMigrations(): SqlFile[] {
  return [
    { name: '20261009000100_app_core.sql', sql: appCore() },
    { name: '20261009000200_schema.sql', sql: schema() },
    { name: '20261009000300_app_scopes.sql', sql: scopes() },
    { name: '20261009000400_rls.sql', sql: rls() },
    { name: '20261009000500_audit.sql', sql: audit() },
    { name: '20261009000600_jobs.sql', sql: jobs() },
  ];
}

export { META_COLUMNS };
