/*
 * Migration of stage 1.5 (the assistance search by the last 4 digits of the phone): the separate search HMAC of the
 * phone's tail (`insured.phone_tail_hmac`, store/sql/physical.ts PII_TAILS). Written by the repositories with the phone;
 * rows written before it get it from the API worker (apps/api/src/jobs/phoneTail.ts: the key is not in the database).
 * Selectable by `authenticated` like `phone_hmac` (a filter needs it; RLS limits the rows, and without the API's key
 * the value says nothing). Generated like the others (scripts/gen-schema.mjs).
 */
import { enumWidening } from './migrationsJobs';

export const PHONE_TAIL_MIGRATION = '20261015000100_phone_tail.sql';

const HEADER = (what: string) =>
  `-- ${what}\n-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/migrationsPhoneTail.ts. Do not edit by hand:\n-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.\n`;

export function phoneTailMigration(): string {
  return `${HEADER('The search of an assistance operator by the last 4 digits of the phone (only with a part of the name or the birth date, only among its own insured persons): a separate HMAC of the tail, so the full phone HMAC stays unusable for a partial search.')}
-- HMAC-SHA-256 (the PII HMAC key of the API) of \`tail4:<last 4 digits>\`: 10 000 possible values, so it narrows a search
-- that must also match the name or the birth date; never shown. A filter on it needs the column's select privilege (as
-- phone_hmac): the rows stay those of the person's RLS, and without the API's key the value says nothing.
alter table public.insured add column phone_tail_hmac bytea;
create index insured_phone_tail_idx on public.insured (phone_tail_hmac) where phone_tail_hmac is not null;
grant select (phone_tail_hmac) on public.insured to authenticated;
comment on column public.insured.phone_tail_hmac is 'HMAC of the last 4 digits of the phone (tail4:NNNN): the assistance search together with a part of the name or the birth date.';

-- Every such search is audited.
${enumWidening(PHONE_TAIL_MIGRATION).join('\n')}
`;
}
