/*
 * Migrations of step 4, part 2 (BACKEND_SPEC §7, §8, §10): BFF sessions and sign-in challenges of the API, the
 * identity sync with Supabase Auth, the Custom Access Token Hook, attempt-counter and session cleanup, and file
 * storage metadata with the private Storage buckets. Generated like the others (scripts/gen-schema.mjs).
 */
import { CLEANUP_STATEMENTS, cleanupFunction } from './cleanup';
import { lit } from './physical';

const HEADER = (what: string) =>
  `-- ${what}\n-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/migrationsAuth.ts. Do not edit by hand:\n-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.\n`;

/** Accounts whose changes Supabase Auth must follow (table → the column holding the auth user id, watched columns). */
export const IDENTITY_SOURCES: readonly { table: string; userColumn: string; columns: string[] }[] = [
  { table: 'staff', userColumn: 'id', columns: ['email', 'role', 'active'] },
  { table: 'hr_users', userColumn: 'id', columns: ['email', 'company_id'] },
  { table: 'clinic_users', userColumn: 'id', columns: ['email', 'role', 'active', 'clinic_id'] },
  { table: 'assist_users', userColumn: 'id', columns: ['email', 'role', 'active', 'assistance_id'] },
  { table: 'insured', userColumn: 'user_id', columns: ['phone_hmac', 'status', 'user_id'] },
];

/** Tables of the API outside the domain repositories (RLS on, no policy: the service role only). */
export const API_TABLES = ['app_sessions', 'app_auth_challenges'] as const;

/** The private buckets of Supabase Storage (BACKEND_SPEC §8) with their limits. */
export const BUCKETS: readonly { id: string; maxBytes: number; mimes: string[] }[] = [
  {
    id: 'receipts',
    maxBytes: 10 * 1024 * 1024,
    mimes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  },
  { id: 'contract-scans', maxBytes: 20 * 1024 * 1024, mimes: ['image/jpeg', 'image/png', 'application/pdf'] },
  {
    id: 'guarantee-attachments',
    maxBytes: 10 * 1024 * 1024,
    mimes: ['image/jpeg', 'image/png', 'application/pdf'],
  },
  {
    id: 'documents',
    maxBytes: 20 * 1024 * 1024,
    mimes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  },
  { id: 'help-assets', maxBytes: 5 * 1024 * 1024, mimes: ['image/jpeg', 'image/png', 'image/webp'] },
];

/** The keys of `app_metadata` the access token keeps (domain auth/identity.ts) and Supabase's own provider keys. */
const META_KEYS = ['provider', 'providers', 'role', 'company_id', 'clinic_id', 'assistance_id', 'insured_id'];

/** Cleanup of part 2: idle BFF sessions, sign-in challenges, finished jobs (in addition to the step 3 list). */
export const AUTH_CLEANUP_STATEMENTS: readonly string[] = [
  ...CLEANUP_STATEMENTS,
  // The longest idle limit is 30 minutes (idleLimitsFor) plus the minute of grace the API allows.
  `delete from public.sessions s using public.app_sessions a where a.session_id = s.id and a.last_activity < now() - interval '31 minutes'; get diagnostics n = row_count; v := v || jsonb_build_object('app_sessions', n);`,
  `delete from public.app_auth_challenges where expires_at < now(); get diagnostics n = row_count; v := v || jsonb_build_object('app_auth_challenges', n);`,
  `delete from app.job_queue where done_at < now() - interval '7 days'; get diagnostics n = row_count; v := v || jsonb_build_object('job_queue', n);`,
];

function authMigration(): string {
  const triggers = IDENTITY_SOURCES.map(
    (
      s,
    ) => `create trigger ${s.table}_identity_sync after insert or update of ${s.columns.join(', ')} on public.${s.table}
  for each row execute function app.request_identity_sync(${lit(s.userColumn)});`,
  ).join('\n');
  return `${HEADER('Sign-in with Supabase Auth and BFF sessions of the API (BACKEND_SPEC §7), cleanup of counters (§10).')}
-- BFF sessions: the browser holds only the opaque cookie; the API keeps the Supabase tokens, encrypted.
-- Every row extends a row of public.sessions (the services end sessions there: logout, deactivation),
-- so deleting that row ends the BFF session too.
create table public.app_sessions (
  id_hash bytea primary key,
  session_id text not null unique references public.sessions (id) on delete cascade,
  user_id uuid not null,
  role text not null,
  aal text not null check (aal in ('aal1', 'aal2')),
  refresh_enc bytea not null,
  refresh_key_ver smallint not null,
  access_enc bytea not null,
  access_key_ver smallint not null,
  access_expires_at timestamptz not null,
  auth_session_id uuid,
  created_at timestamptz not null,
  last_activity timestamptz not null,
  ip inet,
  user_agent text check (length(user_agent) <= 512)
);
create index app_sessions_user_idx on public.app_sessions (user_id);
create index app_sessions_activity_idx on public.app_sessions (last_activity);
comment on table public.app_sessions is 'BFF sessions (BACKEND_SPEC §7): HMAC of the cookie value, the user, Supabase tokens encrypted with the personal-data key, AAL, activity, IP, user-agent. API only.';
alter table public.app_sessions enable row level security;
revoke all on public.app_sessions from public, anon, authenticated;
grant all on public.app_sessions to service_role;

-- Sign-in in progress: after the password (waiting for the TOTP code) or after the phone (waiting for the SMS code).
create table public.app_auth_challenges (
  id_hash bytea primary key,
  kind text not null check (kind in ('password', 'phone')),
  user_id uuid,
  role text,
  lock_key text not null,
  attempts integer not null default 0 check (attempts >= 0),
  factor_id uuid,
  enroll boolean not null default false,
  access_enc bytea,
  access_key_ver smallint,
  refresh_enc bytea,
  refresh_key_ver smallint,
  phone_enc bytea,
  phone_key_ver smallint,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  ip inet,
  user_agent text check (length(user_agent) <= 512)
);
create index app_auth_challenges_expires_idx on public.app_auth_challenges (expires_at);
comment on table public.app_auth_challenges is 'Sign-in challenges of the API (second step: TOTP or SMS code); tokens and the phone are encrypted. API only.';
alter table public.app_auth_challenges enable row level security;
revoke all on public.app_auth_challenges from public, anon, authenticated;
grant all on public.app_auth_challenges to service_role;

-- Accounts whose Supabase Auth user must follow a change of our tables (new account, role, binding, deactivation):
-- the API's worker creates or updates the user with the service role and sends invitations.
create table app.identity_sync (
  user_id uuid primary key,
  requested_at timestamptz not null default now(),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text
);
comment on table app.identity_sync is 'Outbox of account changes for Supabase Auth (the API worker syncs app_metadata, bans, invitations).';
revoke all on app.identity_sync from public, authenticated;
grant select, insert, update, delete on app.identity_sync to service_role;

create or replace function app.request_identity_sync() returns trigger
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_user uuid;
begin
  -- The seed provisions its users itself (supabase/seed.sql).
  if coalesce(current_setting('mig.seeding', true), '') = 'on' then
    return null;
  end if;
  v_user := nullif(to_jsonb(new) ->> tg_argv[0], '')::uuid;
  if v_user is not null then
    insert into app.identity_sync (user_id) values (v_user)
      on conflict (user_id) do update set requested_at = now(), attempts = 0, next_attempt_at = now(), last_error = null;
  end if;
  return null;
end $$;
${triggers}

-- The API worker takes queued jobs (pg_cron puts them) with the service role.
grant select, update, delete on app.job_queue to service_role;

-- Custom Access Token Hook of Supabase Auth: the claims keep only the roles and bindings of app_metadata
-- (set by the API with the service role); user_metadata never carries rights and is dropped from the token.
create or replace function public.custom_access_token_hook(event jsonb) returns jsonb
  language plpgsql stable set search_path = ''
as $$
declare
  v_claims jsonb := coalesce(event -> 'claims', '{}'::jsonb);
  v_meta jsonb := coalesce(event -> 'claims' -> 'app_metadata', '{}'::jsonb);
  v_out jsonb := '{}'::jsonb;
  k text;
begin
  foreach k in array array[${META_KEYS.map(lit).join(', ')}] loop
    if v_meta ? k then
      v_out := v_out || jsonb_build_object(k, v_meta -> k);
    end if;
  end loop;
  v_claims := jsonb_set(v_claims, '{app_metadata}', v_out);
  v_claims := jsonb_set(v_claims, '{user_metadata}', '{}'::jsonb);
  return jsonb_build_object('claims', v_claims);
end $$;
comment on function public.custom_access_token_hook(jsonb) is 'Supabase Auth hook: JWT claims carry app_metadata role and bindings only (BACKEND_SPEC §7).';
revoke execute on function public.custom_access_token_hook(jsonb) from public, anon, authenticated;
do $do$
begin
  if exists (select 1 from pg_roles where rolname = 'supabase_auth_admin') then
    grant usage on schema public to supabase_auth_admin;
    grant execute on function public.custom_access_token_hook(jsonb) to supabase_auth_admin;
  end if;
end
$do$;

${cleanupFunction(AUTH_CLEANUP_STATEMENTS)}
revoke execute on function app.request_identity_sync() from public, authenticated;
revoke execute on function app.job_cleanup_expired() from public, authenticated;
`;
}

export function sharedStateMigration(): string {
  return `${HEADER('State the API containers share (several API replicas behind Caddy): the demo knobs of ci/staging and the codes the Send SMS hook received in the test MFA mode. Nothing of a request lives in one process.')}
-- The demo deployment's switches (never production: the API has no demo routes there). One row.
create table app.demo_state (
  id boolean primary key default true check (id),
  failures boolean not null default false,
  offset_ms bigint not null default 0 check (offset_ms >= 0),
  updated_at timestamptz not null default now()
);
insert into app.demo_state (id) values (true);
comment on table app.demo_state is 'Demo knobs of ci/staging shared by the API replicas: the failure simulation and the test clock offset.';
revoke all on app.demo_state from public, authenticated;

-- ALLOW_TEST_TOTP only: the last code the Send SMS hook received per phone, taken once within five minutes by the
-- replica that verifies the sign-in (\`000000\` of a phone that is not a demo phone stands for it).
create table app.test_phone_codes (
  phone text primary key check (phone ~ '^[0-9]{9,15}$'),
  code text not null check (code ~ '^[0-9]{4,10}$'),
  at timestamptz not null default now()
);
comment on table app.test_phone_codes is 'Test MFA mode only (ALLOW_TEST_TOTP): the last SMS code per phone for the replica that verifies it; five minutes, once.';
revoke all on app.test_phone_codes from public, authenticated;
`;
}

export function storageGcMigration(): string {
  return `${HEADER('Storage objects of removed file rows: a queue the API worker drains (apps/api/src/files/gc.ts), so an object never outlives its row by more than a worker pass; orphans (an upload whose row never committed) are swept daily.')}
create table app.storage_gc (
  id bigint generated always as identity primary key,
  bucket text not null,
  object_name uuid not null,
  queued_at timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text
);
create index storage_gc_queued_idx on app.storage_gc (queued_at);
comment on table app.storage_gc is 'Objects of removed or replaced file rows waiting to be deleted from Storage by the API worker.';
revoke all on app.storage_gc from public, authenticated;

-- Every way a row goes (a delete, a cascade, a rollback of a portfolio transfer) or its object is replaced.
create function app.queue_storage_gc() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if old.object_name is not null and (tg_op = 'DELETE' or old.object_name is distinct from new.object_name) then
    insert into app.storage_gc (bucket, object_name) values (old.bucket, old.object_name);
  end if;
  return null;
end
$$;
revoke all on function app.queue_storage_gc() from public;
create trigger files_storage_gc after delete or update of object_name on public.files
  for each row execute function app.queue_storage_gc();
`;
}

function filesMigration(): string {
  const buckets = BUCKETS.map(
    (b) => `      (${lit(b.id)}, ${lit(b.id)}, false, ${b.maxBytes}, array[${b.mimes.map(lit).join(', ')}])`,
  ).join(',\n');
  return `${HEADER('Files in Supabase Storage (BACKEND_SPEC §8): the object of each file row, its SHA-256 and size; the private buckets.')}
-- Bytes live in a private bucket under a UUID name (no personal data); the row keeps where and the SHA-256.
alter table public.files
  add column bucket text check (bucket in (${BUCKETS.map((b) => lit(b.id)).join(', ')})),
  add column object_name uuid,
  add column sha256 text check (sha256 ~ '^[0-9a-f]{64}$'),
  add column size_bytes bigint check (size_bytes >= 0),
  add constraint files_object_check check ((bucket is null) = (object_name is null));
create unique index files_object_idx on public.files (bucket, object_name) where object_name is not null;
create index files_sha256_idx on public.files (sha256) where sha256 is not null;
comment on column public.files.object_name is 'Object name in the bucket (a UUID, no personal data).';
comment on column public.files.sha256 is 'SHA-256 of the stored bytes (duplicate receipts, integrity of signed scans).';

-- The private buckets (also ensured by the API at start: Storage may create its schema after the migrations).
do $do$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
${buckets}
    on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
  else
    raise notice 'Supabase Storage schema not found: buckets are created by the API';
  end if;
end
$do$;
`;
}

export function authMigrations(): { name: string; sql: string }[] {
  return [
    { name: '20261010000100_auth_sessions.sql', sql: authMigration() },
    { name: '20261010000200_files_storage.sql', sql: filesMigration() },
  ];
}
