/*
 * Migration of stage 1.5 (invitations by e-mail): the single-use links to set the first password of an e-mail account
 * (`app.invitations`, repo `invitations`, services/system/invitations.ts), their audit actions and their cleanup.
 * Generated like the others (scripts/gen-schema.mjs).
 */
import { cleanupFunction } from './cleanup';
import { enumWidening, JOBS_CLEANUP_STATEMENTS } from './migrationsJobs';

export const INVITATIONS_MIGRATION = '20261014000100_invitations.sql';

/** How long a closed invitation (used, revoked or expired) is kept for the record. */
export const INVITATION_KEEP_DAYS = 90;

export const INVITATIONS_CLEANUP_STATEMENTS: readonly string[] = [
  ...JOBS_CLEANUP_STATEMENTS,
  `delete from app.invitations where coalesce(used_at, revoked_at, expires_at) < now() - interval '${INVITATION_KEEP_DAYS} days'; get diagnostics n = row_count; v := v || jsonb_build_object('invitations', n);`,
];

const HEADER = (what: string) =>
  `-- ${what}\n-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/migrationsInvitations.ts. Do not edit by hand:\n-- change the TypeScript source and run \`node scripts/gen-schema.mjs\`.\n`;

export function invitationsMigration(): string {
  return `${HEADER('Invitations of e-mail accounts (staff, HR, clinics, assistance): a single-use link to set the first password, sent by the API worker through the SMTP of MIG; the TOTP factor is set up at the first sign-in.')}
-- One row per invitation; a new one of the same account revokes the open one. Only the SHA-256 of the token is kept
-- for the lookup; the token itself is sealed with the PII key (token_enc, token_key_ver) until the e-mail leaves and
-- dropped then. A send is leased for two minutes (two workers never send one twice) and tried at most 10 times.
create table app.invitations (
  id uuid primary key,
  user_id uuid not null,
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  token_enc bytea,
  token_key_ver smallint,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  sent_at timestamptz,
  used_at timestamptz,
  revoked_at timestamptz,
  attempts integer not null default 0 check (attempts >= 0),
  lease_until timestamptz,
  check (expires_at > created_at),
  check ((token_enc is null) = (token_key_ver is null))
);
create index invitations_user_idx on app.invitations (user_id, created_at desc);
create index invitations_unsent_idx on app.invitations (created_at) where sent_at is null and used_at is null and revoked_at is null;
comment on table app.invitations is 'Single-use links to set the first password of an e-mail account (repo invitations). System only: the API.';
alter table app.invitations enable row level security;
revoke all on app.invitations from public, anon, authenticated;
grant select, insert, update, delete on app.invitations to service_role;

${cleanupFunction(INVITATIONS_CLEANUP_STATEMENTS)}
revoke execute on function app.job_cleanup_expired() from public, authenticated;

-- Audit entries of invitations: sent (also again) and accepted.
${enumWidening(INVITATIONS_MIGRATION).join('\n')}
`;
}
