/*
 * docs/backend/RLS.md: who may select / insert / update / delete every table and why, generated from the
 * same access rules as the policies (scripts/gen-schema.mjs; a test fails when it is out of date).
 */
import type { Role } from '@mig/contracts';
import { TABLES } from '../schema';
import { ALL_ROLES, OPS, rolePredicate } from './rls';

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n\s*/g, ' ');

function who(op: (typeof OPS)[number], access: (typeof TABLES)[number]['access']): string {
  const byPred = new Map<string, Role[]>();
  for (const role of ALL_ROLES) {
    const p = rolePredicate(role, access[op]);
    if (p === 'false') continue;
    byPred.set(p, [...(byPred.get(p) ?? []), role]);
  }
  if (!byPred.size) return '—';
  return [...byPred.entries()].map(([p, roles]) => `${roles.join(', ')}: ${p === 'true' ? 'all rows' : `\`${cell(p)}\``}`).join('<br>');
}

export const RLS_DOC_PATH = 'docs/backend/RLS.md';

export function buildRlsDoc(): string {
  const rows = TABLES.map((t) => `| \`${t.table}\` | ${OPS.map((op) => who(op, t.access)).join(' | ')} | ${cell(t.access.note)} |`);
  return `# RLS: who can do what

Generated by \`node scripts/gen-schema.mjs\` from \`packages/domain/src/store/schema.ts\` (access rules) and
\`packages/domain/src/auth/permissions.ts\` (the matrix). Do not edit by hand.

Every policy also requires \`app.active()\`: a signed-in user with a role, and \`aal2\` (second factor) for MIG
staff, clinics and assistance companies. A role gets a row predicate only when its rule for one of the
table's actions is not \`false\` (\`app.can_any\`). «—» means no policy: nobody but the service role (the API's
\`systemDb\`: sign-in, jobs, outbox side effects) may do it. Column privileges additionally hide ciphertexts
of identity data (\`*_enc\`, \`*_key_ver\` of PINFL and phone), bank card tokens and partner secrets from
\`authenticated\`; lists of insured persons use the view \`insured_masked\`, full values come only from
\`app.reveal()\` (audited).

Helper functions of the predicates (schema \`app\`, SECURITY DEFINER): \`company_id()\`, \`insured_id()\`,
\`clinic_id()\`, \`assistance_id()\` — bindings from \`app_metadata\`; \`my_family_ids()\` — the person, the family
under them and their employee; \`my_person_ids()\` — the person, their children and adult family members who
gave consent; \`clinic_patient_ids()\` — patients with an open visit of the clinic; \`assist_covers(policy, day)\`
/ \`assist_covers_insured(person, day)\` — the policy is assigned to the assistance company on that day;
\`client_of_contract(contract)\`; \`registry_has_payer(lines, assistance)\`; \`client_of_deal(deal)\` — HR writes the
feed of the own company's deal; \`my_card_ids()\` — the person and the active family under them (card codes);
\`hr_asked_contract(contract)\` — an open request of MIG to HR for appendix 2 of a draft; \`assist_access(policy)\` /
\`assist_scope(policy, day)\` — the assistance scope of the domain (today, or read-only for 12 months after the
assignment ended); \`policy_of_insured(person)\`. A group may have several scopes, each with its own action gate.

What a role must learn about rows it may not read (counts, sums, codes, whether a slot is taken) and side effects in
another party's feed go through the narrow SECURITY DEFINER functions \`app.fact_*\` (migration \`…_app_facts.sql\`,
\`docs/PRIVILEGED_AUDIT.md\`): each checks \`app.active()\` and the permission itself and returns only the value.

| Table | select | insert | update | delete | Why |
|---|---|---|---|---|---|
${rows.join('\n')}
`;
}
