/*
 * `supabase/seed.sql` from the deterministic demo database (packages/seed, BACKEND_SPEC §3 «seed.sql
 * (генерируется)»). Rows keep their storage order in `_pos`.
 *
 * DEV/CI ONLY: personal data that the API encrypts (PINFL, phone, free medical texts) is sealed here with
 * AES-256-GCM under the published development key (version 1, store/piiAes.ts) with IVs derived from the value
 * (so the file is stable), and the search HMAC under the development HMAC key; no personal data is in the file
 * in clear. A deployment without `PII_KEYS` (development, CI) reads it with the same key; production refuses the
 * development keys, so a real environment never loads this seed.
 *
 * The Supabase Auth users of the demo accounts follow the data (authSeed.ts).
 */
import type { Db } from '../db';
import { maskCard, maskPhone, maskPinfl } from '../../lib/mask';
import { SEQUENCES, TABLES, sequenceName, type TableSpec } from '../schema';
import { qi, snake } from '../columns';
import { fieldMapping, lit, PII_TAILS, tailInput } from './physical';
import { devAesPiiCrypto } from '../piiAes';
import { buildAuthSeedSql } from './authSeed';
import { DEV_HMAC_KEY } from '../devKeys';

/** «Today» of the generated seed (the mock uses the current time instead). */
export const SEED_NOW = Date.parse('2026-10-09T09:00:00+05:00');
/** Development HMAC key of the seed's search hashes (the API uses its own secret, BACKEND_SPEC §5). */
export { DEV_HMAC_KEY };

type Rec = Record<string, unknown>;

/** Rows of a table taken from the memory database. */
export function rowsOf(db: Db, t: TableSpec): Rec[] {
  switch (t.collection) {
    case 'dmsParamChanges':
      return db.dmsParams.changes as unknown as Rec[];
    case 'aiChanges':
      return db.ai.changes as unknown as Rec[];
    case 'aiLogs':
      return db.ai.logs as unknown as Rec[];
    case 'helpQuestions':
      return db.help.questions as unknown as Rec[];
    case 'dmsParamValues':
      return Object.entries(db.dmsParams.values).map(([key, v]) => ({ key, ...(v as object) }));
    case 'aiSettings':
      return [{ id: 1, settings: db.ai.settings }];
    case 'integrationsSeed':
      return [{ id: 1, value: db.integrationsSeed }];
    case 'aiRebillFlags':
      return Object.entries(db.ai.rebillFlags).map(([lineId, reason]) => ({ lineId, reason }));
    case 'statementKeys':
      return db.statementKeys.map((key) => ({ key }));
    default:
      return (db as unknown as Record<string, Rec[]>)[t.collection] ?? [];
  }
}

const seedCrypto = devAesPiiCrypto({ deterministic: true });
const hex = (b: Uint8Array) => `'\\x${Buffer.from(b).toString('hex')}'::bytea`;

function scalar(kind: string, v: unknown): string {
  if (v === undefined || v === null) return 'null';
  switch (kind) {
    case 'int':
    case 'bigint':
    case 'float':
    case 'epoch':
      if (typeof v !== 'number' || !Number.isFinite(v)) throw new Error(`Not a number: ${String(v)}`);
      return String(v);
    case 'bool':
      return v ? 'true' : 'false';
    case 'json':
      return `${lit(JSON.stringify(v))}::jsonb`;
    case 'textArray':
      return (v as string[]).length ? `array[${(v as string[]).map(lit).join(', ')}]::text[]` : `'{}'::text[]`;
    default:
      return lit(String(v));
  }
}

function maskOf(field: string, plain: string): string {
  if (field === 'phone') return maskPhone(plain);
  return maskPinfl(plain);
}

/** Column names and SQL values of one row. */
export function rowValues(t: TableSpec, row: Rec): { columns: string[]; values: string[] } {
  const columns: string[] = [];
  const values: string[] = [];
  for (const [field, c] of Object.entries(t.columns)) {
    const m = fieldMapping(field, c);
    if (c.kind === 'virtual') continue;
    const v = row[field];
    if (c.pii) {
      const present = v !== undefined && v !== null;
      const plain = typeof v === 'string' ? v : JSON.stringify(v);
      columns.push(...m.columns);
      const sealed = present ? seedCrypto.sealSync(plain, `${t.table}.${field}`) : null;
      values.push(sealed ? hex(sealed.enc) : 'null', sealed ? String(sealed.keyVer) : 'null');
      if (c.pii === 'encrypt+hmac') values.push(present ? hex(seedCrypto.hmacSync(plain)) : 'null', present ? lit(maskOf(field, plain)) : 'null');
      const tailCol = PII_TAILS[`${t.collection}.${field}`];
      if (tailCol) {
        const tail = present ? tailInput(plain) : null;
        columns.push(tailCol);
        values.push(tail ? hex(seedCrypto.hmacSync(tail)) : 'null');
      }
      continue;
    }
    if (c.card) {
      columns.push(...m.columns);
      values.push(typeof v === 'string' ? lit(v ? maskCard(v) : '') : 'null', 'null');
      continue;
    }
    columns.push(snake(field));
    values.push(scalar(c.kind, v));
  }
  return { columns, values };
}

const CHUNK = 200;

export function buildSeedSql(db: Db): string {
  const out: string[] = [
    '-- Demo data for local development and CI. Generated by scripts/gen-seed-sql.mjs from createSeed() of packages/seed.',
    '-- DEV/CI ONLY: PINFL, phone and free texts are sealed with the published development key (AES-256-GCM, key version 1).',
    'begin;',
    'set constraints all deferred;',
    // The rows of the seed are not new accounts to sync with Supabase Auth (their users are provisioned below).
    "select set_config('mig.seeding', 'on', true);",
  ];
  let maxPos = 0;
  for (const t of TABLES) {
    const rows = rowsOf(db, t);
    if (!rows.length) continue;
    // The audit chain links entries in the order they were written: oldest first (the list is newest first).
    const order = rows.map((r, i) => ({ r, pos: i + 1 }));
    if (t.collection === 'audit') order.sort((a, b) => String(a.r.at).localeCompare(String(b.r.at)) || b.pos - a.pos);
    maxPos = Math.max(maxPos, rows.length);
    for (let i = 0; i < order.length; i += CHUNK) {
      const part = order.slice(i, i + CHUNK);
      const first = rowValues(t, part[0]!.r);
      const cols = [...first.columns, '_pos'];
      const tuples = part.map(({ r, pos }) => {
        const v = rowValues(t, r);
        if (v.columns.join() !== first.columns.join()) throw new Error(`Columns differ in ${t.table}`);
        return `  (${[...v.values, String(pos)].join(', ')})`;
      });
      out.push(`insert into public.${t.table} (${cols.map(qi).join(', ')}) values\n${tuples.join(',\n')};`);
    }
  }
  out.push(`select setval('app.pos_seq', ${maxPos + 1});`);
  for (const [name, coll] of Object.entries(SEQUENCES)) out.push(`select setval('public.${sequenceName(name as keyof typeof SEQUENCES)}', ${db[coll]});`);
  out.push('commit;', '', buildAuthSeedSql(db));
  return out.join('\n');
}
