export type Params = Record<string, string | number | boolean | undefined | null>;

export const qk = {
  me: ['auth', 'me'] as const,
  dashboard: ['dashboard'] as const,
  queue: (type: string, p: Record<string, string> = {}) => ['queue', type, p] as const,
  medicalFeed: ['dashboard', 'medical-access'] as const,
  integrations: ['integrations'] as const,
  clients: (p: Params) => ['clients', p] as const,
  client: (id: string) => ['client', id] as const,
  clientInsured: (id: string, p: Params) => ['client', id, 'insured', p] as const,
  clientDocuments: (id: string) => ['client', id, 'documents'] as const,
  clientHistory: (id: string) => ['client', id, 'history'] as const,
  clientKp: (id: string) => ['client', id, 'kp'] as const,
  kpDefaults: (clientId: string, policyId: string) => ['client', clientId, 'kp-defaults', policyId] as const,
  kp: (id: string) => ['kp', id] as const,
  policies: (p: Params) => ['policies', p] as const,
  policy: (id: string) => ['policy', id] as const,
  insuredList: (p: Params) => ['insured', 'list', p] as const,
  insured: (id: string) => ['insured', id] as const,
  insuredLimits: (id: string) => ['insured', id, 'limits'] as const,
  insuredClaims: (id: string) => ['insured', id, 'claims'] as const,
  insuredDocuments: (id: string) => ['insured', id, 'documents'] as const,
  insuredAccessLog: (id: string) => ['insured', id, 'access-log'] as const,
  medical: (id: string, grant: string) => ['insured', id, 'medical', grant] as const,
  claims: (p: Params) => ['claims', p] as const,
  claim: (id: string) => ['claim', id] as const,
  appointments: (p: Params) => ['appointments', p] as const,
  clinics: (p: Params) => ['clinics', p] as const,
  limitRequests: (p: Params) => ['limit-requests', p] as const,
  report: (name: string, p?: Params) => ['reports', name, p ?? {}] as const,
  audit: (p: Params) => ['audit', p] as const,
  adminUsers: ['admin', 'users'] as const,
  invitations: ['invitations'] as const,
  hrOverview: ['hr', 'overview'] as const,
  hrEmployees: (p: Params) => ['hr', 'employees', p] as const,
  hrDocuments: ['hr', 'documents'] as const,
  hrInvoices: ['hr', 'invoices'] as const,
  hrStats: ['hr', 'stats'] as const,
  meProfile: ['me', 'profile'] as const,
  mePolicy: ['me', 'policy'] as const,
  meLimits: ['me', 'limits'] as const,
  meClaims: ['me', 'claims'] as const,
  meClaim: (id: string) => ['me', 'claims', id] as const,
  meAppointments: ['me', 'appointments'] as const,
  nearby: (spec: string) => ['clinics', 'nearby', spec] as const,
  slots: (clinicId: string, date: string) => ['clinics', clinicId, 'slots', date] as const,
  chat: ['me', 'chat'] as const,
  cardToken: ['me', 'card-token'] as const,
  meFamily: ['me', 'family'] as const,
  meFamilyRequests: ['me', 'family-requests'] as const,
  hrFamily: (employeeId?: string) => ['hr', 'family', employeeId ?? 'all'] as const,
  hrFamilyRequests: (status?: string) => ['hr', 'family-requests', status ?? 'all'] as const,
};
