/* Contract of voluntary medical insurance (ДМС): STUB template, texts will be provided by MIG. */
import { clause, type DocTemplate } from './types';

export const CONTRACT_TEMPLATE: DocTemplate = {
  id: 'contract',
  name: 'Договор ДМС',
  version: 'ДОГОВОР-ЗАГЛУШКА 10/26',
  approved: false,
  heading: 'Договор добровольного медицинского страхования № {{contract.number}}',
  subheading: 'г. Ташкент · {{contract.date}} · редакция {{contract.version}}',
  signatures: 'both',
  sections: [
    {
      id: '1',
      title: '1. Стороны и предмет договора',
      clauses: [
        clause(
          '1.1',
          'Стороны договора',
          '{{mig.name}} (Страховщик), в лице {{mig.signatory.position}} {{mig.signatory.name}}, действующего на основании {{mig.signatory.basis}}, и {{client.name}} (Страхователь), в лице {{client.signatory.position}} {{client.signatory.name}}, действующего на основании {{client.signatory.basis}}',
        ),
        clause('1.2', 'Предмет договора', 'Программа страхования: {{program.name}} (Приложение 1)'),
        clause('1.3', 'Правила страхования', 'Правила страхования: {{contract.rulesRef}}'),
      ],
    },
    {
      id: '2',
      title: '2. Термины и определения',
      clauses: [clause('2.1', 'Основные термины'), clause('2.2', 'Толкование терминов')],
    },
    {
      id: '3',
      title: '3. Застрахованные лица',
      clauses: [
        clause('3.1', 'Список застрахованных', 'Застрахованных: {{insured.total}}, из них сотрудников {{insured.employees}}, членов семей {{insured.family}} (Приложение 2)'),
        clause('3.2', 'Сертификаты застрахованных'),
        clause('3.3', 'Включение и исключение застрахованных'),
      ],
    },
    {
      id: '4',
      title: '4. Страховые случаи и исключения',
      clauses: [
        clause('4.1', 'Страховой случай'),
        clause('4.2', 'Объём медицинской помощи'),
        clause('4.3', 'Исключения из страхового покрытия'),
        clause('4.4', 'Период ожидания'),
        clause('4.5', 'Услуги по гарантийному письму'),
        clause('4.6', 'Лимиты и подлимиты'),
      ],
    },
    {
      id: '5',
      title: '5. Страховая премия и порядок оплаты',
      clauses: [
        clause('5.1', 'Размер страховой премии', 'Премия за сотрудника {{premium.employee}}, за члена семьи {{premium.family}}, общая премия {{premium.total}}'),
        clause('5.2', 'График платежей', 'Порядок оплаты: {{contract.paymentFrequency}} (Приложение 3)'),
        clause('5.3', 'Просрочка оплаты'),
      ],
    },
    {
      id: '6',
      title: '6. Срок действия договора',
      clauses: [
        clause('6.1', 'Срок страхования', 'С {{contract.startDate}} по {{contract.endDate}}'),
        clause('6.2', 'Вступление договора в силу', 'Порядок вступления в силу: {{contract.activationRule}}'),
        clause('6.3', 'Продление договора'),
      ],
    },
    {
      id: '7',
      title: '7. Права и обязанности сторон',
      clauses: [clause('7.1', 'Обязанности Страховщика'), clause('7.2', 'Обязанности Страхователя'), clause('7.3', 'Права Страховщика'), clause('7.4', 'Права Страхователя')],
    },
    {
      id: '8',
      title: '8. Урегулирование страховых случаев',
      clauses: [
        clause('8.1', 'Порядок обращения за помощью'),
        clause('8.2', 'Документы для возмещения'),
        clause('8.3', 'Сроки рассмотрения'),
        clause('8.4', 'Основания для отказа в выплате'),
        clause('8.5', 'Частичное возмещение'),
        clause('8.6', 'Оспаривание решения'),
      ],
    },
    {
      id: '9',
      title: '9. Изменение и расторжение договора',
      clauses: [clause('9.1', 'Дополнительные соглашения'), clause('9.2', 'Досрочное расторжение'), clause('9.3', 'Возврат части премии')],
    },
    {
      id: '10',
      title: '10. Конфиденциальность и персональные данные',
      clauses: [clause('10.1', 'Обработка персональных данных'), clause('10.2', 'Медицинская тайна')],
    },
    {
      id: '11',
      title: '11. Разрешение споров и прочие условия',
      clauses: [clause('11.1', 'Порядок разрешения споров'), clause('11.2', 'Количество экземпляров')],
    },
    {
      id: '12',
      title: '12. Реквизиты сторон',
      clauses: [
        clause('12.1', 'Страховщик', '{{mig.name}}, ИНН {{mig.inn}}, {{mig.address}}, р/с {{mig.account}} в {{mig.bank}}, МФО {{mig.mfo}}'),
        clause('12.2', 'Страхователь', '{{client.name}}, ИНН {{client.inn}}, {{client.address}}, р/с {{client.account}} в {{client.bank}}, МФО {{client.mfo}}'),
      ],
    },
    { id: 'A1', title: 'Приложение 1. Программа страхования «{{program.name}}»', clauses: [clause('П1.1', 'Состав программы')], table: 'program' },
    { id: 'A2', title: 'Приложение 2. Список застрахованных', clauses: [clause('П2.1', 'Порядок ведения списка')], table: 'insured' },
    { id: 'A3', title: 'Приложение 3. График платежей', clauses: [clause('П3.1', 'Порядок оплаты взносов')], table: 'schedule' },
  ],
  fields: [
    { key: 'contract.number', description: 'Номер договора', source: 'Contract.number' },
    { key: 'contract.date', description: 'Дата договора', source: 'Contract.createdAt (дата создания версии)' },
    { key: 'contract.version', description: 'Номер редакции', source: 'Contract.version' },
    { key: 'contract.startDate', description: 'Начало срока страхования', source: 'Contract.params.startDate' },
    { key: 'contract.endDate', description: 'Окончание срока страхования', source: 'Contract.params.endDate' },
    { key: 'contract.activationRule', description: 'Порядок вступления в силу', source: 'Contract.params.activationRule: с даты начала или после первого взноса' },
    { key: 'contract.paymentFrequency', description: 'Порядок оплаты', source: 'Contract.params.paymentFrequency: единовременно, поквартально, помесячно' },
    { key: 'contract.rulesRef', description: 'Ссылка на правила страхования', source: 'Константа MIG_RULES_REF (документы МИГ)' },
    { key: 'mig.name', description: 'Наименование страховщика', source: 'Реквизиты МИГ (src/features/documents/mig.ts)' },
    { key: 'mig.inn', description: 'ИНН страховщика', source: 'Реквизиты МИГ' },
    { key: 'mig.address', description: 'Адрес страховщика', source: 'Реквизиты МИГ' },
    { key: 'mig.bank', description: 'Банк страховщика', source: 'Реквизиты МИГ' },
    { key: 'mig.account', description: 'Расчётный счёт страховщика', source: 'Реквизиты МИГ' },
    { key: 'mig.mfo', description: 'МФО банка страховщика', source: 'Реквизиты МИГ' },
    { key: 'mig.signatory.name', description: 'Подписант МИГ', source: 'Contract.params.migSignatoryId → StaffUser.fullName' },
    { key: 'mig.signatory.position', description: 'Должность подписанта МИГ', source: 'Роль подписанта (StaffUser.role)' },
    { key: 'mig.signatory.basis', description: 'Основание полномочий подписанта МИГ', source: 'StaffUser.signatory.basis' },
    { key: 'client.name', description: 'Наименование страхователя', source: 'Карточка клиента: formatLegalName(Client.name, Client.legalForm, язык документа)' },
    { key: 'client.inn', description: 'ИНН страхователя', source: 'Client.inn' },
    { key: 'client.address', description: 'Адрес страхователя', source: 'Client.requisites.address' },
    { key: 'client.bank', description: 'Банк страхователя', source: 'Client.requisites.bank' },
    { key: 'client.account', description: 'Расчётный счёт страхователя', source: 'Client.requisites.account' },
    { key: 'client.mfo', description: 'МФО банка страхователя', source: 'Client.requisites.mfo' },
    { key: 'client.signatory.name', description: 'Подписант клиента', source: 'Contract.params.clientSignatory.name (по умолчанию Client.requisites.director)' },
    { key: 'client.signatory.position', description: 'Должность подписанта клиента', source: 'Contract.params.clientSignatory.position' },
    { key: 'client.signatory.basis', description: 'Основание полномочий подписанта клиента', source: 'Contract.params.clientSignatory.basis (по умолчанию Client.requisites.directorBasis)' },
    { key: 'program.name', description: 'Программа страхования', source: 'Contract.params.program (из утверждённой котировки)' },
    { key: 'premium.employee', description: 'Премия за сотрудника в год', source: 'Contract.params.premiumEmployee' },
    { key: 'premium.family', description: 'Премия за члена семьи в год', source: 'Contract.params.premiumFamily' },
    { key: 'premium.total', description: 'Общая премия', source: 'Contract.params.total' },
    { key: 'insured.employees', description: 'Число сотрудников', source: 'Contract.params.employees' },
    { key: 'insured.family', description: 'Число членов семей', source: 'Contract.params.familyMembers' },
    { key: 'insured.total', description: 'Всего застрахованных', source: 'employees + familyMembers' },
  ],
  tables: [
    { id: 'program', title: 'Лимиты программы', columns: ['Категория', 'Лимит на застрахованного'], source: 'PROGRAMS[Contract.params.program].limits' },
    { id: 'insured', title: 'Список застрахованных', columns: ['№', 'ФИО', 'Должность', 'Членов семьи'], source: 'Список приложения 2 (формат HR-импорта), без ПИНФЛ и телефонов' },
    { id: 'schedule', title: 'График платежей', columns: ['№', 'Срок оплаты', 'Сумма'], source: 'Contract.params.paymentSchedule' },
  ],
};
