-- Files in Supabase Storage (BACKEND_SPEC §8): the object of each file row, its SHA-256 and size; the private buckets.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/migrationsAuth.ts. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

-- Bytes live in a private bucket under a UUID name (no personal data); the row keeps where and the SHA-256.
alter table public.files
  add column bucket text check (bucket in ('receipts', 'contract-scans', 'guarantee-attachments', 'documents', 'help-assets')),
  add column object_name uuid,
  add column sha256 text check (sha256 ~ '^[0-9a-f]{64}$'),
  add column size_bytes bigint check (size_bytes >= 0),
  add constraint files_object_check check ((bucket is null) = (object_name is null));
create unique index files_object_idx on public.files (bucket, object_name) where object_name is not null;
create index files_sha256_idx on public.files (sha256) where sha256 is not null;
comment on column public.files.object_name is 'Object name in the bucket (a UUID, no personal data).';
comment on column public.files.sha256 is 'SHA-256 of the stored bytes (duplicate receipts, integrity of signed scans).';

-- The private buckets (also ensured by the API at start: Storage may create its schema after the migrations).
do $do$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
      ('receipts', 'receipts', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']),
      ('contract-scans', 'contract-scans', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
      ('guarantee-attachments', 'guarantee-attachments', false, 10485760, array['image/jpeg', 'image/png', 'application/pdf']),
      ('documents', 'documents', false, 20971520, array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']),
      ('help-assets', 'help-assets', false, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
    on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
  else
    raise notice 'Supabase Storage schema not found: buckets are created by the API';
  end if;
end
$do$;
