-- Narrow facts (docs/PRIVILEGED_AUDIT.md): counts, codes and anonymous figures of rows the caller's RLS hides; side effects in another party's feed.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/facts.ts. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

create or replace function app.fact_client_insured_count(p_client uuid) returns integer
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select count(*)::int from public.insured i where i.client_id = p_client and i.status = 'active');
end $$;
comment on function app.fact_client_insured_count(uuid) is 'Active insured persons of a client the caller sees (the client card counter).';
revoke execute on function app.fact_client_insured_count(uuid) from public;
grant execute on function app.fact_client_insured_count(uuid) to authenticated, service_role;

create or replace function app.fact_client_legal_form(p_client uuid) returns text
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() or p_client = app.company_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select c.legal_form from public.clients c where c.id = p_client);
end $$;
comment on function app.fact_client_legal_form(uuid) is 'Legal form shown next to a client name (MIG staff; HR — the own company).';
revoke execute on function app.fact_client_legal_form(uuid) from public;
grant execute on function app.fact_client_legal_form(uuid) to authenticated, service_role;

create or replace function app.fact_client_claim_figures(p_client uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
      'category', c.category, 'serviceDate', c.service_date::text, 'createdAt', to_char(c.created_at at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'),
      'status', c.status, 'amountClaimed', c.amount_claimed, 'amountApproved', c.amount_approved)) order by c._pos), '[]'::jsonb)
    from public.claims c where c.client_id = p_client);
end $$;
comment on function app.fact_client_claim_figures(uuid) is 'Anonymous figures (category, dates, status, amounts) of the claims of a client, for clients.read: loss statistics.';
revoke execute on function app.fact_client_claim_figures(uuid) from public;
grant execute on function app.fact_client_claim_figures(uuid) to authenticated, service_role;

create or replace function app.fact_client_invoice_figures(p_client uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_build_object('number', i.number, 'amount', i.amount, 'issuedAt', i.issued_at::text) order by i._pos), '[]'::jsonb)
    from public.invoices i where i.client_id = p_client);
end $$;
comment on function app.fact_client_invoice_figures(uuid) is 'Number, amount and date of the invoices of a client, for clients.read (the last invoice of the client card).';
revoke execute on function app.fact_client_invoice_figures(uuid) from public;
grant execute on function app.fact_client_invoice_figures(uuid) to authenticated, service_role;

create or replace function app.fact_policy_brief(p_policy uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.policies p where p.id = p_policy and exists (select 1 from public.clients v where v.id = p.client_id and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) ))))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('number', p.number, 'startDate', p.start_date::text) from public.policies p where p.id = p_policy);
end $$;
comment on function app.fact_policy_brief(uuid) is 'Number and start date of a policy of a client the caller reads (the client card).';
revoke execute on function app.fact_policy_brief(uuid) from public;
grant execute on function app.fact_policy_brief(uuid) to authenticated, service_role;

create or replace function app.fact_client_history(p_client uuid, p_limit integer) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name, 'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label, 'assistanceId', a.assistance_id)) as j
      from public.audit_log a
      where a.action <> all(array['reveal_pii', 'open_medical']) and a.target_id = any(
        array[p_client::text]
        || array(select p.id::text from public.policies p where p.client_id = p_client)
        || array(select c.id::text from public.claims c where c.client_id = p_client)
        || array(select k.id::text from public.kp k where k.client_id = p_client))
      order by a._pos limit greatest(p_limit, 0)) e);
end $$;
comment on function app.fact_client_history(uuid, integer) is 'Audit entries about a client, its policies, claims and offers (no openings of personal or medical data, no reasons), for clients.read.';
revoke execute on function app.fact_client_history(uuid, integer) from public;
grant execute on function app.fact_client_history(uuid, integer) to authenticated, service_role;

create or replace function app.fact_company_claim_count(p_client uuid, p_since_ms bigint) returns integer
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.role() = 'hr' and p_client = app.company_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select count(*)::int from public.claims c join public.insured i on i.id = c.insured_id
      where i.client_id = p_client and i.status = 'active' and c.created_at >= to_timestamp(p_since_ms / 1000.0));
end $$;
comment on function app.fact_company_claim_count(uuid, bigint) is 'Number of claims of the active persons of the own company since a moment (HR statistics, shown k-anonymous): HR never reads claims.';
revoke execute on function app.fact_company_claim_count(uuid, bigint) from public;
grant execute on function app.fact_company_claim_count(uuid, bigint) to authenticated, service_role;

create or replace function app.fact_person_access_log(p_insured uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() and app.role() <> 'accountant' and (select app.can('insured.read')) and exists (select 1 from public.insured v where v.id = p_insured and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[]))) or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (client_id = (select app.company_id()))) or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.my_family_ids())::uuid[]))) or ((select app.is_clinic()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.clinic_patient_ids())::uuid[]))) or ((select app.is_assist()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (app.assist_covers(policy_id, current_date))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name, 'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label, 'reason', a.reason, 'assistanceId', a.assistance_id)) order by a._pos), '[]'::jsonb) from public.audit_log a
      where a.target_id = p_insured::text and a.action in ('reveal_pii', 'open_medical'));
end $$;
comment on function app.fact_person_access_log(uuid) is 'Openings of personal and medical data of a person the caller reads (the access log of the card): MIG card readers.';
revoke execute on function app.fact_person_access_log(uuid) from public;
grant execute on function app.fact_person_access_log(uuid) to authenticated, service_role;

create or replace function app.fact_own_audit_entries(p_actor uuid, p_actions text[], p_limit integer) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() and p_actor = app.uid() and p_actions <@ array['reveal_pii', 'open_medical']), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name, 'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label, 'reason', a.reason, 'assistanceId', a.assistance_id)) as j from public.audit_log a
      where a.actor_id = p_actor and a.action = any(p_actions) order by a._pos limit p_limit) e);
end $$;
comment on function app.fact_own_audit_entries(uuid, text[], integer) is 'The caller’s own openings of personal and medical data (the doctor’s desktop): a MIG employee, own entries only.';
revoke execute on function app.fact_own_audit_entries(uuid, text[], integer) from public;
grant execute on function app.fact_own_audit_entries(uuid, text[], integer) to authenticated, service_role;

create or replace function app.fact_advance_deal(p_deal uuid, p_stage text, p_order text[], p_at timestamptz) returns boolean
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() or (app.role() = 'hr' and app.client_of_deal(p_deal) = app.company_id())), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  declare
    v text;
  begin
    select d.stage into v from public.deals d where d.id = p_deal for update;
    if v is null or v = 'lost' then
      return false;
    end if;
    if coalesce(array_position(p_order, p_stage), 0) <= coalesce(array_position(p_order, v), 0) and p_stage <> v then
      return false;
    end if;
    if p_stage <> v then
      update public.deals set stage = p_stage, updated_at = p_at where id = p_deal;
    end if;
    return true;
  end;
end $$;
comment on function app.fact_advance_deal(uuid, text, text[], timestamptz) is 'Moves a deal forward along the pipeline order (never back, never out of lost) after an event of any party: MIG staff, HR of the own company.';
revoke execute on function app.fact_advance_deal(uuid, text, text[], timestamptz) from public;
grant execute on function app.fact_advance_deal(uuid, text, text[], timestamptz) to authenticated, service_role;

create or replace function app.fact_push_clinic_event(p_id uuid, p_clinic uuid, p_at timestamptz, p_text text) returns void
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.clinics c where c.id = p_clinic) and (not app.is_clinic() or p_clinic = app.clinic_id()) and length(p_text) <= 2000), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  insert into public.clinic_events (id, clinic_id, "at", "text", _pos) values (p_id, p_clinic, p_at, p_text, -nextval('app.pos_seq'));
  delete from public.clinic_events where id in (select e.id from public.clinic_events e order by e._pos offset 500);
end $$;
comment on function app.fact_push_clinic_event(uuid, uuid, timestamptz, text) is 'An event in the feed of a clinic cabinet caused by any party (a booking, a referral, a decision); the newest ${CLINIC_EVENTS_KEPT} are kept. A clinic writes only into its own feed.';
revoke execute on function app.fact_push_clinic_event(uuid, uuid, timestamptz, text) from public;
grant execute on function app.fact_push_clinic_event(uuid, uuid, timestamptz, text) to authenticated, service_role;

create or replace function app.fact_append_client_log(p_client uuid, p_entry jsonb) returns void
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((app.is_staff() or (app.role() = 'hr' and p_client = app.company_id())) and jsonb_typeof(p_entry) = 'object' and length(p_entry::text) <= 4000), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  update public.clients set log = jsonb_build_array(jsonb_build_object('at', p_entry ->> 'at', 'text', p_entry ->> 'text')) || coalesce(log, '[]'::jsonb) where id = p_client;
end $$;
comment on function app.fact_append_client_log(uuid, jsonb) is 'A line at the top of the activity log of a client after an action on a request: MIG staff, HR of the own company (who may not update the client).';
revoke execute on function app.fact_append_client_log(uuid, jsonb) from public;
grant execute on function app.fact_append_client_log(uuid, jsonb) to authenticated, service_role;

create or replace function app.fact_redeem_card_token(p_short_code text, p_token text, p_now bigint) returns jsonb
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_clinic() and (select app.can('clinic.check_patient'))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  declare
    r public.card_tokens;
  begin
    if p_short_code is not null then
      select * into r from public.card_tokens t where t.short_code = p_short_code order by t._pos limit 1 for update;
    else
      select * into r from public.card_tokens t where t.token = p_token order by t._pos limit 1 for update;
    end if;
    if r.token is not null and r.used_at is not null then
      return jsonb_build_object('status', 'used');
    end if;
    if r.token is null or r.expires_at < p_now then
      return jsonb_build_object('status', 'stale');
    end if;
    update public.card_tokens set used_at = p_now where token = r.token;
    return jsonb_build_object('status', 'ok', 'insuredId', r.insured_id);
  end;
end $$;
comment on function app.fact_redeem_card_token(text, text, bigint) is 'Redeems a card code shown at the desk once (a clinic checking a patient): only the person id, or used/stale. The clinic never reads card tokens.';
revoke execute on function app.fact_redeem_card_token(text, text, bigint) from public;
grant execute on function app.fact_redeem_card_token(text, text, bigint) to authenticated, service_role;

create or replace function app.fact_match_policy_pinfl(p_number text, p_pinfl_hmac bytea) returns uuid
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_clinic() and (select app.can('clinic.check_patient'))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select i.id from public.insured i
      where i.policy_id = (select p.id from public.policies p where upper(p.number) = upper(p_number) order by p._pos limit 1)
        and i.pinfl_hmac = p_pinfl_hmac and i.status = 'active' order by i._pos limit 1);
end $$;
comment on function app.fact_match_policy_pinfl(text, bytea) is 'The active person of a policy number and a PINFL (search HMAC) before a visit exists: a clinic checking a patient gets only the id (rate-limited and audited by the API).';
revoke execute on function app.fact_match_policy_pinfl(text, bytea) from public;
grant execute on function app.fact_match_policy_pinfl(text, bytea) to authenticated, service_role;

create or replace function app.fact_visit_patient(p_visit uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.visits v where v.id = p_visit and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[]))) or ((select app.is_clinic()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])) and (clinic_id = (select app.clinic_id()))) or ((select app.is_assist()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, (opened_at at time zone (select app.tz()))::date))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('id', i.id, 'fullName', i.full_name, 'policyId', i.policy_id)
      from public.visits v join public.insured i on i.id = v.insured_id where v.id = p_visit);
end $$;
comment on function app.fact_visit_patient(uuid) is 'Name and policy of the patient of a visit the caller sees, also after the visit closed (registry lines, payer routing).';
revoke execute on function app.fact_visit_patient(uuid) from public;
grant execute on function app.fact_visit_patient(uuid) to authenticated, service_role;

create or replace function app.fact_visit_policy_period(p_visit uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.visits v where v.id = p_visit and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[]))) or ((select app.is_clinic()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])) and (clinic_id = (select app.clinic_id()))) or ((select app.is_assist()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, (opened_at at time zone (select app.tz()))::date))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('startDate', p.start_date::text, 'endDate', p.end_date::text)
      from public.visits v join public.insured i on i.id = v.insured_id join public.policies p on p.id = i.policy_id where v.id = p_visit);
end $$;
comment on function app.fact_visit_policy_period(uuid) is 'Term of the policy of the patient of a visit the caller sees (registry line checks of the clinic).';
revoke execute on function app.fact_visit_policy_period(uuid) from public;
grant execute on function app.fact_visit_policy_period(uuid) to authenticated, service_role;

create or replace function app.fact_policy_routing(p_policy uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff()
      or (app.role() = 'insured' and p_policy = app.my_policy_id())
      or (app.role() = 'hr' and exists (select 1 from public.policies p where p.id = p_policy and p.client_id = app.company_id()))
      or (app.is_clinic() and exists (select 1 from public.visits v join public.insured i on i.id = v.insured_id where v.clinic_id = app.clinic_id() and i.policy_id = p_policy))
      or (app.is_assist() and exists (select 1 from public.assignments a where a.policy_id = p_policy and a.assistance_id = app.assistance_id()))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_build_object('policyId', a.policy_id, 'assistanceId', a.assistance_id, 'from', a."from"::text)
        || case when a."to" is null then '{}'::jsonb else jsonb_build_object('to', a."to"::text) end order by a._pos), '[]'::jsonb)
      from public.assignments a where a.policy_id = p_policy);
end $$;
comment on function app.fact_policy_routing(uuid) is 'Which assistance company serves a policy from which date (no author): MIG staff; the insured person and HR of the policy; a clinic that had a patient of it; an assistance company that served it.';
revoke execute on function app.fact_policy_routing(uuid) from public;
grant execute on function app.fact_policy_routing(uuid) to authenticated, service_role;

create or replace function app.fact_file_kind(p_file uuid) returns text
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((true), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select case when f.guarantee_id is not null then 'guarantee' else 'other' end from public.files f where f.id = p_file);
end $$;
comment on function app.fact_file_kind(uuid) is 'Whether a file exists and is a guarantee-letter attachment: the download answers 403 or 404 for a file hidden by RLS exactly as the mock (never the file).';
revoke execute on function app.fact_file_kind(uuid) from public;
grant execute on function app.fact_file_kind(uuid) to authenticated, service_role;

create or replace function app.fact_limit_sums(p_insured uuid, p_mode text, p_today date, p_claim_to_limit jsonb, p_limit_of_service jsonb) returns jsonb
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((app.is_staff() and (select app.can_any(array['insured.read', 'claims.read', 'ai.coverage.mig']::text[])))
      or (app.role() = 'insured' and p_insured = any(app.my_person_ids()))
      or (app.is_clinic() and exists (select 1 from public.visits v where v.insured_id = p_insured and v.clinic_id = app.clinic_id()))
      or (app.is_assist() and exists (select 1 from public.insured i join public.assignments a on a.policy_id = i.policy_id where i.id = p_insured and a.assistance_id = app.assistance_id()))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  declare
    i public.insured;
    v_from date;
    v_program text;
    v_pool uuid[];
    v_used jsonb;
    v_reserved jsonb;
  begin
    select * into i from public.insured x where x.id = p_insured;
    if i.id is null then
      return null;
    end if;
    select p.start_date, p.program into v_from, v_program from public.policies p where p.id = i.policy_id;
    if p_mode = 'individual' then
      v_pool := array[i.id];
    else
      select coalesce(array_agg(x.id), '{}') into v_pool from public.insured x
        where x.policy_id = i.policy_id and coalesce(x.principal_id, x.id) = coalesce(i.principal_id, i.id);
    end if;
    -- The lazy clock: an approved letter of the pool past its validity expires.
    update public.guarantees g set status = 'expired'
      where g.insured_id = any(v_pool) and g.status = 'approved' and g.valid_until is not null and g.valid_until < p_today;
    with used as (
      select p_claim_to_limit ->> c.category as cat, coalesce(c.amount_approved, c.amount_claimed)::numeric as amount
        from public.claims c
        where c.insured_id = any(v_pool) and c.status in ('approved', 'to_pay', 'paid') and (v_from is null or c.service_date >= v_from - 7)
      union all
      select m.key, m.value::numeric from public.insured x cross join lateral jsonb_each_text(coalesce(x.migrated_used, '{}'::jsonb)) as m(key, value)
        where x.id = any(v_pool)
      union all
      select p_limit_of_service ->> coalesce(pi.category, 'outpatient'), (l.e ->> 'amount')::numeric
        from public.registries reg
        cross join lateral jsonb_array_elements(coalesce(reg.lines, '[]'::jsonb)) as l(e)
        join public.visits v on v.id::text = l.e ->> 'visitId' and v.insured_id = any(v_pool)
        left join lateral (select it.e ->> 'category' as category from public.price_lists pl cross join lateral jsonb_array_elements(coalesce(pl.items, '[]'::jsonb)) with ordinality as it(e, n)
          where pl.clinic_id = reg.clinic_id and it.e ->> 'code' = l.e ->> 'serviceCode' order by it.n limit 1) pi on true
        where l.e ->> 'status' = 'accepted' and coalesce(l.e ->> 'payer', 'mig') <> 'mig'
          and (v_from is null or (l.e ->> 'serviceDate')::date >= v_from - 7)
          and not exists (select 1 from public.claims c2 where c2.insured_id = v.insured_id and c2.registry_line_id::text = l.e ->> 'id'
            and c2.status in ('approved', 'to_pay', 'paid'))
    )
    select coalesce(jsonb_object_agg(u.cat, u.total), '{}'::jsonb) into v_used from (select cat, sum(amount) as total from used group by cat) u;
    select coalesce(jsonb_object_agg(r.cat, r.total), '{}'::jsonb) into v_reserved from (
      select p_limit_of_service ->> coalesce(pi.category, 'outpatient') as cat, sum(coalesce(g.approved_amount, g.estimated_cost)) as total
        from public.guarantees g
        left join lateral (select it.e ->> 'category' as category from public.price_lists pl cross join lateral jsonb_array_elements(coalesce(pl.items, '[]'::jsonb)) with ordinality as it(e, n)
          where pl.clinic_id = g.clinic_id and it.e ->> 'code' = g.service_code order by it.n limit 1) pi on true
        where g.insured_id = any(v_pool) and g.status = 'approved'
        group by 1) r;
    return jsonb_build_object('program', v_program, 'used', v_used, 'reserved', v_reserved);
  end;
end $$;
comment on function app.fact_limit_sums(uuid, text, date, jsonb, jsonb) is 'Used and reserved sums of the limits of a person by category, and the program (no claims, letters or lines): whoever may check the person. An approved letter of the pool past its validity expires (lazy clock).';
revoke execute on function app.fact_limit_sums(uuid, text, date, jsonb, jsonb) from public;
grant execute on function app.fact_limit_sums(uuid, text, date, jsonb, jsonb) to authenticated, service_role;

create or replace function app.fact_coverage_brief(p_insured uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((app.is_staff() and (select app.can_any(array['insured.read', 'claims.read', 'ai.coverage.mig']::text[])))
      or (app.role() = 'insured' and p_insured = any(app.my_person_ids()))
      or (app.is_clinic() and exists (select 1 from public.visits v where v.insured_id = p_insured and v.clinic_id = app.clinic_id()))
      or (app.is_assist() and exists (select 1 from public.insured i join public.assignments a on a.policy_id = i.policy_id where i.id = p_insured and a.assistance_id = app.assistance_id()))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object(
        'person', jsonb_strip_nulls(jsonb_build_object('id', i.id, 'status', i.status, 'insuredFrom', i.insured_from::text, 'excludedFrom', i.excluded_from::text)),
        'policy', (select jsonb_build_object('id', p.id, 'number', p.number, 'program', p.program, 'startDate', p.start_date::text, 'endDate', p.end_date::text, 'status', p.status)
          from public.policies p where p.id = i.policy_id))
      from public.insured i where i.id = p_insured);
end $$;
comment on function app.fact_coverage_brief(uuid) is 'Term, program and status of the policy and the person’s own dates (the coverage answer): whoever may check the person.';
revoke execute on function app.fact_coverage_brief(uuid) from public;
grant execute on function app.fact_coverage_brief(uuid) to authenticated, service_role;

create or replace function app.fact_taken_slots(p_clinic uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((not app.is_clinic() or p_clinic = app.clinic_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(to_char(a.starts_at at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"') order by a._pos), '[]'::jsonb)
      from public.appointments a where a.clinic_id = p_clinic and a.status not in ('cancelled', 'declined'));
end $$;
comment on function app.fact_taken_slots(uuid) is 'Start times of the live appointments of a clinic, whoever booked them (no person): free slots for every signed-in role; a clinic only its own.';
revoke execute on function app.fact_taken_slots(uuid) from public;
grant execute on function app.fact_taken_slots(uuid) to authenticated, service_role;
