-- Scope helpers of the RLS policies (BACKEND_SPEC §6): «own» rows of HR, the insured, clinics and assistance companies.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/schema.ts and friends. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

create or replace function app.my_policy_id() returns uuid
  language sql stable security definer set search_path = ''
as $$
  select i.policy_id from public.insured i where i.id = app.insured_id()
$$;
comment on function app.my_policy_id is 'Policy of the signed-in insured person.';

create or replace function app.my_client_id() returns uuid
  language sql stable security definer set search_path = ''
as $$
  select i.client_id from public.insured i where i.id = app.insured_id()
$$;
comment on function app.my_client_id is 'Client company of the signed-in insured person.';

create or replace function app.my_family_ids() returns uuid[]
  language sql stable security definer set search_path = ''
as $$
  select coalesce(array_agg(distinct x), '{}') from (
    select app.insured_id() as x
    union all select i.id from public.insured i where i.principal_id = app.insured_id()
    union all select i.principal_id from public.insured i where i.id = app.insured_id() and i.principal_id is not null
  ) s where x is not null
$$;
comment on function app.my_family_ids is 'The insured person, the family under them and their employee: names of the family screen.';

create or replace function app.my_person_ids() returns uuid[]
  language sql stable security definer set search_path = ''
as $$
  select coalesce(array_agg(distinct x), '{}') from (
    select app.insured_id() as x
    union all select i.id from public.insured i where i.principal_id = app.insured_id() and i.relation = 'child'
    union all select c.owner_id from public.family_consents c
      join public.insured o on o.id = c.owner_id
      where c.viewer_id = app.insured_id() and c.revoked_at is null and o.principal_id = app.insured_id()
  ) s where x is not null
$$;
comment on function app.my_person_ids is 'Persons whose claims and appointments the insured person sees: self, children, adults of the family with consent (FAMILY_SPEC).';

create or replace function app.clinic_patient_ids() returns uuid[]
  language sql stable security definer set search_path = ''
as $$
  select coalesce(array_agg(distinct v.insured_id), '{}') from public.visits v where v.clinic_id = app.clinic_id() and v.expires_at > now()
$$;
comment on function app.clinic_patient_ids is 'Patients of the clinic with an open visit (CLINIC_SPEC: access only through a visit).';

create or replace function app.assist_covers(p_policy uuid, p_day date) returns boolean
  language sql stable security definer set search_path = ''
as $$
  select exists (select 1 from public.assignments a
    where a.policy_id = p_policy and a.assistance_id = app.assistance_id()
      and a."from" <= p_day and (a."to" is null or p_day <= a."to"))
$$;
comment on function app.assist_covers is 'The policy is assigned to the user’s assistance company on the date (ASSISTANCE_SPEC §3).';

create or replace function app.assist_covers_insured(p_insured uuid, p_day date) returns boolean
  language sql stable security definer set search_path = ''
as $$
  select app.assist_covers((select i.policy_id from public.insured i where i.id = p_insured), p_day)
$$;
comment on function app.assist_covers_insured is 'The person’s policy is assigned to the user’s assistance company on the date.';

create or replace function app.client_of_contract(p_contract uuid) returns uuid
  language sql stable security definer set search_path = ''
as $$
  select c.client_id from public.contracts c where c.id = p_contract
$$;
comment on function app.client_of_contract is 'Client of a contract (HR scope of appendices, change requests, endorsements).';

create or replace function app.registry_has_payer(p_lines jsonb, p_payer uuid) returns boolean
  language sql immutable security definer set search_path = ''
as $$
  select p_payer is not null and exists (select 1 from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb)) l where l ->> 'payer' = p_payer::text)
$$;
comment on function app.registry_has_payer is 'A registry has lines paid by the assistance company.';

create or replace function app.mask_email(p_email text) returns text
  language sql immutable security definer set search_path = ''
as $$
  select case when p_email is null or p_email = '' then p_email else left(split_part(p_email, '@', 1), 1) || '•••@' || split_part(p_email, '@', 2) end
$$;
comment on function app.mask_email is 'a•••@company.uz (the same mask as packages/domain/src/lib/mask.ts).';

-- The full value of PINFL or phone (ciphertext and key version; the API decrypts) for a role allowed to see
-- it, written to the audit log. The only way for `authenticated` to read *_enc of identity data.
create or replace function app.reveal(p_table text, p_id text, p_field text, p_reason text, p_actor_name text default null)
  returns table (enc bytea, key_ver smallint)
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_enc bytea;
  v_ver smallint;
begin
  if not app.active() then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  if coalesce(btrim(p_reason), '') = '' then
    raise exception 'a reason is required' using errcode = '22023';
  end if;
  if p_table = 'insured' and p_field = 'pinfl' then
    select r.pinfl_enc, r.pinfl_key_ver into v_enc, v_ver from public.insured r
      where r.id::text = p_id and (((select app.role()) = 'insured' and id = (select app.insured_id())) or ((select app.can_any(array['insured.reveal_pii', 'assist.insured.reveal_pii']::text[])) and (select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[]))) or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (client_id = (select app.company_id()))) or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.my_family_ids())::uuid[]))) or ((select app.is_clinic()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.clinic_patient_ids())::uuid[]))) or ((select app.is_assist()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (app.assist_covers(policy_id, current_date))) )));
  end if;
  if p_table = 'insured' and p_field = 'phone' then
    select r.phone_enc, r.phone_key_ver into v_enc, v_ver from public.insured r
      where r.id::text = p_id and (((select app.role()) = 'insured' and id = (select app.insured_id())) or ((select app.can_any(array['insured.reveal_pii', 'assist.insured.reveal_pii']::text[])) and (select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[]))) or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (client_id = (select app.company_id()))) or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.my_family_ids())::uuid[]))) or ((select app.is_clinic()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.clinic_patient_ids())::uuid[]))) or ((select app.is_assist()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (app.assist_covers(policy_id, current_date))) )));
  end if;
  if p_table = 'family_requests' and p_field = 'pinfl' then
    select r.pinfl_enc, r.pinfl_key_ver into v_enc, v_ver from public.family_requests r
      where r.id::text = p_id and (((select app.role()) = 'insured' and employee_id = (select app.insured_id())) or ((select app.can_any(array['insured.reveal_pii']::text[])) and (select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['insured.read', 'policy_changes.decide', 'family.self_service', 'family.requests.decide']::text[]))) or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'policy_changes.decide', 'family.self_service', 'family.requests.decide']::text[])) and (client_id = (select app.company_id()))) or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'policy_changes.decide', 'family.self_service', 'family.requests.decide']::text[])) and (employee_id = (select app.insured_id()))) )));
  end if;
  if v_enc is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;
  perform app.audit('reveal_pii', 'insured', p_id, null, p_field || ': ' || p_reason, app.assistance_id(), p_actor_name);
  return query select v_enc, v_ver;
end $$;
comment on function app.reveal(text, text, text, text, text) is 'Ciphertext of an identity field for an allowed role, audited (BACKEND_SPEC §5).';

-- Lists of insured persons: no ciphertexts, the birth date and email masked (security_invoker: RLS of the caller applies).
create view public.insured_masked with (security_invoker = true) as
  select id, client_id, client_name, policy_id, full_name, position, relation, principal_id, is_student, age_limit, app_status, my_id_verified, attached_clinic_id, insured_from, status, certificate_number, contract_id, external_certificate_number, migration, pinfl_hmac, pinfl_mask, phone_hmac, phone_mask, payout_card_mask, consent_given_at, added_at, excluded_from, updated_at, user_id, migrated_used, migrated_premium, _pos, _created_at, _updated_at, _created_by,
    '••.••.' || to_char(birth_date, 'YYYY') as birth_date_masked,
    app.mask_email(email) as email_masked
  from public.insured;
comment on view public.insured_masked is 'Masked list view of insured persons (BACKEND_SPEC §6): the API uses it for lists.';

revoke execute on all functions in schema app from public;
grant execute on all functions in schema app to authenticated, service_role;
