-- Narrow facts (docs/PRIVILEGED_AUDIT.md): counts, codes and anonymous figures of rows the caller's RLS hides; side effects in another party's feed.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/facts.ts. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

create or replace function app.fact_client_insured_count(p_client uuid) returns integer
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select count(*)::int from public.insured i where i.client_id = p_client and i.status = 'active');
end $$;
comment on function app.fact_client_insured_count(uuid) is 'Active insured persons of a client the caller sees (the client card counter).';
revoke execute on function app.fact_client_insured_count(uuid) from public;
grant execute on function app.fact_client_insured_count(uuid) to authenticated, service_role;

create or replace function app.fact_client_legal_form(p_client uuid) returns text
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() or p_client = app.company_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select c.legal_form from public.clients c where c.id = p_client);
end $$;
comment on function app.fact_client_legal_form(uuid) is 'Legal form shown next to a client name (MIG staff; HR — the own company).';
revoke execute on function app.fact_client_legal_form(uuid) from public;
grant execute on function app.fact_client_legal_form(uuid) to authenticated, service_role;

create or replace function app.fact_client_claim_figures(p_client uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
      'category', c.category, 'serviceDate', c.service_date::text, 'createdAt', to_char(c.created_at at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'),
      'status', c.status, 'amountClaimed', c.amount_claimed, 'amountApproved', c.amount_approved)) order by c._pos), '[]'::jsonb)
    from public.claims c where c.client_id = p_client);
end $$;
comment on function app.fact_client_claim_figures(uuid) is 'Anonymous figures (category, dates, status, amounts) of the claims of a client, for clients.read: loss statistics.';
revoke execute on function app.fact_client_claim_figures(uuid) from public;
grant execute on function app.fact_client_claim_figures(uuid) to authenticated, service_role;

create or replace function app.fact_client_invoice_figures(p_client uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_build_object('number', i.number, 'amount', i.amount, 'issuedAt', i.issued_at::text) order by i._pos), '[]'::jsonb)
    from public.invoices i where i.client_id = p_client);
end $$;
comment on function app.fact_client_invoice_figures(uuid) is 'Number, amount and date of the invoices of a client, for clients.read (the last invoice of the client card).';
revoke execute on function app.fact_client_invoice_figures(uuid) from public;
grant execute on function app.fact_client_invoice_figures(uuid) to authenticated, service_role;

create or replace function app.fact_policy_brief(p_policy uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.policies p where p.id = p_policy and exists (select 1 from public.clients v where v.id = p.client_id and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) ))))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('number', p.number, 'startDate', p.start_date::text) from public.policies p where p.id = p_policy);
end $$;
comment on function app.fact_policy_brief(uuid) is 'Number and start date of a policy of a client the caller reads (the client card).';
revoke execute on function app.fact_policy_brief(uuid) from public;
grant execute on function app.fact_policy_brief(uuid) to authenticated, service_role;

create or replace function app.fact_client_history(p_client uuid, p_limit integer) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name, 'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label, 'assistanceId', a.assistance_id)) as j
      from public.audit_log a
      where a.action <> all(array['reveal_pii', 'open_medical']) and a.target_id = any(
        array[p_client::text]
        || array(select p.id::text from public.policies p where p.client_id = p_client)
        || array(select c.id::text from public.claims c where c.client_id = p_client)
        || array(select k.id::text from public.kp k where k.client_id = p_client))
      order by a._pos limit greatest(p_limit, 0)) e);
end $$;
comment on function app.fact_client_history(uuid, integer) is 'Audit entries about a client, its policies, claims and offers (no openings of personal or medical data, no reasons), for clients.read.';
revoke execute on function app.fact_client_history(uuid, integer) from public;
grant execute on function app.fact_client_history(uuid, integer) to authenticated, service_role;

create or replace function app.fact_company_claim_count(p_client uuid, p_since_ms bigint) returns integer
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.role() = 'hr' and p_client = app.company_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select count(*)::int from public.claims c join public.insured i on i.id = c.insured_id
      where i.client_id = p_client and i.status = 'active' and c.created_at >= to_timestamp(p_since_ms / 1000.0));
end $$;
comment on function app.fact_company_claim_count(uuid, bigint) is 'Number of claims of the active persons of the own company since a moment (HR statistics, shown k-anonymous): HR never reads claims.';
revoke execute on function app.fact_company_claim_count(uuid, bigint) from public;
grant execute on function app.fact_company_claim_count(uuid, bigint) to authenticated, service_role;

create or replace function app.fact_person_access_log(p_insured uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() and app.role() <> 'accountant' and (select app.can('insured.read')) and exists (select 1 from public.insured v where v.id = p_insured and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[]))) or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (client_id = (select app.company_id()))) or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.my_family_ids())::uuid[]))) or ((select app.is_clinic()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.clinic_patient_ids())::uuid[]))) or ((select app.is_assist()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (app.assist_covers(policy_id, current_date))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name, 'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label, 'reason', a.reason, 'assistanceId', a.assistance_id)) order by a._pos), '[]'::jsonb) from public.audit_log a
      where a.target_id = p_insured::text and a.action in ('reveal_pii', 'open_medical'));
end $$;
comment on function app.fact_person_access_log(uuid) is 'Openings of personal and medical data of a person the caller reads (the access log of the card): MIG card readers.';
revoke execute on function app.fact_person_access_log(uuid) from public;
grant execute on function app.fact_person_access_log(uuid) to authenticated, service_role;

create or replace function app.fact_own_audit_entries(p_actor uuid, p_actions text[], p_limit integer) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() and p_actor = app.uid() and p_actions <@ array['reveal_pii', 'open_medical']), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name, 'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label, 'reason', a.reason, 'assistanceId', a.assistance_id)) as j from public.audit_log a
      where a.actor_id = p_actor and a.action = any(p_actions) order by a._pos limit p_limit) e);
end $$;
comment on function app.fact_own_audit_entries(uuid, text[], integer) is 'The caller’s own openings of personal and medical data (the doctor’s desktop): a MIG employee, own entries only.';
revoke execute on function app.fact_own_audit_entries(uuid, text[], integer) from public;
grant execute on function app.fact_own_audit_entries(uuid, text[], integer) to authenticated, service_role;

create or replace function app.fact_advance_deal(p_deal uuid, p_stage text, p_order text[], p_at timestamptz) returns boolean
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() or (app.role() = 'hr' and app.client_of_deal(p_deal) = app.company_id())), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  declare
    v text;
  begin
    select d.stage into v from public.deals d where d.id = p_deal for update;
    if v is null or v = 'lost' then
      return false;
    end if;
    if coalesce(array_position(p_order, p_stage), 0) <= coalesce(array_position(p_order, v), 0) and p_stage <> v then
      return false;
    end if;
    if p_stage <> v then
      update public.deals set stage = p_stage, updated_at = p_at where id = p_deal;
    end if;
    return true;
  end;
end $$;
comment on function app.fact_advance_deal(uuid, text, text[], timestamptz) is 'Moves a deal forward along the pipeline order (never back, never out of lost) after an event of any party: MIG staff, HR of the own company.';
revoke execute on function app.fact_advance_deal(uuid, text, text[], timestamptz) from public;
grant execute on function app.fact_advance_deal(uuid, text, text[], timestamptz) to authenticated, service_role;

create or replace function app.fact_push_clinic_event(p_id uuid, p_clinic uuid, p_at timestamptz, p_text text) returns void
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.clinics c where c.id = p_clinic) and (not app.is_clinic() or p_clinic = app.clinic_id()) and length(p_text) <= 2000), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  insert into public.clinic_events (id, clinic_id, "at", "text", _pos) values (p_id, p_clinic, p_at, p_text, -nextval('app.pos_seq'));
  delete from public.clinic_events where id in (select e.id from public.clinic_events e order by e._pos offset 500);
end $$;
comment on function app.fact_push_clinic_event(uuid, uuid, timestamptz, text) is 'An event in the feed of a clinic cabinet caused by any party (a booking, a referral, a decision); the newest ${CLINIC_EVENTS_KEPT} are kept. A clinic writes only into its own feed.';
revoke execute on function app.fact_push_clinic_event(uuid, uuid, timestamptz, text) from public;
grant execute on function app.fact_push_clinic_event(uuid, uuid, timestamptz, text) to authenticated, service_role;

create or replace function app.fact_append_client_log(p_client uuid, p_entry jsonb) returns void
  language plpgsql volatile security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((app.is_staff() or (app.role() = 'hr' and p_client = app.company_id())) and jsonb_typeof(p_entry) = 'object' and length(p_entry::text) <= 4000), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  update public.clients set log = jsonb_build_array(jsonb_build_object('at', p_entry ->> 'at', 'text', p_entry ->> 'text')) || coalesce(log, '[]'::jsonb) where id = p_client;
end $$;
comment on function app.fact_append_client_log(uuid, jsonb) is 'A line at the top of the activity log of a client after an action on a request: MIG staff, HR of the own company (who may not update the client).';
revoke execute on function app.fact_append_client_log(uuid, jsonb) from public;
grant execute on function app.fact_append_client_log(uuid, jsonb) to authenticated, service_role;
