-- Row level security on every table of `public` (BACKEND_SPEC §6), generated from the access rules of schema.ts and the permissions matrix.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/schema.ts and friends. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.


-- Nobody but the API reaches the database; the anon role gets nothing.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;

-- staff: Every MIG employee sees colleagues (names, roles, signatories); the admin manages accounts and authority.
alter table public.staff enable row level security;
create policy staff_select on public.staff for select to authenticated
  using ((select app.active()) and ((select app.is_staff())));
create policy staff_insert on public.staff for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage', 'staff.authority.manage']::text[]))));
create policy staff_update on public.staff for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage', 'staff.authority.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage', 'staff.authority.manage']::text[]))));
grant select, insert, update on public.staff to authenticated;

-- hr_users: HR sees only the own account; the sales manager creates the HR account of a won client.
alter table public.hr_users enable row level security;
create policy hr_users_select on public.hr_users for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clients.read', 'users.manage', 'deals.manage']::text[])))
      or ((select app.role()) = 'hr' and (id = (select app.uid())))
    ));
create policy hr_users_insert on public.hr_users for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage', 'deals.manage', 'leads.manage']::text[]))));
create policy hr_users_update on public.hr_users for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage', 'deals.manage', 'leads.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage', 'deals.manage', 'leads.manage']::text[]))));
grant select, insert, update on public.hr_users to authenticated;

-- clients: MIG staff with client access; HR — the own company only (name, requisites).
alter table public.clients enable row level security;
create policy clients_select on public.clients for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[])))
      or ((select app.role()) = 'hr' and (id = (select app.company_id())))
    ));
create policy clients_insert on public.clients for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clients.write', 'leads.manage', 'deals.manage', 'contracts.draft', 'assistance.assign', 'migration.manage']::text[]))));
create policy clients_update on public.clients for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clients.write', 'leads.manage', 'deals.manage', 'contracts.draft', 'assistance.assign', 'migration.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clients.write', 'leads.manage', 'deals.manage', 'contracts.draft', 'assistance.assign', 'migration.manage']::text[]))));
grant select, insert, update on public.clients to authenticated;

-- policies: HR — policies of the own company; the insured — the own policy; an assistance company — policies assigned to it today.
alter table public.policies enable row level security;
create policy policies_select on public.policies for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policies.read', 'policies.write', 'assistance.assign', 'contracts.read', 'claims.read', 'insured.read', 'assist.insured.search']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policies.read', 'policies.write', 'assistance.assign', 'contracts.read', 'claims.read', 'insured.read', 'assist.insured.search']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['policies.read', 'policies.write', 'assistance.assign', 'contracts.read', 'claims.read', 'insured.read', 'assist.insured.search']::text[])) and (id = (select app.my_policy_id())))
      or ((select app.is_assist()) and (select app.can_any(array['policies.read', 'policies.write', 'assistance.assign', 'contracts.read', 'claims.read', 'insured.read', 'assist.insured.search']::text[])) and (app.assist_covers(id, current_date)))
    ));
create policy policies_insert on public.policies for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['policies.write', 'assistance.assign', 'contracts.draft', 'policy_changes.decide']::text[]))));
create policy policies_update on public.policies for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['policies.write', 'assistance.assign', 'contracts.draft', 'policy_changes.decide']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['policies.write', 'assistance.assign', 'contracts.draft', 'policy_changes.decide']::text[]))));
grant select, insert, update on public.policies to authenticated;

-- insured: HR — employees of the own company; the insured — self and the own family (names); a clinic — patients with an open visit; an assistance company — persons of policies assigned to it today. Ciphertexts of PINFL and phone are not readable by `authenticated` (column privileges); lists use the view `insured_masked`.
alter table public.insured enable row level security;
create policy insured_select on public.insured for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.my_family_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.clinic_patient_ids())::uuid[])))
      or ((select app.is_assist()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (app.assist_covers(policy_id, current_date)))
    ));
create policy insured_insert on public.insured for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage']::text[])) and (client_id = (select app.company_id())))
    ));
create policy insured_update on public.insured for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage', 'family.self_service']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage', 'family.self_service']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage', 'family.self_service']::text[])) and (id = (select app.insured_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage', 'family.self_service']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage', 'family.self_service']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['policies.write', 'policy_changes.decide', 'hr.employees.manage', 'family.self_service']::text[])) and (id = (select app.insured_id())))
    ));
grant select (id, client_id, client_name, policy_id, full_name, position, relation, principal_id, is_student, age_limit, app_status, my_id_verified, attached_clinic_id, insured_from, status, certificate_number, contract_id, external_certificate_number, migration, birth_date, pinfl_hmac, pinfl_mask, phone_hmac, phone_mask, email, payout_card_mask, consent_given_at, added_at, excluded_from, updated_at, user_id, migrated_used, migrated_premium, _pos, _created_at, _updated_at, _created_by) on public.insured to authenticated;
grant insert, update on public.insured to authenticated;

-- claims: The insured — own claims, children’s and of adults who gave consent (appeal, new claim); an assistance company — claims of persons assigned to it on the service date (reimbursements it handles).
alter table public.claims enable row level security;
create policy claims_select on public.claims for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['claims.read', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'assist.registries.review', 'assist.cases.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['claims.read', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'assist.registries.review', 'assist.cases.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_assist()) and (select app.can_any(array['claims.read', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'assist.registries.review', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, service_date)))
    ));
create policy claims_insert on public.claims for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['claims.create', 'claims.decide', 'registries.review', 'assist.cases.manage', 'assist.registries.review']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['claims.create', 'claims.decide', 'registries.review', 'assist.cases.manage', 'assist.registries.review']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_assist()) and (select app.can_any(array['claims.create', 'claims.decide', 'registries.review', 'assist.cases.manage', 'assist.registries.review']::text[])) and (app.assist_covers_insured(insured_id, service_date)))
    ));
create policy claims_update on public.claims for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['claims.transition', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'claims.create', 'assist.registries.review', 'assist.cases.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['claims.transition', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'claims.create', 'assist.registries.review', 'assist.cases.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_assist()) and (select app.can_any(array['claims.transition', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'claims.create', 'assist.registries.review', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, service_date)))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['claims.transition', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'claims.create', 'assist.registries.review', 'assist.cases.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['claims.transition', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'claims.create', 'assist.registries.review', 'assist.cases.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_assist()) and (select app.can_any(array['claims.transition', 'claims.decide', 'claims.medical_opinion', 'claims.reserves', 'claims.create', 'assist.registries.review', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, service_date)))
    ));
grant select, insert, update on public.claims to authenticated;

-- appointments: The insured books for self and the family; a clinic — appointments of the own clinic; an assistance company — of persons assigned to it on the visit date.
alter table public.appointments enable row level security;
create policy appointments_select on public.appointments for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.read', 'appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['appointments.read', 'appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['appointments.read', 'appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.read', 'appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (app.assist_covers_insured(insured_id, (starts_at at time zone (select app.tz()))::date)))
    ));
create policy appointments_insert on public.appointments for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (app.assist_covers_insured(insured_id, (starts_at at time zone (select app.tz()))::date)))
    ));
create policy appointments_update on public.appointments for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (app.assist_covers_insured(insured_id, (starts_at at time zone (select app.tz()))::date)))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (app.assist_covers_insured(insured_id, (starts_at at time zone (select app.tz()))::date)))
    ));
grant select, insert, update on public.appointments to authenticated;

-- clinics: The clinic network is public to every signed-in role (names, addresses, specialties); a clinic sees only itself; the admin manages the network.
alter table public.clinics enable row level security;
create policy clinics_select on public.clinics for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()))
      or ((select app.role()) = 'hr')
      or ((select app.role()) = 'insured')
      or ((select app.is_clinic()) and (id = (select app.clinic_id())))
      or ((select app.is_assist()))
    ));
create policy clinics_insert on public.clinics for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clinics.manage']::text[]))));
create policy clinics_update on public.clinics for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])) and (id = (select app.clinic_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])) and (id = (select app.clinic_id())))
    ));
grant select, insert, update on public.clinics to authenticated;

-- audit_log: Append-only: no INSERT/UPDATE/DELETE privilege for any role, entries are written by `app.audit()` (SECURITY DEFINER) with a hash chain. Read: the MIG admin; the assistance admin — actions of the own company.
alter table public.audit_log enable row level security;
create policy audit_log_select on public.audit_log for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['audit.read', 'assist.users.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['audit.read', 'assist.users.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
grant select on public.audit_log to authenticated;

-- limit_requests: MIG staff only (four-eyes is checked by the service).
alter table public.limit_requests enable row level security;
create policy limit_requests_select on public.limit_requests for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['limits.request_change', 'limits.approve_change', 'policies.read']::text[]))));
create policy limit_requests_insert on public.limit_requests for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['limits.request_change', 'limits.approve_change']::text[]))));
create policy limit_requests_update on public.limit_requests for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['limits.request_change', 'limits.approve_change']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['limits.request_change', 'limits.approve_change']::text[]))));
grant select, insert, update on public.limit_requests to authenticated;

-- invoices: HR sees the own company’s invoices; MIG accounting records payments.
alter table public.invoices enable row level security;
create policy invoices_select on public.invoices for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['invoices.read', 'payments.record', 'contracts.read']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['invoices.read', 'payments.record', 'contracts.read']::text[])) and (client_id = (select app.company_id())))
    ));
create policy invoices_insert on public.invoices for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record', 'contracts.draft', 'contracts.sign_mig', 'endorsements.manage']::text[]))));
create policy invoices_update on public.invoices for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record', 'contracts.draft', 'contracts.sign_mig', 'endorsements.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record', 'contracts.draft', 'contracts.sign_mig', 'endorsements.manage']::text[]))));
grant select, insert, update on public.invoices to authenticated;

-- documents: Documents of a client: MIG staff (also the policy card of policies.read) and the own company’s HR.
alter table public.documents enable row level security;
create policy documents_select on public.documents for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clients.read', 'contracts.read', 'kp.read', 'invoices.read', 'policies.read']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['clients.read', 'contracts.read', 'kp.read', 'invoices.read', 'policies.read']::text[])) and (client_id = (select app.company_id())))
    ));
create policy documents_insert on public.documents for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['kp.create', 'kp.send', 'contracts.draft', 'contracts.sign_mig', 'migration.manage', 'clients.write']::text[]))));
create policy documents_update on public.documents for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['kp.create', 'kp.send', 'contracts.draft', 'contracts.sign_mig', 'migration.manage', 'clients.write']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['kp.create', 'kp.send', 'contracts.draft', 'contracts.sign_mig', 'migration.manage', 'clients.write']::text[]))));
grant select, insert, update on public.documents to authenticated;

-- insured_documents: Documents issued to a person (guarantee letters): MIG staff and the person (and the family that may see them).
alter table public.insured_documents enable row level security;
create policy insured_documents_select on public.insured_documents for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['insured.read']::text[])))
      or ((select app.role()) = 'insured' and (insured_id = any((select app.my_person_ids())::uuid[])))
    ));
create policy insured_documents_insert on public.insured_documents for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['insured.read']::text[]))));
grant select, insert on public.insured_documents to authenticated;

-- chat: The chat of the insured with the operator (MIG or the assigned assistance company); messages are encrypted at rest.
alter table public.chat enable row level security;
create policy chat_select on public.chat for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.manage', 'assist.cases.manage']::text[])))
      or ((select app.role()) = 'insured' and (insured_id = (select app.insured_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.manage', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, current_date)))
    ));
create policy chat_insert on public.chat for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.manage', 'assist.cases.manage']::text[])))
      or ((select app.role()) = 'insured' and (insured_id = (select app.insured_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.manage', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, current_date)))
    ));
grant select, insert on public.chat to authenticated;

-- files: File metadata: receipts of the insured, attachments of the own clinic, signed scans of the own company for HR.
alter table public.files enable row level security;
create policy files_select on public.files for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['claims.read', 'guarantees.read', 'contracts.read', 'guarantees.request', 'contracts.sign_client', 'claims.create']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['claims.read', 'guarantees.read', 'contracts.read', 'guarantees.request', 'contracts.sign_client', 'claims.create']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['claims.read', 'guarantees.read', 'contracts.read', 'guarantees.request', 'contracts.sign_client', 'claims.create']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['claims.read', 'guarantees.read', 'contracts.read', 'guarantees.request', 'contracts.sign_client', 'claims.create']::text[])) and (clinic_id = (select app.clinic_id())))
    ));
create policy files_insert on public.files for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['claims.create', 'guarantees.request', 'contracts.sign_client', 'contracts.verify_scan', 'contracts.draft']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['claims.create', 'guarantees.request', 'contracts.sign_client', 'contracts.verify_scan', 'contracts.draft']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['claims.create', 'guarantees.request', 'contracts.sign_client', 'contracts.verify_scan', 'contracts.draft']::text[])) and (insured_id = any((select app.my_person_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['claims.create', 'guarantees.request', 'contracts.sign_client', 'contracts.verify_scan', 'contracts.draft']::text[])) and (clinic_id = (select app.clinic_id())))
    ));
grant select, insert on public.files to authenticated;

-- sessions: System only (service role in the API): no policy for `authenticated`.
alter table public.sessions enable row level security;

-- challenges: System only (service role in the API): no policy for `authenticated`.
alter table public.challenges enable row level security;

-- grants: System only (service role in the API): no policy for `authenticated`.
alter table public.grants enable row level security;

-- lockouts: System only (service role in the API): no policy for `authenticated`.
alter table public.lockouts enable row level security;

-- kp: Commercial offers: MIG staff; HR — sent offers of the own company (accept or decline).
alter table public.kp enable row level security;
create policy kp_select on public.kp for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['kp.read']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['kp.read']::text[])) and (client_id = (select app.company_id()) and status <> 'draft'))
    ));
create policy kp_insert on public.kp for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['kp.create', 'deals.manage']::text[]))));
create policy kp_update on public.kp for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['kp.create', 'kp.send', 'kp.respond', 'deals.manage', 'quotes.approve']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['kp.create', 'kp.send', 'kp.respond', 'deals.manage', 'quotes.approve']::text[])) and (client_id = (select app.company_id()) and status <> 'draft'))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['kp.create', 'kp.send', 'kp.respond', 'deals.manage', 'quotes.approve']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['kp.create', 'kp.send', 'kp.respond', 'deals.manage', 'quotes.approve']::text[])) and (client_id = (select app.company_id()) and status <> 'draft'))
    ));
grant select, insert, update on public.kp to authenticated;

-- clinic_users: Users of a clinic: colleagues of the own clinic; the clinic admin manages them (MIG admin — the first admin).
alter table public.clinic_users enable row level security;
create policy clinic_users_select on public.clinic_users for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.users.manage']::text[])))
      or ((select app.is_clinic()) and (clinic_id = (select app.clinic_id())))
    ));
create policy clinic_users_insert on public.clinic_users for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.users.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.users.manage']::text[])) and (clinic_id = (select app.clinic_id())))
    ));
create policy clinic_users_update on public.clinic_users for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.users.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.users.manage']::text[])) and (clinic_id = (select app.clinic_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.users.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.users.manage']::text[])) and (clinic_id = (select app.clinic_id())))
    ));
grant select, insert, update on public.clinic_users to authenticated;

-- price_lists: Price lists: the own clinic, MIG and every assistance company (the network list is the reference of its referrals and contracts).
alter table public.price_lists enable row level security;
create policy price_lists_select on public.price_lists for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.read', 'clinics.manage', 'registries.review', 'guarantees.decide', 'assist.registries.review', 'assist.guarantees.decide', 'ai.coverage.mig', 'ai.coverage.assist']::text[])))
      or ((select app.is_clinic()) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()))
    ));
create policy price_lists_insert on public.price_lists for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
    ));
create policy price_lists_update on public.price_lists for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
    ));
grant select, insert, update on public.price_lists to authenticated;

-- card_tokens: The insured issues QR/short-code tokens of the own card and of the active family under them (FAMILY_SPEC: card); a clinic redeems a token through app.fact_redeem_card_token, not by reading the table.
alter table public.card_tokens enable row level security;
create policy card_tokens_select on public.card_tokens for select to authenticated
  using ((select app.active()) and ((select app.role()) = 'insured' and (insured_id = any((select app.my_card_ids())::uuid[]))));
create policy card_tokens_insert on public.card_tokens for insert to authenticated
  with check ((select app.active()) and ((select app.role()) = 'insured' and (insured_id = any((select app.my_card_ids())::uuid[]))));
create policy card_tokens_delete on public.card_tokens for delete to authenticated
  using ((select app.active()) and ((select app.role()) = 'insured' and (insured_id = any((select app.my_card_ids())::uuid[]))));
grant select, insert, delete on public.card_tokens to authenticated;

-- visits: Visits open access of a clinic to a patient: the own clinic; an assistance company opens a visit for a person assigned to it.
alter table public.visits enable row level security;
create policy visits_select on public.visits for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['guarantees.read', 'registries.review', 'clinic.check_patient', 'assist.guarantees.decide', 'assist.registries.review', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, (opened_at at time zone (select app.tz()))::date)))
    ));
create policy visits_insert on public.visits for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_clinic()) and (select app.can_any(array['clinic.check_patient', 'assist.cases.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.check_patient', 'assist.cases.manage']::text[])) and (app.assist_covers_insured(insured_id, (opened_at at time zone (select app.tz()))::date)))
    ));
grant select, insert on public.visits to authenticated;

-- check_locks: System only (service role in the API): no policy for `authenticated`.
alter table public.check_locks enable row level security;

-- guarantees: Guarantee letters: the requesting clinic; the deciding assistance company; MIG doctors (escalations and clients without an assistance company).
alter table public.guarantees enable row level security;
create policy guarantees_select on public.guarantees for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['guarantees.read', 'guarantees.decide', 'assist.guarantees.decide', 'qa.review', 'guarantees.request', 'assist.cases.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['guarantees.read', 'guarantees.decide', 'assist.guarantees.decide', 'qa.review', 'guarantees.request', 'assist.cases.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['guarantees.read', 'guarantees.decide', 'assist.guarantees.decide', 'qa.review', 'guarantees.request', 'assist.cases.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy guarantees_insert on public.guarantees for insert to authenticated
  with check ((select app.active()) and ((select app.is_clinic()) and (select app.can_any(array['guarantees.request']::text[])) and (clinic_id = (select app.clinic_id()))));
create policy guarantees_update on public.guarantees for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['guarantees.decide', 'assist.guarantees.decide', 'guarantees.request']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['guarantees.decide', 'assist.guarantees.decide', 'guarantees.request']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['guarantees.decide', 'assist.guarantees.decide', 'guarantees.request']::text[])) and (assistance_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['guarantees.decide', 'assist.guarantees.decide', 'guarantees.request']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['guarantees.decide', 'assist.guarantees.decide', 'guarantees.request']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['guarantees.decide', 'assist.guarantees.decide', 'guarantees.request']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
grant select, insert, update on public.guarantees to authenticated;

-- registries: Registries of services: the own clinic; an assistance company — registries with lines it pays; MIG review and payment.
alter table public.registries enable row level security;
create policy registries_select on public.registries for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['registries.review', 'registries.pay', 'rebills.review', 'registries.submit', 'clinic.check_patient', 'assist.registries.review', 'assist.clinic_payments.record']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['registries.review', 'registries.pay', 'rebills.review', 'registries.submit', 'clinic.check_patient', 'assist.registries.review', 'assist.clinic_payments.record']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['registries.review', 'registries.pay', 'rebills.review', 'registries.submit', 'clinic.check_patient', 'assist.registries.review', 'assist.clinic_payments.record']::text[])) and (app.registry_has_payer(lines, (select app.assistance_id()))))
    ));
create policy registries_insert on public.registries for insert to authenticated
  with check ((select app.active()) and ((select app.is_clinic()) and (select app.can_any(array['registries.submit']::text[])) and (clinic_id = (select app.clinic_id()))));
create policy registries_update on public.registries for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['registries.review', 'registries.pay', 'registries.submit', 'assist.registries.review', 'assist.clinic_payments.record']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['registries.review', 'registries.pay', 'registries.submit', 'assist.registries.review', 'assist.clinic_payments.record']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['registries.review', 'registries.pay', 'registries.submit', 'assist.registries.review', 'assist.clinic_payments.record']::text[])) and (app.registry_has_payer(lines, (select app.assistance_id()))))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['registries.review', 'registries.pay', 'registries.submit', 'assist.registries.review', 'assist.clinic_payments.record']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['registries.review', 'registries.pay', 'registries.submit', 'assist.registries.review', 'assist.clinic_payments.record']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['registries.review', 'registries.pay', 'registries.submit', 'assist.registries.review', 'assist.clinic_payments.record']::text[])) and (app.registry_has_payer(lines, (select app.assistance_id()))))
    ));
grant select, insert, update on public.registries to authenticated;

-- integration_clients: API keys of a partner (`clinic_id` is the partner: a clinic or an assistance company); `secret_hash` is not readable by `authenticated`.
alter table public.integration_clients enable row level security;
create policy integration_clients_select on public.integration_clients for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
create policy integration_clients_insert on public.integration_clients for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
create policy integration_clients_update on public.integration_clients for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
grant select (id, clinic_id, partner_type, name, client_id, secret_last4, scopes, ip_allowlist, created_at, last_used_at, revoked_at, _pos, _created_at, _updated_at, _created_by) on public.integration_clients to authenticated;
grant insert, update on public.integration_clients to authenticated;

-- access_tokens: System only (service role in the API): no policy for `authenticated`.
alter table public.access_tokens enable row level security;

-- webhooks: Webhook endpoints of a partner; the signing secret is encrypted and not readable by `authenticated`.
alter table public.webhooks enable row level security;
create policy webhooks_select on public.webhooks for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
create policy webhooks_insert on public.webhooks for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
create policy webhooks_update on public.webhooks for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
grant select (id, clinic_id, partner_type, url, events, secret_last4, active, created_at, _pos, _created_at, _updated_at, _created_by) on public.webhooks to authenticated;
grant insert, update on public.webhooks to authenticated;

-- webhook_deliveries: Delivery log of webhooks: read by the partner, whose integration admin records a manual retry; written by the API outbox (system).
alter table public.webhook_deliveries enable row level security;
create policy webhook_deliveries_select on public.webhook_deliveries for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
create policy webhook_deliveries_update on public.webhook_deliveries for update to authenticated
  using ((select app.active()) and (
      ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_clinic()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinic.integration.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
grant select, update on public.webhook_deliveries to authenticated;

-- idempotency: System only (service role in the API): no policy for `authenticated`.
alter table public.idempotency enable row level security;

-- api_logs: Partner API call log (no values): read by the partner and the MIG admin; written by the API (system).
alter table public.api_logs enable row level security;
create policy api_logs_select on public.api_logs for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['clinics.manage', 'clinic.integration.manage', 'assistance.manage', 'assist.integration.manage']::text[])) and (clinic_id = (select app.assistance_id())))
    ));
grant select on public.api_logs to authenticated;

-- clinic_events: Event feed of a clinic cabinet: the own clinic; written as a side effect by the API (system).
alter table public.clinic_events enable row level security;
create policy clinic_events_select on public.clinic_events for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage']::text[])))
      or ((select app.is_clinic()) and (clinic_id = (select app.clinic_id())))
    ));
grant select on public.clinic_events to authenticated;

-- policy_changes: HR requests changes of the own company’s insured list; the underwriter decides. The new person’s data is encrypted.
alter table public.policy_changes enable row level security;
create policy policy_changes_select on public.policy_changes for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policy_changes.read', 'policy_changes.decide', 'family.requests.decide']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policy_changes.read', 'policy_changes.decide', 'family.requests.decide']::text[])) and (client_id = (select app.company_id())))
    ));
create policy policy_changes_insert on public.policy_changes for insert to authenticated
  with check ((select app.active()) and ((select app.role()) = 'hr' and (select app.can_any(array['policy_changes.request', 'hr.employees.manage', 'family.requests.decide']::text[])) and (client_id = (select app.company_id()))));
create policy policy_changes_update on public.policy_changes for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policy_changes.decide', 'policy_changes.request']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policy_changes.decide', 'policy_changes.request']::text[])) and (client_id = (select app.company_id()) and status = 'pending'))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['policy_changes.decide', 'policy_changes.request']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['policy_changes.decide', 'policy_changes.request']::text[])) and (client_id = (select app.company_id()) and status = 'pending'))
    ));
grant select, insert, update on public.policy_changes to authenticated;

-- assistances: Assistance companies: names and the 24/7 phone are shown to the insured, HR and clinics; a company sees itself; the MIG admin manages them.
alter table public.assistances enable row level security;
create policy assistances_select on public.assistances for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()))
      or ((select app.role()) = 'hr')
      or ((select app.role()) = 'insured')
      or ((select app.is_clinic()))
      or ((select app.is_assist()) and (id = (select app.assistance_id())))
    ));
create policy assistances_insert on public.assistances for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['assistance.manage']::text[]))));
create policy assistances_update on public.assistances for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['assistance.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['assistance.manage']::text[]))));
grant select, insert, update on public.assistances to authenticated;

-- assist_users: Users of an assistance company: colleagues of the own company; its admin manages them.
alter table public.assist_users enable row level security;
create policy assist_users_select on public.assist_users for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assistance.manage', 'assist.users.manage']::text[])))
      or ((select app.is_assist()) and (assistance_id = (select app.assistance_id())))
    ));
create policy assist_users_insert on public.assist_users for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.users.manage', 'assistance.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.users.manage', 'assistance.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy assist_users_update on public.assist_users for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.users.manage', 'assistance.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.users.manage', 'assistance.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.users.manage', 'assistance.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.users.manage', 'assistance.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
grant select, insert, update on public.assist_users to authenticated;

-- cases: Cases of an assistance company: the own company; MIG (complaints, quality control). Free texts are encrypted.
alter table public.cases enable row level security;
create policy cases_select on public.cases for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.cases.manage', 'qa.review', 'assistance.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.cases.manage', 'qa.review', 'assistance.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy cases_insert on public.cases for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.cases.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.cases.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy cases_update on public.cases for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.cases.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.cases.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['assist.cases.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['assist.cases.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
grant select, insert, update on public.cases to authenticated;

-- rebills: Re-invoices of an assistance company to MIG: the own company; MIG review and payment.
alter table public.rebills enable row level security;
create policy rebills_select on public.rebills for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit', 'assist.registries.review']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit', 'assist.registries.review']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy rebills_insert on public.rebills for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy rebills_update on public.rebills for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[])) and (assistance_id = (select app.assistance_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
grant select, insert, update on public.rebills to authenticated;

-- qa_samples: Quality control samples: MIG doctors review; the assistance company sees the verdicts on its decisions.
alter table public.qa_samples enable row level security;
create policy qa_samples_select on public.qa_samples for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['qa.review', 'assistance.manage', 'assist.guarantees.decide', 'assist.users.manage']::text[])))
      or ((select app.is_assist()) and (select app.can_any(array['qa.review', 'assistance.manage', 'assist.guarantees.decide', 'assist.users.manage']::text[])) and (assistance_id = (select app.assistance_id())))
    ));
create policy qa_samples_update on public.qa_samples for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['qa.review']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['qa.review']::text[]))));
grant select, update on public.qa_samples to authenticated;

-- authority_changes: Authority changes (four-eyes): MIG admins.
alter table public.authority_changes enable row level security;
create policy authority_changes_select on public.authority_changes for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['staff.authority.manage', 'users.manage']::text[]))));
create policy authority_changes_insert on public.authority_changes for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['staff.authority.manage']::text[]))));
create policy authority_changes_update on public.authority_changes for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['staff.authority.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['staff.authority.manage']::text[]))));
grant select, insert, update on public.authority_changes to authenticated;

-- deals: The sales pipeline: MIG staff only.
alter table public.deals enable row level security;
create policy deals_select on public.deals for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['deals.manage', 'leads.manage', 'contracts.read', 'quotes.calculate', 'census.upload', 'kp.send', 'kp.create', 'payments.record']::text[]))));
create policy deals_insert on public.deals for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['deals.manage', 'leads.manage', 'quotes.calculate', 'quotes.approve', 'census.upload', 'kp.create', 'kp.send', 'contracts.draft', 'contracts.sign_mig', 'payments.record']::text[]))));
create policy deals_update on public.deals for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['deals.manage', 'leads.manage', 'quotes.calculate', 'quotes.approve', 'census.upload', 'kp.create', 'kp.send', 'contracts.draft', 'contracts.sign_mig', 'payments.record']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['deals.manage', 'leads.manage', 'quotes.calculate', 'quotes.approve', 'census.upload', 'kp.create', 'kp.send', 'contracts.draft', 'contracts.sign_mig', 'payments.record']::text[]))));
grant select, insert, update on public.deals to authenticated;

-- deal_events: Deal activity feed: MIG staff read it; HR writes the events of its own actions (an offer answered, a signature, a request) into the feed of the own company’s deal.
alter table public.deal_events enable row level security;
create policy deal_events_select on public.deal_events for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['deals.manage', 'leads.manage', 'contracts.read', 'quotes.calculate', 'census.upload', 'kp.send', 'kp.create']::text[]))));
create policy deal_events_insert on public.deal_events for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['deals.manage', 'leads.manage', 'quotes.calculate', 'quotes.approve', 'census.upload', 'kp.create', 'kp.send', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'payments.record', 'tasks.ask']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['deals.manage', 'leads.manage', 'quotes.calculate', 'quotes.approve', 'census.upload', 'kp.create', 'kp.send', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'payments.record', 'tasks.ask']::text[])) and (app.client_of_deal(deal_id) = (select app.company_id())))
    ));
grant select, insert on public.deal_events to authenticated;

-- censuses: Anonymous census (gender, birth year): MIG sales and underwriting.
alter table public.censuses enable row level security;
create policy censuses_select on public.censuses for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['census.upload', 'quotes.calculate', 'deals.manage']::text[]))));
create policy censuses_insert on public.censuses for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['census.upload']::text[]))));
grant select, insert on public.censuses to authenticated;

-- quotes: Quotes: MIG underwriting.
alter table public.quotes enable row level security;
create policy quotes_select on public.quotes for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['quotes.calculate', 'quotes.approve', 'deals.manage', 'contracts.draft', 'kp.create']::text[]))));
create policy quotes_insert on public.quotes for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['quotes.calculate', 'quotes.approve']::text[]))));
create policy quotes_update on public.quotes for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['quotes.calculate', 'quotes.approve']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['quotes.calculate', 'quotes.approve']::text[]))));
grant select, insert, update on public.quotes to authenticated;

-- contracts: Contracts: MIG staff; HR — contracts of the own company once sent (signing, the insured list).
alter table public.contracts enable row level security;
create policy contracts_select on public.contracts for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.read', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_client']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.read', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_client']::text[])) and (client_id = (select app.company_id()) and status <> 'draft' and status <> 'legal_review'))
    ));
create policy contracts_insert on public.contracts for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['contracts.draft']::text[]))));
create policy contracts_update on public.contracts for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.originals', 'payments.record', 'endorsements.manage', 'contracts.sign_client']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.originals', 'payments.record', 'endorsements.manage', 'contracts.sign_client']::text[])) and (client_id = (select app.company_id()) and status in ('sent', 'signing', 'signed', 'active')))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.originals', 'payments.record', 'endorsements.manage', 'contracts.sign_client']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.originals', 'payments.record', 'endorsements.manage', 'contracts.sign_client']::text[])) and (client_id = (select app.company_id()) and status in ('sent', 'signing', 'signed', 'active')))
    ));
grant select, insert, update on public.contracts to authenticated;

-- contract_insured: Appendix 2 (the insured list with personal data, encrypted): MIG contract staff and the own company’s HR.
alter table public.contract_insured enable row level security;
create policy contract_insured_select on public.contract_insured for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.read', 'contracts.draft', 'contracts.sign_client']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.read', 'contracts.draft', 'contracts.sign_client']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
create policy contract_insured_insert on public.contract_insured for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.draft', 'contracts.sign_client', 'hr.employees.manage']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.draft', 'contracts.sign_client', 'hr.employees.manage']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
create policy contract_insured_update on public.contract_insured for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.draft', 'contracts.sign_client', 'hr.employees.manage']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.draft', 'contracts.sign_client', 'hr.employees.manage']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.draft', 'contracts.sign_client', 'hr.employees.manage']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.draft', 'contracts.sign_client', 'hr.employees.manage']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
grant select, insert, update on public.contract_insured to authenticated;

-- payments: Payments: MIG accounting.
alter table public.payments enable row level security;
create policy payments_select on public.payments for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record', 'invoices.read']::text[]))));
create policy payments_insert on public.payments for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))));
grant select, insert on public.payments to authenticated;

-- bank_payments: Bank statement queue: MIG accounting.
alter table public.bank_payments enable row level security;
create policy bank_payments_select on public.bank_payments for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))));
create policy bank_payments_insert on public.bank_payments for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))));
create policy bank_payments_update on public.bank_payments for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))));
grant select, insert, update on public.bank_payments to authenticated;

-- change_requests: Change requests of a contract: MIG staff; HR of the own company.
alter table public.change_requests enable row level security;
create policy change_requests_select on public.change_requests for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.read', 'endorsements.manage', 'policy_changes.read']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.read', 'endorsements.manage', 'policy_changes.read']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
create policy change_requests_insert on public.change_requests for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide', 'policy_changes.request']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide', 'policy_changes.request']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
create policy change_requests_update on public.change_requests for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide', 'policy_changes.request']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide', 'policy_changes.request']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide', 'policy_changes.request']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide', 'policy_changes.request']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
grant select, insert, update on public.change_requests to authenticated;

-- endorsements: Endorsements: MIG staff; HR of the own company (signing).
alter table public.endorsements enable row level security;
create policy endorsements_select on public.endorsements for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['contracts.read', 'endorsements.manage']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['contracts.read', 'endorsements.manage']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
create policy endorsements_insert on public.endorsements for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'policy_changes.decide']::text[]))));
create policy endorsements_update on public.endorsements for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.sign_client']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.sign_client']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.sign_client']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['endorsements.manage', 'contracts.draft', 'contracts.legal_approve', 'contracts.sign_mig', 'contracts.verify_scan', 'contracts.sign_client']::text[])) and (app.client_of_contract(contract_id) = (select app.company_id())))
    ));
grant select, insert, update on public.endorsements to authenticated;

-- migration_batches: Portfolio transfer batches: MIG admins; the uploaded files (personal data) are encrypted.
alter table public.migration_batches enable row level security;
create policy migration_batches_select on public.migration_batches for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['migration.manage', 'migration.approve']::text[]))));
create policy migration_batches_insert on public.migration_batches for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['migration.manage', 'migration.approve']::text[]))));
create policy migration_batches_update on public.migration_batches for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['migration.manage', 'migration.approve']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['migration.manage', 'migration.approve']::text[]))));
grant select, insert, update on public.migration_batches to authenticated;

-- family_consents: Consents of adult family members: given and revoked only by the owner; the viewer sees that a consent exists.
alter table public.family_consents enable row level security;
create policy family_consents_select on public.family_consents for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['insured.read']::text[])))
      or ((select app.role()) = 'insured' and (owner_id = (select app.insured_id()) or viewer_id = (select app.insured_id())))
    ));
create policy family_consents_insert on public.family_consents for insert to authenticated
  with check ((select app.active()) and ((select app.role()) = 'insured' and (select app.can_any(array['family.self_service']::text[])) and (owner_id = (select app.insured_id()))));
create policy family_consents_update on public.family_consents for update to authenticated
  using ((select app.active()) and ((select app.role()) = 'insured' and (select app.can_any(array['family.self_service']::text[])) and (owner_id = (select app.insured_id()))))
  with check ((select app.active()) and ((select app.role()) = 'insured' and (select app.can_any(array['family.self_service']::text[])) and (owner_id = (select app.insured_id()))));
grant select, insert, update on public.family_consents to authenticated;

-- family_requests: An employee asks to add a family member from the app; HR of the own company decides.
alter table public.family_requests enable row level security;
create policy family_requests_select on public.family_requests for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['insured.read', 'policy_changes.decide', 'family.self_service', 'family.requests.decide']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'policy_changes.decide', 'family.self_service', 'family.requests.decide']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'policy_changes.decide', 'family.self_service', 'family.requests.decide']::text[])) and (employee_id = (select app.insured_id())))
    ));
create policy family_requests_insert on public.family_requests for insert to authenticated
  with check ((select app.active()) and ((select app.role()) = 'insured' and (select app.can_any(array['family.self_service']::text[])) and (employee_id = (select app.insured_id()) and client_id = (select app.my_client_id()))));
create policy family_requests_update on public.family_requests for update to authenticated
  using ((select app.active()) and ((select app.role()) = 'hr' and (select app.can_any(array['family.requests.decide']::text[])) and (client_id = (select app.company_id()))))
  with check ((select app.active()) and ((select app.role()) = 'hr' and (select app.can_any(array['family.requests.decide']::text[])) and (client_id = (select app.company_id()))));
grant select (id, employee_id, client_id, full_name, birth_date, pinfl_hmac, pinfl_mask, relation, is_student, consent_at, status, created_at, decided_at, decided_by_id, decided_by_name, rejection_reason, policy_change_id, _pos, _created_at, _updated_at, _created_by) on public.family_requests to authenticated;
grant insert, update on public.family_requests to authenticated;

-- tasks: Requests between roles: MIG staff see the staff queues (and their own requests to HR); HR — requests to the own company.
alter table public.tasks enable row level security;
create policy tasks_select on public.tasks for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['tasks.receive', 'tasks.ask']::text[])) and (to_role = (select app.role()) or created_by_id = (select app.uid()) or assignee_id = (select app.uid()) or to_role <> 'hr'))
      or ((select app.role()) = 'hr' and (select app.can_any(array['tasks.receive', 'tasks.ask']::text[])) and (to_role = 'hr' and client_id = (select app.company_id())))
    ));
create policy tasks_insert on public.tasks for insert to authenticated
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['tasks.ask', 'tasks.request_hr']::text[])) and (created_by_id = (select app.uid())))
      or ((select app.role()) = 'hr' and (select app.can_any(array['tasks.ask', 'tasks.request_hr']::text[])) and (created_by_id = (select app.uid()) and client_id = (select app.company_id())))
    ));
create policy tasks_update on public.tasks for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['tasks.receive', 'tasks.ask']::text[])) and (to_role = (select app.role()) or created_by_id = (select app.uid()) or assignee_id = (select app.uid()) or to_role <> 'hr'))
      or ((select app.role()) = 'hr' and (select app.can_any(array['tasks.receive', 'tasks.ask']::text[])) and ((to_role = 'hr' or created_by_id = (select app.uid())) and client_id = (select app.company_id())))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['tasks.receive', 'tasks.ask']::text[])) and (to_role = (select app.role()) or created_by_id = (select app.uid()) or assignee_id = (select app.uid()) or to_role <> 'hr'))
      or ((select app.role()) = 'hr' and (select app.can_any(array['tasks.receive', 'tasks.ask']::text[])) and ((to_role = 'hr' or created_by_id = (select app.uid())) and client_id = (select app.company_id())))
    ));
grant select, insert, update on public.tasks to authenticated;

-- notifications: In-app notifications: anyone may notify anyone (task done, request answered), only the addressee reads and marks them.
alter table public.notifications enable row level security;
create policy notifications_select on public.notifications for select to authenticated
  using ((select app.active()) and (user_id = (select app.uid())));
create policy notifications_insert on public.notifications for insert to authenticated
  with check ((select app.active()) and true);
create policy notifications_update on public.notifications for update to authenticated
  using ((select app.active()) and (user_id = (select app.uid())))
  with check ((select app.active()) and (user_id = (select app.uid())));
grant select, insert, update on public.notifications to authenticated;

-- login_failures: System only (service role in the API): no policy for `authenticated`.
alter table public.login_failures enable row level security;

-- check_attempts: System only (service role in the API): no policy for `authenticated`.
alter table public.check_attempts enable row level security;

-- api_calls: System only (service role in the API): no policy for `authenticated`.
alter table public.api_calls enable row level security;

-- mis_slots: Free slots published by a clinic system: read by everyone who books; written by the clinic (or its API client, system).
alter table public.mis_slots enable row level security;
create policy mis_slots_select on public.mis_slots for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
      or ((select app.role()) = 'insured' and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
      or ((select app.is_clinic()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (select app.can_any(array['appointments.manage', 'clinic.appointments.manage', 'assist.appointments.manage']::text[])))
    ));
create policy mis_slots_insert on public.mis_slots for insert to authenticated
  with check ((select app.active()) and ((select app.is_clinic()) and (select app.can_any(array['clinic.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id()))));
create policy mis_slots_delete on public.mis_slots for delete to authenticated
  using ((select app.active()) and ((select app.is_clinic()) and (select app.can_any(array['clinic.appointments.manage']::text[])) and (clinic_id = (select app.clinic_id()))));
grant select, insert, delete on public.mis_slots to authenticated;

-- sms_outbox: Imitated SMS invitations (stage 1): MIG admin; written by the API (system).
alter table public.sms_outbox enable row level security;
create policy sms_outbox_select on public.sms_outbox for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['users.manage']::text[]))));
grant select on public.sms_outbox to authenticated;

-- assignments: Assignment of policies to assistance companies by date: MIG staff; a company sees its own assignments.
alter table public.assignments enable row level security;
create policy assignments_select on public.assignments for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()))
      or ((select app.is_assist()) and (assistance_id = (select app.assistance_id())))
    ));
create policy assignments_insert on public.assignments for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['assistance.assign', 'contracts.draft', 'contracts.sign_mig', 'payments.record']::text[]))));
create policy assignments_update on public.assignments for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['assistance.assign']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['assistance.assign']::text[]))));
grant select, insert, update on public.assignments to authenticated;

-- clinic_contracts: Clinic contracts with a payer (MIG or an assistance company): the clinic, the payer (every user of the assistance company: its network page) and MIG.
alter table public.clinic_contracts enable row level security;
create policy clinic_contracts_select on public.clinic_contracts for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'registries.review', 'assistance.manage', 'assist.registries.review', 'clinic.check_patient']::text[])))
      or ((select app.is_clinic()) and (clinic_id = (select app.clinic_id())))
      or ((select app.is_assist()) and (payer = (select app.assistance_id())::text))
    ));
create policy clinic_contracts_insert on public.clinic_contracts for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'assistance.manage']::text[]))));
create policy clinic_contracts_update on public.clinic_contracts for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'assistance.manage']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['clinics.manage', 'assistance.manage']::text[]))));
grant select, insert, update on public.clinic_contracts to authenticated;

-- dms_param_changes: Parameter change requests (four-eyes): MIG staff.
alter table public.dms_param_changes enable row level security;
create policy dms_param_changes_select on public.dms_param_changes for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.read']::text[]))));
create policy dms_param_changes_insert on public.dms_param_changes for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.propose', 'dms_params.approve']::text[]))));
create policy dms_param_changes_update on public.dms_param_changes for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.propose', 'dms_params.approve']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.propose', 'dms_params.approve']::text[]))));
grant select, insert, update on public.dms_param_changes to authenticated;

-- ai_changes: AI settings changes (four-eyes): MIG admins.
alter table public.ai_changes enable row level security;
create policy ai_changes_select on public.ai_changes for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))));
create policy ai_changes_insert on public.ai_changes for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))));
create policy ai_changes_update on public.ai_changes for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))));
grant select, insert, update on public.ai_changes to authenticated;

-- ai_logs: AI call log (redacted input, no personal data): every user logs the own calls; MIG AI admins review.
alter table public.ai_logs enable row level security;
create policy ai_logs_select on public.ai_logs for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[])))
      or (user_id = (select app.uid()))
    ));
create policy ai_logs_insert on public.ai_logs for insert to authenticated
  with check ((select app.active()) and (user_id = (select app.uid())));
create policy ai_logs_update on public.ai_logs for update to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[])))
      or (user_id = (select app.uid()))
    ))
  with check ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[])))
      or (user_id = (select app.uid()))
    ));
create policy ai_logs_delete on public.ai_logs for delete to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))));
grant select, insert, update, delete on public.ai_logs to authenticated;

-- help_questions: Questions of the help «Ask a question» (redacted): the asker rates the answer; MIG AI admins review.
alter table public.help_questions enable row level security;
create policy help_questions_select on public.help_questions for select to authenticated
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[])))
      or (asker_id = (select app.uid()))
    ));
create policy help_questions_insert on public.help_questions for insert to authenticated
  with check ((select app.active()) and (asker_id = (select app.uid())));
create policy help_questions_update on public.help_questions for update to authenticated
  using ((select app.active()) and (asker_id = (select app.uid())))
  with check ((select app.active()) and (asker_id = (select app.uid())));
grant select, insert, update on public.help_questions to authenticated;

-- dms_param_values: Current values of DMS parameters (only changed ones): read by every role (limits, ages, deadlines); applied after the second confirmation.
alter table public.dms_param_values enable row level security;
create policy dms_param_values_select on public.dms_param_values for select to authenticated
  using ((select app.active()) and true);
create policy dms_param_values_insert on public.dms_param_values for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.approve']::text[]))));
create policy dms_param_values_update on public.dms_param_values for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.approve']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['dms_params.approve']::text[]))));
grant select, insert, update on public.dms_param_values to authenticated;

-- ai_settings: AI settings (one row): read by everyone (kill switch), changed by MIG AI admins.
alter table public.ai_settings enable row level security;
create policy ai_settings_select on public.ai_settings for select to authenticated
  using ((select app.active()) and true);
create policy ai_settings_update on public.ai_settings for update to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))))
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['ai.admin']::text[]))));
grant select, update on public.ai_settings to authenticated;

-- integrations_seed: Seed of the demo integration status figures (one row).
alter table public.integrations_seed enable row level security;
create policy integrations_seed_select on public.integrations_seed for select to authenticated
  using ((select app.active()) and true);
grant select on public.integrations_seed to authenticated;

-- ai_rebill_flags: AI precheck flags of rebill lines: MIG reviewers; written by the API (system).
alter table public.ai_rebill_flags enable row level security;
create policy ai_rebill_flags_select on public.ai_rebill_flags for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['rebills.review', 'rebills.pay', 'assist.rebills.submit']::text[]))));
grant select on public.ai_rebill_flags to authenticated;

-- statement_keys: Keys of imported bank statement lines: MIG accounting.
alter table public.statement_keys enable row level security;
create policy statement_keys_select on public.statement_keys for select to authenticated
  using ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))));
create policy statement_keys_insert on public.statement_keys for insert to authenticated
  with check ((select app.active()) and ((select app.is_staff()) and (select app.can_any(array['payments.record']::text[]))));
grant select, insert on public.statement_keys to authenticated;

grant select on public.insured_masked to authenticated;
grant usage on all sequences in schema public to authenticated;
