-- Narrow facts (docs/PRIVILEGED_AUDIT.md): counts, codes and anonymous figures of rows the caller's RLS hides; side effects in another party's feed.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/facts.ts. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

create or replace function app.fact_client_insured_count(p_client uuid) returns integer
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select count(*)::int from public.insured i where i.client_id = p_client and i.status = 'active');
end $$;
comment on function app.fact_client_insured_count(uuid) is 'Active insured persons of a client the caller sees (the client card counter).';
revoke execute on function app.fact_client_insured_count(uuid) from public;
grant execute on function app.fact_client_insured_count(uuid) to authenticated, service_role;

create or replace function app.fact_client_legal_form(p_client uuid) returns text
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.is_staff() or p_client = app.company_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select c.legal_form from public.clients c where c.id = p_client);
end $$;
comment on function app.fact_client_legal_form(uuid) is 'Legal form shown next to a client name (MIG staff; HR — the own company).';
revoke execute on function app.fact_client_legal_form(uuid) from public;
grant execute on function app.fact_client_legal_form(uuid) to authenticated, service_role;

create or replace function app.fact_client_claim_figures(p_client uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
      'category', c.category, 'serviceDate', c.service_date::text, 'createdAt', to_char(c.created_at at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'),
      'status', c.status, 'amountClaimed', c.amount_claimed, 'amountApproved', c.amount_approved)) order by c._pos), '[]'::jsonb)
    from public.claims c where c.client_id = p_client);
end $$;
comment on function app.fact_client_claim_figures(uuid) is 'Anonymous figures (category, dates, status, amounts) of the claims of a client, for clients.read: loss statistics.';
revoke execute on function app.fact_client_claim_figures(uuid) from public;
grant execute on function app.fact_client_claim_figures(uuid) to authenticated, service_role;

create or replace function app.fact_client_invoice_figures(p_client uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(jsonb_build_object('number', i.number, 'amount', i.amount, 'issuedAt', i.issued_at::text) order by i._pos), '[]'::jsonb)
    from public.invoices i where i.client_id = p_client);
end $$;
comment on function app.fact_client_invoice_figures(uuid) is 'Number, amount and date of the invoices of a client, for clients.read (the last invoice of the client card).';
revoke execute on function app.fact_client_invoice_figures(uuid) from public;
grant execute on function app.fact_client_invoice_figures(uuid) to authenticated, service_role;

create or replace function app.fact_policy_brief(p_policy uuid) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.policies p where p.id = p_policy and exists (select 1 from public.clients v where v.id = p.client_id and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) ))))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select jsonb_build_object('number', p.number, 'startDate', p.start_date::text) from public.policies p where p.id = p_policy);
end $$;
comment on function app.fact_policy_brief(uuid) is 'Number and start date of a policy of a client the caller reads (the client card).';
revoke execute on function app.fact_policy_brief(uuid) from public;
grant execute on function app.fact_policy_brief(uuid) to authenticated, service_role;

create or replace function app.fact_client_history(p_client uuid, p_limit integer) returns jsonb
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce(((select app.can('clients.read')) and exists (select 1 from public.clients v where v.id = p_client and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select coalesce(jsonb_agg(e.j order by e._pos), '[]'::jsonb) from (
      select a._pos, jsonb_strip_nulls(jsonb_build_object('id', a.id, 'at', to_char(a."at" at time zone app.tz(), 'YYYY-MM-DD"T"HH24:MI:SS"+05:00"'), 'actorId', a.actor_id, 'actorName', a.actor_name,
        'actorRole', a.actor_role, 'action', a.action, 'targetType', a.target_type, 'targetId', a.target_id, 'targetLabel', a.target_label,
        'assistanceId', a.assistance_id)) as j
      from public.audit_log a
      where a.action <> all(array['reveal_pii', 'open_medical']) and a.target_id = any(
        array[p_client::text]
        || array(select p.id::text from public.policies p where p.client_id = p_client)
        || array(select c.id::text from public.claims c where c.client_id = p_client)
        || array(select k.id::text from public.kp k where k.client_id = p_client))
      order by a._pos limit greatest(p_limit, 0)) e);
end $$;
comment on function app.fact_client_history(uuid, integer) is 'Audit entries about a client, its policies, claims and offers (no openings of personal or medical data, no reasons), for clients.read.';
revoke execute on function app.fact_client_history(uuid, integer) from public;
grant execute on function app.fact_client_history(uuid, integer) to authenticated, service_role;

create or replace function app.fact_company_claim_count(p_client uuid, p_since_ms bigint) returns integer
  language plpgsql stable security definer set search_path = ''
as $$
begin
  if not app.active() or not coalesce((app.role() = 'hr' and p_client = app.company_id()), false) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  return (select count(*)::int from public.claims c join public.insured i on i.id = c.insured_id
      where i.client_id = p_client and i.status = 'active' and c.created_at >= to_timestamp(p_since_ms / 1000.0));
end $$;
comment on function app.fact_company_claim_count(uuid, bigint) is 'Number of claims of the active persons of the own company since a moment (HR statistics, shown k-anonymous): HR never reads claims.';
revoke execute on function app.fact_company_claim_count(uuid, bigint) from public;
grant execute on function app.fact_company_claim_count(uuid, bigint) to authenticated, service_role;
