-- Sign-in with Supabase Auth and BFF sessions of the API (BACKEND_SPEC §7), cleanup of counters (§10).
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/migrationsAuth.ts. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

-- BFF sessions: the browser holds only the opaque cookie; the API keeps the Supabase tokens, encrypted.
-- Every row extends a row of public.sessions (the services end sessions there: logout, deactivation),
-- so deleting that row ends the BFF session too.
create table public.app_sessions (
  id_hash bytea primary key,
  session_id text not null unique references public.sessions (id) on delete cascade,
  user_id uuid not null,
  role text not null,
  aal text not null check (aal in ('aal1', 'aal2')),
  refresh_enc bytea not null,
  refresh_key_ver smallint not null,
  access_enc bytea not null,
  access_key_ver smallint not null,
  access_expires_at timestamptz not null,
  auth_session_id uuid,
  created_at timestamptz not null,
  last_activity timestamptz not null,
  ip inet,
  user_agent text check (length(user_agent) <= 512)
);
create index app_sessions_user_idx on public.app_sessions (user_id);
create index app_sessions_activity_idx on public.app_sessions (last_activity);
comment on table public.app_sessions is 'BFF sessions (BACKEND_SPEC §7): HMAC of the cookie value, the user, Supabase tokens encrypted with the personal-data key, AAL, activity, IP, user-agent. API only.';
alter table public.app_sessions enable row level security;
revoke all on public.app_sessions from public, anon, authenticated;
grant all on public.app_sessions to service_role;

-- Sign-in in progress: after the password (waiting for the TOTP code) or after the phone (waiting for the SMS code).
create table public.app_auth_challenges (
  id_hash bytea primary key,
  kind text not null check (kind in ('password', 'phone')),
  user_id uuid,
  role text,
  lock_key text not null,
  attempts integer not null default 0 check (attempts >= 0),
  factor_id uuid,
  enroll boolean not null default false,
  access_enc bytea,
  access_key_ver smallint,
  refresh_enc bytea,
  refresh_key_ver smallint,
  phone_enc bytea,
  phone_key_ver smallint,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  ip inet,
  user_agent text check (length(user_agent) <= 512)
);
create index app_auth_challenges_expires_idx on public.app_auth_challenges (expires_at);
comment on table public.app_auth_challenges is 'Sign-in challenges of the API (second step: TOTP or SMS code); tokens and the phone are encrypted. API only.';
alter table public.app_auth_challenges enable row level security;
revoke all on public.app_auth_challenges from public, anon, authenticated;
grant all on public.app_auth_challenges to service_role;

-- Accounts whose Supabase Auth user must follow a change of our tables (new account, role, binding, deactivation):
-- the API's worker creates or updates the user with the service role and sends invitations.
create table app.identity_sync (
  user_id uuid primary key,
  requested_at timestamptz not null default now(),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text
);
comment on table app.identity_sync is 'Outbox of account changes for Supabase Auth (the API worker syncs app_metadata, bans, invitations).';
revoke all on app.identity_sync from public, authenticated;
grant select, insert, update, delete on app.identity_sync to service_role;

create or replace function app.request_identity_sync() returns trigger
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_user uuid;
begin
  -- The seed provisions its users itself (supabase/seed.sql).
  if coalesce(current_setting('mig.seeding', true), '') = 'on' then
    return null;
  end if;
  v_user := nullif(to_jsonb(new) ->> tg_argv[0], '')::uuid;
  if v_user is not null then
    insert into app.identity_sync (user_id) values (v_user)
      on conflict (user_id) do update set requested_at = now(), attempts = 0, next_attempt_at = now(), last_error = null;
  end if;
  return null;
end $$;
create trigger staff_identity_sync after insert or update of email, role, active on public.staff
  for each row execute function app.request_identity_sync('id');
create trigger hr_users_identity_sync after insert or update of email, company_id on public.hr_users
  for each row execute function app.request_identity_sync('id');
create trigger clinic_users_identity_sync after insert or update of email, role, active, clinic_id on public.clinic_users
  for each row execute function app.request_identity_sync('id');
create trigger assist_users_identity_sync after insert or update of email, role, active, assistance_id on public.assist_users
  for each row execute function app.request_identity_sync('id');
create trigger insured_identity_sync after insert or update of phone_hmac, status, user_id on public.insured
  for each row execute function app.request_identity_sync('user_id');

-- The API worker takes queued jobs (pg_cron puts them) with the service role.
grant select, update, delete on app.job_queue to service_role;

-- Custom Access Token Hook of Supabase Auth: the claims keep only the roles and bindings of app_metadata
-- (set by the API with the service role); user_metadata never carries rights and is dropped from the token.
create or replace function public.custom_access_token_hook(event jsonb) returns jsonb
  language plpgsql stable set search_path = ''
as $$
declare
  v_claims jsonb := coalesce(event -> 'claims', '{}'::jsonb);
  v_meta jsonb := coalesce(event -> 'claims' -> 'app_metadata', '{}'::jsonb);
  v_out jsonb := '{}'::jsonb;
  k text;
begin
  foreach k in array array['provider', 'providers', 'role', 'company_id', 'clinic_id', 'assistance_id', 'insured_id'] loop
    if v_meta ? k then
      v_out := v_out || jsonb_build_object(k, v_meta -> k);
    end if;
  end loop;
  v_claims := jsonb_set(v_claims, '{app_metadata}', v_out);
  v_claims := jsonb_set(v_claims, '{user_metadata}', '{}'::jsonb);
  return jsonb_build_object('claims', v_claims);
end $$;
comment on function public.custom_access_token_hook(jsonb) is 'Supabase Auth hook: JWT claims carry app_metadata role and bindings only (BACKEND_SPEC §7).';
revoke execute on function public.custom_access_token_hook(jsonb) from public, anon, authenticated;
do $do$
begin
  if exists (select 1 from pg_roles where rolname = 'supabase_auth_admin') then
    grant usage on schema public to supabase_auth_admin;
    grant execute on function public.custom_access_token_hook(jsonb) to supabase_auth_admin;
  end if;
end
$do$;

-- Expired sessions, challenges, attempt counters and tokens (epoch columns are milliseconds).
create or replace function app.job_cleanup_expired() returns jsonb
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_now bigint := (extract(epoch from now()) * 1000)::bigint;
  v_day bigint := 24 * 3600 * 1000;
  v jsonb := '{}'::jsonb;
  n bigint;
begin
  delete from public.sessions where last_activity < v_now - 12 * 3600 * 1000; get diagnostics n = row_count; v := v || jsonb_build_object('sessions', n);
  delete from public.challenges where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('challenges', n);
  delete from public.grants where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('grants', n);
  delete from public.lockouts where until < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('lockouts', n);
  delete from public.login_failures where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('login_failures', n);
  delete from public.check_attempts where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('check_attempts', n);
  delete from public.check_locks where until < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('check_locks', n);
  delete from public.card_tokens where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('card_tokens', n);
  delete from public.access_tokens where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('access_tokens', n);
  delete from public.idempotency where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('idempotency', n);
  delete from public.api_calls where "at" < v_now - 3600 * 1000; get diagnostics n = row_count; v := v || jsonb_build_object('api_calls', n);
  delete from public.sessions s using public.app_sessions a where a.session_id = s.id and a.last_activity < now() - interval '31 minutes'; get diagnostics n = row_count; v := v || jsonb_build_object('app_sessions', n);
  delete from public.app_auth_challenges where expires_at < now(); get diagnostics n = row_count; v := v || jsonb_build_object('app_auth_challenges', n);
  delete from app.job_queue where done_at < now() - interval '7 days'; get diagnostics n = row_count; v := v || jsonb_build_object('job_queue', n);
  return v;
end $$;

revoke execute on function app.request_identity_sync() from public, authenticated;
revoke execute on function app.job_cleanup_expired() from public, authenticated;
