-- Background jobs (BACKEND_SPEC §10): schedules from packages/domain/src/services/jobs.ts.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/schema.ts and friends. Do not edit by hand:
-- change the TypeScript source and run `node scripts/gen-schema.mjs`.

-- Jobs that need the domain services are queued for the API (step 4 runs them with the system context).
create table app.job_queue (
  id bigint generated always as identity primary key,
  name text not null,
  requested_at timestamptz not null default now(),
  taken_at timestamptz,
  done_at timestamptz,
  error text
);
create index job_queue_pending_idx on app.job_queue (name) where taken_at is null;
comment on table app.job_queue is 'Runs of API jobs requested by pg_cron; the API takes pending rows.';
revoke all on app.job_queue from public, authenticated;

create table app.job_catalog (
  name text primary key,
  cron text not null,
  runner text not null check (runner in ('db', 'api')),
  command text not null,
  description text not null
);
comment on table app.job_catalog is 'The schedules of jobs.ts (also registered in pg_cron when it is available).';
insert into app.job_catalog (name, cron, runner, command, description) values
  ('task-deadlines', '*/15 * * * *', 'api', 'tasks.sweepDeadlines', 'Reminders on request deadlines: «Завтра срок» and «Просрочен» (once each).'),
  ('sla-reminders', '*/10 * * * *', 'api', 'dashboard.queueFor', 'SLA of claims, guarantee letters, appointments and assistance cases: overdue items in the work queues.'),
  ('sales-reminders', '7 1 * * *', 'api', 'deals (kpNoAnswerDays, leadIdleDays)', 'Commercial offers without an answer and leads without activity (06:07 Tashkent).'),
  ('renewal-deals', '13 1 * * *', 'api', 'deals.ensureRenewalDeal (renewalLeadDays)', 'Renewal deals N days before the policy ends (06:13 Tashkent).'),
  ('contract-lifecycle', '5 19 * * *', 'api', 'lifecycle.refreshContract', 'Contracts entering into force and policies expiring (00:05 Tashkent).'),
  ('child-age-limit', '21 1 * * *', 'api', 'family.ageLimits', 'Children reaching the age limit (maxChildAge / studentMaxAge) (06:21 Tashkent).'),
  ('cleanup-expired', '*/30 * * * *', 'db', 'select app.job_cleanup_expired()', 'Expired sessions, login challenges, attempt counters, lockouts, card tokens, partner tokens and idempotency keys.'),
  ('audit-chain-check', '47 0 * * *', 'db', 'select app.job_verify_audit_chain()', 'Verifies the hash chain of the audit log; on a break notifies every MIG admin (05:47 Tashkent).');
revoke all on app.job_catalog from public, authenticated;

create or replace function app.enqueue_job(p_name text) returns void
  language sql volatile security definer set search_path = ''
as $$ insert into app.job_queue (name) values (p_name) $$;

-- Expired sessions, challenges, attempt counters and tokens (epoch columns are milliseconds).
create or replace function app.job_cleanup_expired() returns jsonb
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_now bigint := (extract(epoch from now()) * 1000)::bigint;
  v_day bigint := 24 * 3600 * 1000;
  v jsonb := '{}'::jsonb;
  n bigint;
begin
  delete from public.sessions where last_activity < v_now - 12 * 3600 * 1000; get diagnostics n = row_count; v := v || jsonb_build_object('sessions', n);
  delete from public.challenges where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('challenges', n);
  delete from public.grants where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('grants', n);
  delete from public.lockouts where until < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('lockouts', n);
  delete from public.login_failures where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('login_failures', n);
  delete from public.check_attempts where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('check_attempts', n);
  delete from public.check_locks where until < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('check_locks', n);
  delete from public.card_tokens where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('card_tokens', n);
  delete from public.access_tokens where expires_at < v_now; get diagnostics n = row_count; v := v || jsonb_build_object('access_tokens', n);
  delete from public.idempotency where "at" < v_now - v_day; get diagnostics n = row_count; v := v || jsonb_build_object('idempotency', n);
  delete from public.api_calls where "at" < v_now - 3600 * 1000; get diagnostics n = row_count; v := v || jsonb_build_object('api_calls', n);
  return v;
end $$;

-- Daily check of the audit chain: on a break every active MIG admin gets a notification.
create or replace function app.job_verify_audit_chain() returns boolean
  language plpgsql volatile security definer set search_path = ''
as $$
declare
  v record;
begin
  select * into v from app.verify_audit_chain();
  if not v.ok then
    insert into public.notifications (id, text, detail, link, created_at, read, user_id)
    select gen_random_uuid(), 'srv.auditChainBroken', v.first_broken::text, '/staff/admin/audit', now(), false, s.id
      from public.staff s where s.role = 'admin' and s.active;
  end if;
  return v.ok;
end $$;

revoke execute on all functions in schema app from public;
grant execute on all functions in schema app to authenticated, service_role;
revoke execute on function app.verify_audit_chain() from authenticated;
revoke execute on function app.audit_chain() from authenticated;
revoke execute on function app.audit_immutable() from authenticated;
revoke execute on function app.enqueue_job(text) from authenticated;
revoke execute on function app.job_cleanup_expired() from authenticated;
revoke execute on function app.job_verify_audit_chain() from authenticated;

-- pg_cron is optional: where it is missing the migration still applies and the jobs stay unscheduled.
do $do$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    perform cron.schedule('mig:task-deadlines', '*/15 * * * *', 'select app.enqueue_job(''task-deadlines'')');
    perform cron.schedule('mig:sla-reminders', '*/10 * * * *', 'select app.enqueue_job(''sla-reminders'')');
    perform cron.schedule('mig:sales-reminders', '7 1 * * *', 'select app.enqueue_job(''sales-reminders'')');
    perform cron.schedule('mig:renewal-deals', '13 1 * * *', 'select app.enqueue_job(''renewal-deals'')');
    perform cron.schedule('mig:contract-lifecycle', '5 19 * * *', 'select app.enqueue_job(''contract-lifecycle'')');
    perform cron.schedule('mig:child-age-limit', '21 1 * * *', 'select app.enqueue_job(''child-age-limit'')');
    perform cron.schedule('mig:cleanup-expired', '*/30 * * * *', 'select app.job_cleanup_expired()');
    perform cron.schedule('mig:audit-chain-check', '47 0 * * *', 'select app.job_verify_audit_chain()');
  else
    raise notice 'pg_cron is not available: background jobs are not scheduled';
  end if;
end
$do$;
