-- List queries (docs/backend/DATABASE.md, section "List queries"): collations, the search key, the claim reserve, generated
-- search-key columns and list indexes.
-- Generated by scripts/gen-schema.mjs from packages/domain/src/store/sql/listQueries.ts and schema.ts LIST_QUERIES. Do not
-- edit by hand: change the TypeScript source and run `node scripts/gen-schema.mjs`.

-- Text order of the lists (store/query.ts Collation): ICU, non-deterministic (strings ICU calls equal are a tie, broken by _pos).
create collation if not exists app.ru (provider = icu, locale = 'ru', deterministic = false);
comment on collation app.ru is 'localeCompare(…, ''ru''): text sort keys of the lists.';
create collation if not exists app.legal_name (provider = icu, locale = 'en-u-ks-level1-ka-shifted', deterministic = false);
comment on collation app.legal_name is 'config/legalForms.ts legalNameCollator: names of legal entities (case, quotes, punctuation ignored).';

create or replace function app.search_key(p_text text) returns text
  language plpgsql immutable strict parallel safe set search_path = ''
as $$
declare
  s text;
begin
  -- normalizeSearch(): lower case (full Unicode mapping, as JavaScript toLowerCase), NFC, Cyrillic into Uzbek Latin,
  -- apostrophes dropped, whitespace runs collapsed, trimmed.
  s := normalize(lower(p_text collate pg_catalog."und-x-icu"), nfc);
  s := replace(s, 'ё', 'yo');
  s := replace(s, 'ц', 'ts');
  s := replace(s, 'ч', 'ch');
  s := replace(s, 'ш', 'sh');
  s := replace(s, 'щ', 'sh');
  s := replace(s, 'ю', 'yu');
  s := replace(s, 'я', 'ya');
  s := translate(s, 'абвгдежзийклмнопрстуфхыэўқғҳъь', 'abvgdejziyklmnoprstufxieoqgh');
  s := translate(s, '''`ʻʼ‘’', '');
  s := btrim(regexp_replace(s, '[\t\n\v\f\r \u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]+', ' ', 'g'), ' ');
  -- searchKey(): the loose phonetic folding.
  s := replace(s, 'q', 'k');
  s := replace(s, 'x', 'h');
  s := replace(s, 'kh', 'h');
  s := translate(s, 'oe', 'aa');
  s := replace(s, 'yu', 'u');
  -- Runs of one character become one (JavaScript /(.)\1+/ over UTF-16 units: characters outside the BMP never repeat).
  return regexp_replace(s, '([^\U00010000-\U0010FFFF])\1+', '\1', 'g');
end
$$;
comment on function app.search_key(text) is 'lib/searchNormalize.ts searchKey(): the key the list search compares (generated *_sk columns).';
create or replace function app.claim_reserve(p_history jsonb, p_changes jsonb, p_claimed bigint, p_approved bigint) returns numeric
  language plpgsql immutable parallel safe set search_path = ''
as $$
declare
  v numeric := 0;
  nxt numeric;
  h jsonb;
  best_at text;
  best_to numeric := 0;
begin
  -- Events derived from the status history (registration, decision, refusal or payment) …
  for h in select value from jsonb_array_elements(case when jsonb_typeof(p_history) = 'array' then p_history else '[]'::jsonb end) loop
    nxt := null;
    if h ->> 'to' = 'new' and coalesce(h ->> 'from', '') = '' then nxt := p_claimed;
    elsif h ->> 'to' = 'approved' then nxt := coalesce(p_approved, p_claimed);
    elsif h ->> 'to' in ('rejected', 'paid') then nxt := 0;
    end if;
    if nxt is null or nxt = v then continue; end if;
    if best_at is null or (h ->> 'at') collate "C" >= best_at collate "C" then best_at := h ->> 'at'; best_to := nxt; end if;
    v := nxt;
  end loop;
  -- … then the explicit changes; the value is the one of the latest event (the last one of equal times).
  for h in select value from jsonb_array_elements(case when jsonb_typeof(p_changes) = 'array' then p_changes else '[]'::jsonb end) loop
    if best_at is null or (h ->> 'at') collate "C" >= best_at collate "C" then best_at := h ->> 'at'; best_to := (h ->> 'to')::numeric; end if;
  end loop;
  return best_to;
end
$$;
comment on function app.claim_reserve(jsonb, jsonb, bigint, bigint) is 'services/reserve.ts currentReserve(): the current reserve of a claim (the claims list sorts by it).';
grant execute on function app.search_key(text), app.claim_reserve(jsonb, jsonb, bigint, bigint) to authenticated, service_role;

-- The assistance roster: one array of policies per statement instead of app.assist_access per row.
create or replace function app.assist_policy_ids() returns uuid[]
  language sql stable security definer set search_path = ''
as $$
  select coalesce(array_agg(s.p), '{}') from (select distinct a.policy_id as p from public.assignments a where a.assistance_id = app.assistance_id()) s
    where app.assist_access(s.p) <> 'none'
$$;
comment on function app.assist_policy_ids is 'Policies the user’s assistance company has access to (app.assist_access), as an array: the insured SELECT policy.';
grant execute on function app.assist_policy_ids() to authenticated, service_role;
alter policy insured_select on public.insured
  using ((select app.active()) and (
      ((select app.is_staff()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])))
      or ((select app.role()) = 'hr' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (client_id = (select app.company_id())))
      or ((select app.role()) = 'insured' and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.my_family_ids())::uuid[])))
      or ((select app.is_clinic()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (id = any((select app.clinic_patient_ids())::uuid[])))
      or ((select app.is_assist()) and (select app.can_any(array['insured.read', 'assist.insured.search', 'clinic.check_patient', 'policy_changes.decide']::text[])) and (policy_id = any((select app.assist_policy_ids())::uuid[])))
    ));

-- The client list sorted by the number of insured: the counters of app.fact_client_insured_count for every client the
-- caller sees, once per statement (store/computed.ts clients.insuredCount).
create or replace function app.list_client_insured_counts() returns jsonb
  language sql stable security definer set search_path = ''
as $$
  select coalesce(jsonb_object_agg(i.client_id, i.n), '{}'::jsonb)
    from (select client_id, count(*)::int as n from public.insured where status = 'active' group by client_id) i
    where app.active() and exists (select 1 from public.clients v where v.id = i.client_id and ((select app.active()) and ( ((select app.is_staff()) and (select app.can_any(array['clients.read', 'leads.manage', 'deals.manage', 'contracts.read', 'invoices.read', 'policies.read', 'kp.read', 'policy_changes.read']::text[]))) or ((select app.role()) = 'hr' and (id = (select app.company_id()))) )))
$$;
comment on function app.list_client_insured_counts is 'Active insured persons by client (app.fact_client_insured_count) of the clients the caller sees, as one object: the sort of the client list.';
grant execute on function app.list_client_insured_counts() to authenticated, service_role;

-- clients
alter table public.clients add column name_sk text generated always as (app.search_key(name)) stored;
create index clients_name_sk_trgm_idx on public.clients using gin (name_sk extensions.gin_trgm_ops);
create index clients_name_legal_list_idx on public.clients (name collate app.legal_name, _pos);
create index clients_status_name_legal_list_idx on public.clients (status, name collate app.legal_name, _pos);
create index clients_manager_id_name_legal_list_idx on public.clients (manager_id, name collate app.legal_name, _pos);

-- policies
alter table public.policies add column number_sk text generated always as (app.search_key(number)) stored;
create index policies_number_sk_trgm_idx on public.policies using gin (number_sk extensions.gin_trgm_ops);
alter table public.policies add column client_name_sk text generated always as (app.search_key(client_name)) stored;
create index policies_client_name_sk_trgm_idx on public.policies using gin (client_name_sk extensions.gin_trgm_ops);
create index policies_end_date_list_idx on public.policies (end_date, _pos);
create index policies_client_id_end_date_list_idx on public.policies (client_id, end_date, _pos);
create index policies_status_end_date_list_idx on public.policies (status, end_date, _pos);

-- insured
alter table public.insured add column full_name_sk text generated always as (app.search_key(full_name)) stored;
create index insured_full_name_sk_trgm_idx on public.insured using gin (full_name_sk extensions.gin_trgm_ops);
grant select (full_name_sk) on public.insured to authenticated;
alter table public.insured add column position_sk text generated always as (app.search_key(position)) stored;
create index insured_position_sk_trgm_idx on public.insured using gin (position_sk extensions.gin_trgm_ops);
grant select (position_sk) on public.insured to authenticated;
create index insured_full_name_ru_list_idx on public.insured (full_name collate app.ru, _pos);
create index insured_client_id_full_name_ru_list_idx on public.insured (client_id, full_name collate app.ru, _pos);
create index insured_client_id_relation_full_name_ru_list_idx on public.insured (client_id, relation, full_name collate app.ru, _pos);
create index insured_policy_id_full_name_ru_list_idx on public.insured (policy_id, full_name collate app.ru, _pos);
create index insured_principal_id_status_list_idx on public.insured (principal_id, status, _pos);

-- claims
alter table public.claims add column number_sk text generated always as (app.search_key(number)) stored;
create index claims_number_sk_trgm_idx on public.claims using gin (number_sk extensions.gin_trgm_ops);
alter table public.claims add column insured_name_sk text generated always as (app.search_key(insured_name)) stored;
create index claims_insured_name_sk_trgm_idx on public.claims using gin (insured_name_sk extensions.gin_trgm_ops);
alter table public.claims add column client_name_sk text generated always as (app.search_key(client_name)) stored;
create index claims_client_name_sk_trgm_idx on public.claims using gin (client_name_sk extensions.gin_trgm_ops);
alter table public.claims add column external_number_sk text generated always as (app.search_key(external_number)) stored;
create index claims_external_number_sk_trgm_idx on public.claims using gin (external_number_sk extensions.gin_trgm_ops);
create index claims_created_at_list_idx on public.claims (created_at, _pos);
create index claims_status_created_at_list_idx on public.claims (status, created_at, _pos);
create index claims_client_id_created_at_list_idx on public.claims (client_id, created_at, _pos);
create index claims_insured_id_created_at_list_idx on public.claims (insured_id, created_at, _pos);

-- appointments
alter table public.appointments add column insured_name_sk text generated always as (app.search_key(insured_name)) stored;
create index appointments_insured_name_sk_trgm_idx on public.appointments using gin (insured_name_sk extensions.gin_trgm_ops);
alter table public.appointments add column clinic_name_sk text generated always as (app.search_key(clinic_name)) stored;
create index appointments_clinic_name_sk_trgm_idx on public.appointments using gin (clinic_name_sk extensions.gin_trgm_ops);
create index appointments_starts_at_list_idx on public.appointments (starts_at, _pos);
create index appointments_clinic_id_starts_at_list_idx on public.appointments (clinic_id, starts_at, _pos);
create index appointments_insured_id_starts_at_list_idx on public.appointments (insured_id, starts_at, _pos);
create index appointments_status_starts_at_list_idx on public.appointments (status, starts_at, _pos);

-- clinics
alter table public.clinics add column name_sk text generated always as (app.search_key(name)) stored;
create index clinics_name_sk_trgm_idx on public.clinics using gin (name_sk extensions.gin_trgm_ops);
alter table public.clinics add column district_sk text generated always as (app.search_key(district)) stored;
create index clinics_district_sk_trgm_idx on public.clinics using gin (district_sk extensions.gin_trgm_ops);
create index clinics_name_legal_list_idx on public.clinics (name collate app.legal_name, _pos);

-- audit
create index audit_log_actor_id_list_idx on public.audit_log (actor_id, _pos);
create index audit_log_assistance_id_list_idx on public.audit_log (assistance_id, _pos);
create index audit_log_action_list_idx on public.audit_log (action, _pos);

-- policyChanges
alter table public.policy_changes add column full_name_sk text generated always as (app.search_key(full_name)) stored;
create index policy_changes_full_name_sk_trgm_idx on public.policy_changes using gin (full_name_sk extensions.gin_trgm_ops);
alter table public.policy_changes add column position_sk text generated always as (app.search_key(position)) stored;
create index policy_changes_position_sk_trgm_idx on public.policy_changes using gin (position_sk extensions.gin_trgm_ops);
create index policy_changes_client_id_kind_relation_list_idx on public.policy_changes (client_id, kind, relation, _pos);
create index policy_changes_insured_id_kind_status_list_idx on public.policy_changes (insured_id, kind, status, _pos);
